// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: payment/payment.proto

package payment

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	common "tradegateway/proto/common"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PENDING                    PaymentStatus = 1
	PaymentStatus_PROCESSING                 PaymentStatus = 2
	PaymentStatus_CONFIRMED                  PaymentStatus = 3
	PaymentStatus_FAILED                     PaymentStatus = 4
	PaymentStatus_REFUNDED                   PaymentStatus = 5
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "PROCESSING",
		3: "CONFIRMED",
		4: "FAILED",
		5: "REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PENDING":                    1,
		"PROCESSING":                 2,
		"CONFIRMED":                  3,
		"FAILED":                     4,
		"REFUNDED":                   5,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_payment_payment_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{0}
}

type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNSPECIFIED PaymentMethod = 0
	PaymentMethod_MOJALOOP_BANK              PaymentMethod = 1
	PaymentMethod_MOJALOOP_MOBILE            PaymentMethod = 2
	PaymentMethod_BANK_TRANSFER              PaymentMethod = 3
	PaymentMethod_CUSTOMS_BOND               PaymentMethod = 4
	PaymentMethod_DUTY_DRAWBACK              PaymentMethod = 5
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		1: "MOJALOOP_BANK",
		2: "MOJALOOP_MOBILE",
		3: "BANK_TRANSFER",
		4: "CUSTOMS_BOND",
		5: "DUTY_DRAWBACK",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED": 0,
		"MOJALOOP_BANK":              1,
		"MOJALOOP_MOBILE":            2,
		"BANK_TRANSFER":              3,
		"CUSTOMS_BOND":               4,
		"DUTY_DRAWBACK":              5,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_payment_proto_enumTypes[1].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_payment_payment_proto_enumTypes[1]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{1}
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DeclarationId int64                  `protobuf:"varint,2,opt,name=declaration_id,json=declarationId,proto3" json:"declaration_id,omitempty"`
	TraderId      int64                  `protobuf:"varint,3,opt,name=trader_id,json=traderId,proto3" json:"trader_id,omitempty"`
	PaymentRef    string                 `protobuf:"bytes,4,opt,name=payment_ref,json=paymentRef,proto3" json:"payment_ref,omitempty"`
	Amount        *common.Money          `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Method        PaymentMethod          `protobuf:"varint,6,opt,name=method,proto3,enum=payment.PaymentMethod" json:"method,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=payment.PaymentStatus" json:"status,omitempty"`
	MojaloopTxnId string                 `protobuf:"bytes,8,opt,name=mojaloop_txn_id,json=mojaloopTxnId,proto3" json:"mojaloop_txn_id,omitempty"`
	FailureReason string                 `protobuf:"bytes,9,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	InitiatedAt   *timestamp.Timestamp   `protobuf:"bytes,10,opt,name=initiated_at,json=initiatedAt,proto3" json:"initiated_at,omitempty"`
	ConfirmedAt   *timestamp.Timestamp   `protobuf:"bytes,11,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_payment_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Payment) GetDeclarationId() int64 {
	if x != nil {
		return x.DeclarationId
	}
	return 0
}

func (x *Payment) GetTraderId() int64 {
	if x != nil {
		return x.TraderId
	}
	return 0
}

func (x *Payment) GetPaymentRef() string {
	if x != nil {
		return x.PaymentRef
	}
	return ""
}

func (x *Payment) GetAmount() *common.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Payment) GetMethod() PaymentMethod {
	if x != nil {
		return x.Method
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *Payment) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *Payment) GetMojaloopTxnId() string {
	if x != nil {
		return x.MojaloopTxnId
	}
	return ""
}

func (x *Payment) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *Payment) GetInitiatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.InitiatedAt
	}
	return nil
}

func (x *Payment) GetConfirmedAt() *timestamp.Timestamp {
	if x != nil {
		return x.ConfirmedAt
	}
	return nil
}

type InitiatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeclarationId int64                  `protobuf:"varint,1,opt,name=declaration_id,json=declarationId,proto3" json:"declaration_id,omitempty"`
	TraderId      int64                  `protobuf:"varint,2,opt,name=trader_id,json=traderId,proto3" json:"trader_id,omitempty"`
	Amount        *common.Money          `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Method        PaymentMethod          `protobuf:"varint,4,opt,name=method,proto3,enum=payment.PaymentMethod" json:"method,omitempty"`
	ReturnUrl     string                 `protobuf:"bytes,5,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiatePaymentRequest) Reset() {
	*x = InitiatePaymentRequest{}
	mi := &file_payment_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiatePaymentRequest) ProtoMessage() {}

func (x *InitiatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiatePaymentRequest.ProtoReflect.Descriptor instead.
func (*InitiatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{1}
}

func (x *InitiatePaymentRequest) GetDeclarationId() int64 {
	if x != nil {
		return x.DeclarationId
	}
	return 0
}

func (x *InitiatePaymentRequest) GetTraderId() int64 {
	if x != nil {
		return x.TraderId
	}
	return 0
}

func (x *InitiatePaymentRequest) GetAmount() *common.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *InitiatePaymentRequest) GetMethod() PaymentMethod {
	if x != nil {
		return x.Method
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *InitiatePaymentRequest) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

type InitiatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	RedirectUrl   string                 `protobuf:"bytes,2,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"` // Mojaloop payment URL
	QrCodeData    string                 `protobuf:"bytes,3,opt,name=qr_code_data,json=qrCodeData,proto3" json:"qr_code_data,omitempty"`  // for mobile money
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiatePaymentResponse) Reset() {
	*x = InitiatePaymentResponse{}
	mi := &file_payment_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiatePaymentResponse) ProtoMessage() {}

func (x *InitiatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiatePaymentResponse.ProtoReflect.Descriptor instead.
func (*InitiatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{2}
}

func (x *InitiatePaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *InitiatePaymentResponse) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

func (x *InitiatePaymentResponse) GetQrCodeData() string {
	if x != nil {
		return x.QrCodeData
	}
	return ""
}

type ConfirmPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentRef    string                 `protobuf:"bytes,1,opt,name=payment_ref,json=paymentRef,proto3" json:"payment_ref,omitempty"`
	MojaloopTxnId string                 `protobuf:"bytes,2,opt,name=mojaloop_txn_id,json=mojaloopTxnId,proto3" json:"mojaloop_txn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPaymentRequest) Reset() {
	*x = ConfirmPaymentRequest{}
	mi := &file_payment_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentRequest) ProtoMessage() {}

func (x *ConfirmPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentRequest.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmPaymentRequest) GetPaymentRef() string {
	if x != nil {
		return x.PaymentRef
	}
	return ""
}

func (x *ConfirmPaymentRequest) GetMojaloopTxnId() string {
	if x != nil {
		return x.MojaloopTxnId
	}
	return ""
}

type GetPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeclarationId int64                  `protobuf:"varint,1,opt,name=declaration_id,json=declarationId,proto3" json:"declaration_id,omitempty"`
	TraderId      int64                  `protobuf:"varint,2,opt,name=trader_id,json=traderId,proto3" json:"trader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentsRequest) Reset() {
	*x = GetPaymentsRequest{}
	mi := &file_payment_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentsRequest) ProtoMessage() {}

func (x *GetPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentsRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{4}
}

func (x *GetPaymentsRequest) GetDeclarationId() int64 {
	if x != nil {
		return x.DeclarationId
	}
	return 0
}

func (x *GetPaymentsRequest) GetTraderId() int64 {
	if x != nil {
		return x.TraderId
	}
	return 0
}

type GetPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentsResponse) Reset() {
	*x = GetPaymentsResponse{}
	mi := &file_payment_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentsResponse) ProtoMessage() {}

func (x *GetPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentsResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{5}
}

func (x *GetPaymentsResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

type PaymentSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalTransactions int64                  `protobuf:"varint,1,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	TotalCollected    *common.Money          `protobuf:"bytes,2,opt,name=total_collected,json=totalCollected,proto3" json:"total_collected,omitempty"`
	PendingAmount     *common.Money          `protobuf:"bytes,3,opt,name=pending_amount,json=pendingAmount,proto3" json:"pending_amount,omitempty"`
	FailedCount       int64                  `protobuf:"varint,4,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PaymentSummary) Reset() {
	*x = PaymentSummary{}
	mi := &file_payment_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentSummary) ProtoMessage() {}

func (x *PaymentSummary) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentSummary.ProtoReflect.Descriptor instead.
func (*PaymentSummary) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{6}
}

func (x *PaymentSummary) GetTotalTransactions() int64 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *PaymentSummary) GetTotalCollected() *common.Money {
	if x != nil {
		return x.TotalCollected
	}
	return nil
}

func (x *PaymentSummary) GetPendingAmount() *common.Money {
	if x != nil {
		return x.PendingAmount
	}
	return nil
}

func (x *PaymentSummary) GetFailedCount() int64 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

var File_payment_payment_proto protoreflect.FileDescriptor

const file_payment_payment_proto_rawDesc = "" +
	"\n" +
	"\x15payment/payment.proto\x12\apayment\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\xd2\x03\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\x0edeclaration_id\x18\x02 \x01(\x03R\rdeclarationId\x12\x1b\n" +
	"\ttrader_id\x18\x03 \x01(\x03R\btraderId\x12\x1f\n" +
	"\vpayment_ref\x18\x04 \x01(\tR\n" +
	"paymentRef\x12%\n" +
	"\x06amount\x18\x05 \x01(\v2\r.common.MoneyR\x06amount\x12.\n" +
	"\x06method\x18\x06 \x01(\x0e2\x16.payment.PaymentMethodR\x06method\x12.\n" +
	"\x06status\x18\a \x01(\x0e2\x16.payment.PaymentStatusR\x06status\x12&\n" +
	"\x0fmojaloop_txn_id\x18\b \x01(\tR\rmojaloopTxnId\x12%\n" +
	"\x0efailure_reason\x18\t \x01(\tR\rfailureReason\x12=\n" +
	"\finitiated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vinitiatedAt\x12=\n" +
	"\fconfirmed_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vconfirmedAt\"\xd2\x01\n" +
	"\x16InitiatePaymentRequest\x12%\n" +
	"\x0edeclaration_id\x18\x01 \x01(\x03R\rdeclarationId\x12\x1b\n" +
	"\ttrader_id\x18\x02 \x01(\x03R\btraderId\x12%\n" +
	"\x06amount\x18\x03 \x01(\v2\r.common.MoneyR\x06amount\x12.\n" +
	"\x06method\x18\x04 \x01(\x0e2\x16.payment.PaymentMethodR\x06method\x12\x1d\n" +
	"\n" +
	"return_url\x18\x05 \x01(\tR\treturnUrl\"\x8a\x01\n" +
	"\x17InitiatePaymentResponse\x12*\n" +
	"\apayment\x18\x01 \x01(\v2\x10.payment.PaymentR\apayment\x12!\n" +
	"\fredirect_url\x18\x02 \x01(\tR\vredirectUrl\x12 \n" +
	"\fqr_code_data\x18\x03 \x01(\tR\n" +
	"qrCodeData\"`\n" +
	"\x15ConfirmPaymentRequest\x12\x1f\n" +
	"\vpayment_ref\x18\x01 \x01(\tR\n" +
	"paymentRef\x12&\n" +
	"\x0fmojaloop_txn_id\x18\x02 \x01(\tR\rmojaloopTxnId\"X\n" +
	"\x12GetPaymentsRequest\x12%\n" +
	"\x0edeclaration_id\x18\x01 \x01(\x03R\rdeclarationId\x12\x1b\n" +
	"\ttrader_id\x18\x02 \x01(\x03R\btraderId\"C\n" +
	"\x13GetPaymentsResponse\x12,\n" +
	"\bpayments\x18\x01 \x03(\v2\x10.payment.PaymentR\bpayments\"\xd0\x01\n" +
	"\x0ePaymentSummary\x12-\n" +
	"\x12total_transactions\x18\x01 \x01(\x03R\x11totalTransactions\x126\n" +
	"\x0ftotal_collected\x18\x02 \x01(\v2\r.common.MoneyR\x0etotalCollected\x124\n" +
	"\x0epending_amount\x18\x03 \x01(\v2\r.common.MoneyR\rpendingAmount\x12!\n" +
	"\ffailed_count\x18\x04 \x01(\x03R\vfailedCount*u\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x02\x12\r\n" +
	"\tCONFIRMED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\f\n" +
	"\bREFUNDED\x10\x05*\x8f\x01\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rMOJALOOP_BANK\x10\x01\x12\x13\n" +
	"\x0fMOJALOOP_MOBILE\x10\x02\x12\x11\n" +
	"\rBANK_TRANSFER\x10\x03\x12\x10\n" +
	"\fCUSTOMS_BOND\x10\x04\x12\x11\n" +
	"\rDUTY_DRAWBACK\x10\x052\xe7\x02\n" +
	"\x0ePaymentService\x12T\n" +
	"\x0fInitiatePayment\x12\x1f.payment.InitiatePaymentRequest\x1a .payment.InitiatePaymentResponse\x12B\n" +
	"\x0eConfirmPayment\x12\x1e.payment.ConfirmPaymentRequest\x1a\x10.payment.Payment\x12H\n" +
	"\vGetPayments\x12\x1b.payment.GetPaymentsRequest\x1a\x1c.payment.GetPaymentsResponse\x12:\n" +
	"\n" +
	"GetSummary\x12\x13.common.PageRequest\x1a\x17.payment.PaymentSummary\x125\n" +
	"\x06Health\x12\x13.common.PageRequest\x1a\x16.common.HealthResponseB\x1cZ\x1atradegateway/proto/paymentb\x06proto3"

var (
	file_payment_payment_proto_rawDescOnce sync.Once
	file_payment_payment_proto_rawDescData []byte
)

func file_payment_payment_proto_rawDescGZIP() []byte {
	file_payment_payment_proto_rawDescOnce.Do(func() {
		file_payment_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_payment_proto_rawDesc), len(file_payment_payment_proto_rawDesc)))
	})
	return file_payment_payment_proto_rawDescData
}

var file_payment_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_payment_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_payment_payment_proto_goTypes = []any{
	(PaymentStatus)(0),              // 0: payment.PaymentStatus
	(PaymentMethod)(0),              // 1: payment.PaymentMethod
	(*Payment)(nil),                 // 2: payment.Payment
	(*InitiatePaymentRequest)(nil),  // 3: payment.InitiatePaymentRequest
	(*InitiatePaymentResponse)(nil), // 4: payment.InitiatePaymentResponse
	(*ConfirmPaymentRequest)(nil),   // 5: payment.ConfirmPaymentRequest
	(*GetPaymentsRequest)(nil),      // 6: payment.GetPaymentsRequest
	(*GetPaymentsResponse)(nil),     // 7: payment.GetPaymentsResponse
	(*PaymentSummary)(nil),          // 8: payment.PaymentSummary
	(*common.Money)(nil),            // 9: common.Money
	(*timestamp.Timestamp)(nil),     // 10: google.protobuf.Timestamp
	(*common.PageRequest)(nil),      // 11: common.PageRequest
	(*common.HealthResponse)(nil),   // 12: common.HealthResponse
}
var file_payment_payment_proto_depIdxs = []int32{
	9,  // 0: payment.Payment.amount:type_name -> common.Money
	1,  // 1: payment.Payment.method:type_name -> payment.PaymentMethod
	0,  // 2: payment.Payment.status:type_name -> payment.PaymentStatus
	10, // 3: payment.Payment.initiated_at:type_name -> google.protobuf.Timestamp
	10, // 4: payment.Payment.confirmed_at:type_name -> google.protobuf.Timestamp
	9,  // 5: payment.InitiatePaymentRequest.amount:type_name -> common.Money
	1,  // 6: payment.InitiatePaymentRequest.method:type_name -> payment.PaymentMethod
	2,  // 7: payment.InitiatePaymentResponse.payment:type_name -> payment.Payment
	2,  // 8: payment.GetPaymentsResponse.payments:type_name -> payment.Payment
	9,  // 9: payment.PaymentSummary.total_collected:type_name -> common.Money
	9,  // 10: payment.PaymentSummary.pending_amount:type_name -> common.Money
	3,  // 11: payment.PaymentService.InitiatePayment:input_type -> payment.InitiatePaymentRequest
	5,  // 12: payment.PaymentService.ConfirmPayment:input_type -> payment.ConfirmPaymentRequest
	6,  // 13: payment.PaymentService.GetPayments:input_type -> payment.GetPaymentsRequest
	11, // 14: payment.PaymentService.GetSummary:input_type -> common.PageRequest
	11, // 15: payment.PaymentService.Health:input_type -> common.PageRequest
	4,  // 16: payment.PaymentService.InitiatePayment:output_type -> payment.InitiatePaymentResponse
	2,  // 17: payment.PaymentService.ConfirmPayment:output_type -> payment.Payment
	7,  // 18: payment.PaymentService.GetPayments:output_type -> payment.GetPaymentsResponse
	8,  // 19: payment.PaymentService.GetSummary:output_type -> payment.PaymentSummary
	12, // 20: payment.PaymentService.Health:output_type -> common.HealthResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_payment_payment_proto_init() }
func file_payment_payment_proto_init() {
	if File_payment_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_payment_proto_rawDesc), len(file_payment_payment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_payment_proto_goTypes,
		DependencyIndexes: file_payment_payment_proto_depIdxs,
		EnumInfos:         file_payment_payment_proto_enumTypes,
		MessageInfos:      file_payment_payment_proto_msgTypes,
	}.Build()
	File_payment_payment_proto = out.File
	file_payment_payment_proto_goTypes = nil
	file_payment_payment_proto_depIdxs = nil
}
