// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: workflow/workflow.proto

package workflow

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	common "tradegateway/proto/common"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkflowType int32

const (
	WorkflowType_WORKFLOW_TYPE_UNSPECIFIED WorkflowType = 0
	WorkflowType_DECLARATION_LIFECYCLE     WorkflowType = 1
	WorkflowType_OGA_JOINT_INSPECTION      WorkflowType = 2
	WorkflowType_PAYMENT_SETTLEMENT        WorkflowType = 3
	WorkflowType_AEO_CERTIFICATION         WorkflowType = 4
	WorkflowType_POST_CLEARANCE_AUDIT      WorkflowType = 5
	WorkflowType_SANCTIONS_ESCALATION      WorkflowType = 6
)

// Enum value maps for WorkflowType.
var (
	WorkflowType_name = map[int32]string{
		0: "WORKFLOW_TYPE_UNSPECIFIED",
		1: "DECLARATION_LIFECYCLE",
		2: "OGA_JOINT_INSPECTION",
		3: "PAYMENT_SETTLEMENT",
		4: "AEO_CERTIFICATION",
		5: "POST_CLEARANCE_AUDIT",
		6: "SANCTIONS_ESCALATION",
	}
	WorkflowType_value = map[string]int32{
		"WORKFLOW_TYPE_UNSPECIFIED": 0,
		"DECLARATION_LIFECYCLE":     1,
		"OGA_JOINT_INSPECTION":      2,
		"PAYMENT_SETTLEMENT":        3,
		"AEO_CERTIFICATION":         4,
		"POST_CLEARANCE_AUDIT":      5,
		"SANCTIONS_ESCALATION":      6,
	}
)

func (x WorkflowType) Enum() *WorkflowType {
	p := new(WorkflowType)
	*p = x
	return p
}

func (x WorkflowType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowType) Descriptor() protoreflect.EnumDescriptor {
	return file_workflow_workflow_proto_enumTypes[0].Descriptor()
}

func (WorkflowType) Type() protoreflect.EnumType {
	return &file_workflow_workflow_proto_enumTypes[0]
}

func (x WorkflowType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowType.Descriptor instead.
func (WorkflowType) EnumDescriptor() ([]byte, []int) {
	return file_workflow_workflow_proto_rawDescGZIP(), []int{0}
}

type WorkflowStatus int32

const (
	WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED WorkflowStatus = 0
	WorkflowStatus_RUNNING                     WorkflowStatus = 1
	WorkflowStatus_COMPLETED                   WorkflowStatus = 2
	WorkflowStatus_FAILED                      WorkflowStatus = 3
	WorkflowStatus_CANCELLED                   WorkflowStatus = 4
	WorkflowStatus_TIMED_OUT                   WorkflowStatus = 5
	WorkflowStatus_TERMINATED                  WorkflowStatus = 6
)

// Enum value maps for WorkflowStatus.
var (
	WorkflowStatus_name = map[int32]string{
		0: "WORKFLOW_STATUS_UNSPECIFIED",
		1: "RUNNING",
		2: "COMPLETED",
		3: "FAILED",
		4: "CANCELLED",
		5: "TIMED_OUT",
		6: "TERMINATED",
	}
	WorkflowStatus_value = map[string]int32{
		"WORKFLOW_STATUS_UNSPECIFIED": 0,
		"RUNNING":                     1,
		"COMPLETED":                   2,
		"FAILED":                      3,
		"CANCELLED":                   4,
		"TIMED_OUT":                   5,
		"TERMINATED":                  6,
	}
)

func (x WorkflowStatus) Enum() *WorkflowStatus {
	p := new(WorkflowStatus)
	*p = x
	return p
}

func (x WorkflowStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_workflow_workflow_proto_enumTypes[1].Descriptor()
}

func (WorkflowStatus) Type() protoreflect.EnumType {
	return &file_workflow_workflow_proto_enumTypes[1]
}

func (x WorkflowStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowStatus.Descriptor instead.
func (WorkflowStatus) EnumDescriptor() ([]byte, []int) {
	return file_workflow_workflow_proto_rawDescGZIP(), []int{1}
}

type WorkflowInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Type          WorkflowType           `protobuf:"varint,3,opt,name=type,proto3,enum=workflow.WorkflowType" json:"type,omitempty"`
	Status        WorkflowStatus         `protobuf:"varint,4,opt,name=status,proto3,enum=workflow.WorkflowStatus" json:"status,omitempty"`
	EntityId      int64                  `protobuf:"varint,5,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // declaration_id, aeo_id, etc.
	CurrentState  string                 `protobuf:"bytes,6,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StartedAt     *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamp.Timestamp   `protobuf:"bytes,9,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowInstance) Reset() {
	*x = WorkflowInstance{}
	mi := &file_workflow_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowInstance) ProtoMessage() {}

func (x *WorkflowInstance) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowInstance.ProtoReflect.Descriptor instead.
func (*WorkflowInstance) Descriptor() ([]byte, []int) {
	return file_workflow_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowInstance) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowInstance) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *WorkflowInstance) GetType() WorkflowType {
	if x != nil {
		return x.Type
	}
	return WorkflowType_WORKFLOW_TYPE_UNSPECIFIED
}

func (x *WorkflowInstance) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *WorkflowInstance) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *WorkflowInstance) GetCurrentState() string {
	if x != nil {
		return x.CurrentState
	}
	return ""
}

func (x *WorkflowInstance) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *WorkflowInstance) GetStartedAt() *timestamp.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *WorkflowInstance) GetCompletedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type StartWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          WorkflowType           `protobuf:"varint,1,opt,name=type,proto3,enum=workflow.WorkflowType" json:"type,omitempty"`
	EntityId      int64                  `protobuf:"varint,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	InputJson     string                 `protobuf:"bytes,3,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"` // JSON payload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkflowRequest) Reset() {
	*x = StartWorkflowRequest{}
	mi := &file_workflow_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkflowRequest) ProtoMessage() {}

func (x *StartWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkflowRequest.ProtoReflect.Descriptor instead.
func (*StartWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflow_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *StartWorkflowRequest) GetType() WorkflowType {
	if x != nil {
		return x.Type
	}
	return WorkflowType_WORKFLOW_TYPE_UNSPECIFIED
}

func (x *StartWorkflowRequest) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *StartWorkflowRequest) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

type StartWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkflowResponse) Reset() {
	*x = StartWorkflowResponse{}
	mi := &file_workflow_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkflowResponse) ProtoMessage() {}

func (x *StartWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkflowResponse.ProtoReflect.Descriptor instead.
func (*StartWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_workflow_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *StartWorkflowResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *StartWorkflowResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type GetWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowRequest) Reset() {
	*x = GetWorkflowRequest{}
	mi := &file_workflow_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowRequest) ProtoMessage() {}

func (x *GetWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflow_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *GetWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type SignalWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	SignalName    string                 `protobuf:"bytes,2,opt,name=signal_name,json=signalName,proto3" json:"signal_name,omitempty"` // e.g. "payment_confirmed", "oga_approved"
	SignalData    string                 `protobuf:"bytes,3,opt,name=signal_data,json=signalData,proto3" json:"signal_data,omitempty"` // JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalWorkflowRequest) Reset() {
	*x = SignalWorkflowRequest{}
	mi := &file_workflow_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalWorkflowRequest) ProtoMessage() {}

func (x *SignalWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalWorkflowRequest.ProtoReflect.Descriptor instead.
func (*SignalWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflow_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *SignalWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *SignalWorkflowRequest) GetSignalName() string {
	if x != nil {
		return x.SignalName
	}
	return ""
}

func (x *SignalWorkflowRequest) GetSignalData() string {
	if x != nil {
		return x.SignalData
	}
	return ""
}

type ListWorkflowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          WorkflowType           `protobuf:"varint,1,opt,name=type,proto3,enum=workflow.WorkflowType" json:"type,omitempty"`
	Status        WorkflowStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=workflow.WorkflowStatus" json:"status,omitempty"`
	EntityId      int64                  `protobuf:"varint,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Page          *common.PageRequest    `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsRequest) Reset() {
	*x = ListWorkflowsRequest{}
	mi := &file_workflow_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsRequest) ProtoMessage() {}

func (x *ListWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_workflow_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *ListWorkflowsRequest) GetType() WorkflowType {
	if x != nil {
		return x.Type
	}
	return WorkflowType_WORKFLOW_TYPE_UNSPECIFIED
}

func (x *ListWorkflowsRequest) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *ListWorkflowsRequest) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *ListWorkflowsRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListWorkflowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflows     []*WorkflowInstance    `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	Meta          *common.PageMeta       `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsResponse) Reset() {
	*x = ListWorkflowsResponse{}
	mi := &file_workflow_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsResponse) ProtoMessage() {}

func (x *ListWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_workflow_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *ListWorkflowsResponse) GetWorkflows() []*WorkflowInstance {
	if x != nil {
		return x.Workflows
	}
	return nil
}

func (x *ListWorkflowsResponse) GetMeta() *common.PageMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_workflow_workflow_proto protoreflect.FileDescriptor

const file_workflow_workflow_proto_rawDesc = "" +
	"\n" +
	"\x17workflow/workflow.proto\x12\bworkflow\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\x89\x03\n" +
	"\x10WorkflowInstance\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12*\n" +
	"\x04type\x18\x03 \x01(\x0e2\x16.workflow.WorkflowTypeR\x04type\x120\n" +
	"\x06status\x18\x04 \x01(\x0e2\x18.workflow.WorkflowStatusR\x06status\x12\x1b\n" +
	"\tentity_id\x18\x05 \x01(\x03R\bentityId\x12#\n" +
	"\rcurrent_state\x18\x06 \x01(\tR\fcurrentState\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"~\n" +
	"\x14StartWorkflowRequest\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.workflow.WorkflowTypeR\x04type\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\x03R\bentityId\x12\x1d\n" +
	"\n" +
	"input_json\x18\x03 \x01(\tR\tinputJson\"O\n" +
	"\x15StartWorkflowResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\"5\n" +
	"\x12GetWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"z\n" +
	"\x15SignalWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x1f\n" +
	"\vsignal_name\x18\x02 \x01(\tR\n" +
	"signalName\x12\x1f\n" +
	"\vsignal_data\x18\x03 \x01(\tR\n" +
	"signalData\"\xba\x01\n" +
	"\x14ListWorkflowsRequest\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.workflow.WorkflowTypeR\x04type\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.workflow.WorkflowStatusR\x06status\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\x03R\bentityId\x12'\n" +
	"\x04page\x18\x04 \x01(\v2\x13.common.PageRequestR\x04page\"w\n" +
	"\x15ListWorkflowsResponse\x128\n" +
	"\tworkflows\x18\x01 \x03(\v2\x1a.workflow.WorkflowInstanceR\tworkflows\x12$\n" +
	"\x04meta\x18\x02 \x01(\v2\x10.common.PageMetaR\x04meta*\xc5\x01\n" +
	"\fWorkflowType\x12\x1d\n" +
	"\x19WORKFLOW_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DECLARATION_LIFECYCLE\x10\x01\x12\x18\n" +
	"\x14OGA_JOINT_INSPECTION\x10\x02\x12\x16\n" +
	"\x12PAYMENT_SETTLEMENT\x10\x03\x12\x15\n" +
	"\x11AEO_CERTIFICATION\x10\x04\x12\x18\n" +
	"\x14POST_CLEARANCE_AUDIT\x10\x05\x12\x18\n" +
	"\x14SANCTIONS_ESCALATION\x10\x06*\x87\x01\n" +
	"\x0eWorkflowStatus\x12\x1f\n" +
	"\x1bWORKFLOW_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\r\n" +
	"\tCOMPLETED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\x12\r\n" +
	"\tCANCELLED\x10\x04\x12\r\n" +
	"\tTIMED_OUT\x10\x05\x12\x0e\n" +
	"\n" +
	"TERMINATED\x10\x062\xc8\x03\n" +
	"\x0fWorkflowService\x12P\n" +
	"\rStartWorkflow\x12\x1e.workflow.StartWorkflowRequest\x1a\x1f.workflow.StartWorkflowResponse\x12G\n" +
	"\vGetWorkflow\x12\x1c.workflow.GetWorkflowRequest\x1a\x1a.workflow.WorkflowInstance\x12I\n" +
	"\x0eSignalWorkflow\x12\x1f.workflow.SignalWorkflowRequest\x1a\x16.common.StatusResponse\x12F\n" +
	"\x0eCancelWorkflow\x12\x1c.workflow.GetWorkflowRequest\x1a\x16.common.StatusResponse\x12P\n" +
	"\rListWorkflows\x12\x1e.workflow.ListWorkflowsRequest\x1a\x1f.workflow.ListWorkflowsResponse\x125\n" +
	"\x06Health\x12\x13.common.PageRequest\x1a\x16.common.HealthResponseB\x1dZ\x1btradegateway/proto/workflowb\x06proto3"

var (
	file_workflow_workflow_proto_rawDescOnce sync.Once
	file_workflow_workflow_proto_rawDescData []byte
)

func file_workflow_workflow_proto_rawDescGZIP() []byte {
	file_workflow_workflow_proto_rawDescOnce.Do(func() {
		file_workflow_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_workflow_proto_rawDesc), len(file_workflow_workflow_proto_rawDesc)))
	})
	return file_workflow_workflow_proto_rawDescData
}

var file_workflow_workflow_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_workflow_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_workflow_workflow_proto_goTypes = []any{
	(WorkflowType)(0),             // 0: workflow.WorkflowType
	(WorkflowStatus)(0),           // 1: workflow.WorkflowStatus
	(*WorkflowInstance)(nil),      // 2: workflow.WorkflowInstance
	(*StartWorkflowRequest)(nil),  // 3: workflow.StartWorkflowRequest
	(*StartWorkflowResponse)(nil), // 4: workflow.StartWorkflowResponse
	(*GetWorkflowRequest)(nil),    // 5: workflow.GetWorkflowRequest
	(*SignalWorkflowRequest)(nil), // 6: workflow.SignalWorkflowRequest
	(*ListWorkflowsRequest)(nil),  // 7: workflow.ListWorkflowsRequest
	(*ListWorkflowsResponse)(nil), // 8: workflow.ListWorkflowsResponse
	(*timestamp.Timestamp)(nil),   // 9: google.protobuf.Timestamp
	(*common.PageRequest)(nil),    // 10: common.PageRequest
	(*common.PageMeta)(nil),       // 11: common.PageMeta
	(*common.StatusResponse)(nil), // 12: common.StatusResponse
	(*common.HealthResponse)(nil), // 13: common.HealthResponse
}
var file_workflow_workflow_proto_depIdxs = []int32{
	0,  // 0: workflow.WorkflowInstance.type:type_name -> workflow.WorkflowType
	1,  // 1: workflow.WorkflowInstance.status:type_name -> workflow.WorkflowStatus
	9,  // 2: workflow.WorkflowInstance.started_at:type_name -> google.protobuf.Timestamp
	9,  // 3: workflow.WorkflowInstance.completed_at:type_name -> google.protobuf.Timestamp
	0,  // 4: workflow.StartWorkflowRequest.type:type_name -> workflow.WorkflowType
	0,  // 5: workflow.ListWorkflowsRequest.type:type_name -> workflow.WorkflowType
	1,  // 6: workflow.ListWorkflowsRequest.status:type_name -> workflow.WorkflowStatus
	10, // 7: workflow.ListWorkflowsRequest.page:type_name -> common.PageRequest
	2,  // 8: workflow.ListWorkflowsResponse.workflows:type_name -> workflow.WorkflowInstance
	11, // 9: workflow.ListWorkflowsResponse.meta:type_name -> common.PageMeta
	3,  // 10: workflow.WorkflowService.StartWorkflow:input_type -> workflow.StartWorkflowRequest
	5,  // 11: workflow.WorkflowService.GetWorkflow:input_type -> workflow.GetWorkflowRequest
	6,  // 12: workflow.WorkflowService.SignalWorkflow:input_type -> workflow.SignalWorkflowRequest
	5,  // 13: workflow.WorkflowService.CancelWorkflow:input_type -> workflow.GetWorkflowRequest
	7,  // 14: workflow.WorkflowService.ListWorkflows:input_type -> workflow.ListWorkflowsRequest
	10, // 15: workflow.WorkflowService.Health:input_type -> common.PageRequest
	4,  // 16: workflow.WorkflowService.StartWorkflow:output_type -> workflow.StartWorkflowResponse
	2,  // 17: workflow.WorkflowService.GetWorkflow:output_type -> workflow.WorkflowInstance
	12, // 18: workflow.WorkflowService.SignalWorkflow:output_type -> common.StatusResponse
	12, // 19: workflow.WorkflowService.CancelWorkflow:output_type -> common.StatusResponse
	8,  // 20: workflow.WorkflowService.ListWorkflows:output_type -> workflow.ListWorkflowsResponse
	13, // 21: workflow.WorkflowService.Health:output_type -> common.HealthResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_workflow_workflow_proto_init() }
func file_workflow_workflow_proto_init() {
	if File_workflow_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_workflow_proto_rawDesc), len(file_workflow_workflow_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workflow_workflow_proto_goTypes,
		DependencyIndexes: file_workflow_workflow_proto_depIdxs,
		EnumInfos:         file_workflow_workflow_proto_enumTypes,
		MessageInfos:      file_workflow_workflow_proto_msgTypes,
	}.Build()
	File_workflow_workflow_proto = out.File
	file_workflow_workflow_proto_goTypes = nil
	file_workflow_workflow_proto_depIdxs = nil
}
