// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.6
// source: oga.proto

package ogav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OGAService_SubmitPermitRequest_FullMethodName      = "/tradegateway.oga.v1.OGAService/SubmitPermitRequest"
	OGAService_GetPermitStatus_FullMethodName          = "/tradegateway.oga.v1.OGAService/GetPermitStatus"
	OGAService_ApprovePermit_FullMethodName            = "/tradegateway.oga.v1.OGAService/ApprovePermit"
	OGAService_RejectPermit_FullMethodName             = "/tradegateway.oga.v1.OGAService/RejectPermit"
	OGAService_ListAgencies_FullMethodName             = "/tradegateway.oga.v1.OGAService/ListAgencies"
	OGAService_GetJointInspectionStatus_FullMethodName = "/tradegateway.oga.v1.OGAService/GetJointInspectionStatus"
	OGAService_TriggerJointInspection_FullMethodName   = "/tradegateway.oga.v1.OGAService/TriggerJointInspection"
	OGAService_GetSLAReport_FullMethodName             = "/tradegateway.oga.v1.OGAService/GetSLAReport"
)

// OGAServiceClient is the client API for OGAService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OGAServiceClient interface {
	SubmitPermitRequest(ctx context.Context, in *PermitRequest, opts ...grpc.CallOption) (*PermitResponse, error)
	GetPermitStatus(ctx context.Context, in *GetPermitStatusRequest, opts ...grpc.CallOption) (*PermitResponse, error)
	ApprovePermit(ctx context.Context, in *ApprovePermitRequest, opts ...grpc.CallOption) (*PermitResponse, error)
	RejectPermit(ctx context.Context, in *RejectPermitRequest, opts ...grpc.CallOption) (*PermitResponse, error)
	ListAgencies(ctx context.Context, in *ListAgenciesRequest, opts ...grpc.CallOption) (*ListAgenciesResponse, error)
	GetJointInspectionStatus(ctx context.Context, in *JointInspectionRequest, opts ...grpc.CallOption) (*JointInspectionResponse, error)
	TriggerJointInspection(ctx context.Context, in *TriggerJointInspectionRequest, opts ...grpc.CallOption) (*JointInspectionResponse, error)
	GetSLAReport(ctx context.Context, in *SLAReportRequest, opts ...grpc.CallOption) (*SLAReportResponse, error)
}

type oGAServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOGAServiceClient(cc grpc.ClientConnInterface) OGAServiceClient {
	return &oGAServiceClient{cc}
}

func (c *oGAServiceClient) SubmitPermitRequest(ctx context.Context, in *PermitRequest, opts ...grpc.CallOption) (*PermitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PermitResponse)
	err := c.cc.Invoke(ctx, OGAService_SubmitPermitRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oGAServiceClient) GetPermitStatus(ctx context.Context, in *GetPermitStatusRequest, opts ...grpc.CallOption) (*PermitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PermitResponse)
	err := c.cc.Invoke(ctx, OGAService_GetPermitStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oGAServiceClient) ApprovePermit(ctx context.Context, in *ApprovePermitRequest, opts ...grpc.CallOption) (*PermitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PermitResponse)
	err := c.cc.Invoke(ctx, OGAService_ApprovePermit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oGAServiceClient) RejectPermit(ctx context.Context, in *RejectPermitRequest, opts ...grpc.CallOption) (*PermitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PermitResponse)
	err := c.cc.Invoke(ctx, OGAService_RejectPermit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oGAServiceClient) ListAgencies(ctx context.Context, in *ListAgenciesRequest, opts ...grpc.CallOption) (*ListAgenciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgenciesResponse)
	err := c.cc.Invoke(ctx, OGAService_ListAgencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oGAServiceClient) GetJointInspectionStatus(ctx context.Context, in *JointInspectionRequest, opts ...grpc.CallOption) (*JointInspectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JointInspectionResponse)
	err := c.cc.Invoke(ctx, OGAService_GetJointInspectionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oGAServiceClient) TriggerJointInspection(ctx context.Context, in *TriggerJointInspectionRequest, opts ...grpc.CallOption) (*JointInspectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JointInspectionResponse)
	err := c.cc.Invoke(ctx, OGAService_TriggerJointInspection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oGAServiceClient) GetSLAReport(ctx context.Context, in *SLAReportRequest, opts ...grpc.CallOption) (*SLAReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SLAReportResponse)
	err := c.cc.Invoke(ctx, OGAService_GetSLAReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OGAServiceServer is the server API for OGAService service.
// All implementations must embed UnimplementedOGAServiceServer
// for forward compatibility.
type OGAServiceServer interface {
	SubmitPermitRequest(context.Context, *PermitRequest) (*PermitResponse, error)
	GetPermitStatus(context.Context, *GetPermitStatusRequest) (*PermitResponse, error)
	ApprovePermit(context.Context, *ApprovePermitRequest) (*PermitResponse, error)
	RejectPermit(context.Context, *RejectPermitRequest) (*PermitResponse, error)
	ListAgencies(context.Context, *ListAgenciesRequest) (*ListAgenciesResponse, error)
	GetJointInspectionStatus(context.Context, *JointInspectionRequest) (*JointInspectionResponse, error)
	TriggerJointInspection(context.Context, *TriggerJointInspectionRequest) (*JointInspectionResponse, error)
	GetSLAReport(context.Context, *SLAReportRequest) (*SLAReportResponse, error)
	mustEmbedUnimplementedOGAServiceServer()
}

// UnimplementedOGAServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOGAServiceServer struct{}

func (UnimplementedOGAServiceServer) SubmitPermitRequest(context.Context, *PermitRequest) (*PermitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitPermitRequest not implemented")
}
func (UnimplementedOGAServiceServer) GetPermitStatus(context.Context, *GetPermitStatusRequest) (*PermitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPermitStatus not implemented")
}
func (UnimplementedOGAServiceServer) ApprovePermit(context.Context, *ApprovePermitRequest) (*PermitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApprovePermit not implemented")
}
func (UnimplementedOGAServiceServer) RejectPermit(context.Context, *RejectPermitRequest) (*PermitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectPermit not implemented")
}
func (UnimplementedOGAServiceServer) ListAgencies(context.Context, *ListAgenciesRequest) (*ListAgenciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAgencies not implemented")
}
func (UnimplementedOGAServiceServer) GetJointInspectionStatus(context.Context, *JointInspectionRequest) (*JointInspectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJointInspectionStatus not implemented")
}
func (UnimplementedOGAServiceServer) TriggerJointInspection(context.Context, *TriggerJointInspectionRequest) (*JointInspectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerJointInspection not implemented")
}
func (UnimplementedOGAServiceServer) GetSLAReport(context.Context, *SLAReportRequest) (*SLAReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSLAReport not implemented")
}
func (UnimplementedOGAServiceServer) mustEmbedUnimplementedOGAServiceServer() {}
func (UnimplementedOGAServiceServer) testEmbeddedByValue()                    {}

// UnsafeOGAServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OGAServiceServer will
// result in compilation errors.
type UnsafeOGAServiceServer interface {
	mustEmbedUnimplementedOGAServiceServer()
}

func RegisterOGAServiceServer(s grpc.ServiceRegistrar, srv OGAServiceServer) {
	// If the following call pancis, it indicates UnimplementedOGAServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OGAService_ServiceDesc, srv)
}

func _OGAService_SubmitPermitRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OGAServiceServer).SubmitPermitRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OGAService_SubmitPermitRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OGAServiceServer).SubmitPermitRequest(ctx, req.(*PermitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OGAService_GetPermitStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPermitStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OGAServiceServer).GetPermitStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OGAService_GetPermitStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OGAServiceServer).GetPermitStatus(ctx, req.(*GetPermitStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OGAService_ApprovePermit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApprovePermitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OGAServiceServer).ApprovePermit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OGAService_ApprovePermit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OGAServiceServer).ApprovePermit(ctx, req.(*ApprovePermitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OGAService_RejectPermit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectPermitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OGAServiceServer).RejectPermit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OGAService_RejectPermit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OGAServiceServer).RejectPermit(ctx, req.(*RejectPermitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OGAService_ListAgencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgenciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OGAServiceServer).ListAgencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OGAService_ListAgencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OGAServiceServer).ListAgencies(ctx, req.(*ListAgenciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OGAService_GetJointInspectionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JointInspectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OGAServiceServer).GetJointInspectionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OGAService_GetJointInspectionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OGAServiceServer).GetJointInspectionStatus(ctx, req.(*JointInspectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OGAService_TriggerJointInspection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerJointInspectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OGAServiceServer).TriggerJointInspection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OGAService_TriggerJointInspection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OGAServiceServer).TriggerJointInspection(ctx, req.(*TriggerJointInspectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OGAService_GetSLAReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SLAReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OGAServiceServer).GetSLAReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OGAService_GetSLAReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OGAServiceServer).GetSLAReport(ctx, req.(*SLAReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OGAService_ServiceDesc is the grpc.ServiceDesc for OGAService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OGAService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tradegateway.oga.v1.OGAService",
	HandlerType: (*OGAServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitPermitRequest",
			Handler:    _OGAService_SubmitPermitRequest_Handler,
		},
		{
			MethodName: "GetPermitStatus",
			Handler:    _OGAService_GetPermitStatus_Handler,
		},
		{
			MethodName: "ApprovePermit",
			Handler:    _OGAService_ApprovePermit_Handler,
		},
		{
			MethodName: "RejectPermit",
			Handler:    _OGAService_RejectPermit_Handler,
		},
		{
			MethodName: "ListAgencies",
			Handler:    _OGAService_ListAgencies_Handler,
		},
		{
			MethodName: "GetJointInspectionStatus",
			Handler:    _OGAService_GetJointInspectionStatus_Handler,
		},
		{
			MethodName: "TriggerJointInspection",
			Handler:    _OGAService_TriggerJointInspection_Handler,
		},
		{
			MethodName: "GetSLAReport",
			Handler:    _OGAService_GetSLAReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oga.proto",
}
