// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.6
// source: declaration.proto

package declarationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeclarationService_CreateDeclaration_FullMethodName       = "/tradegateway.declaration.v1.DeclarationService/CreateDeclaration"
	DeclarationService_SubmitDeclaration_FullMethodName       = "/tradegateway.declaration.v1.DeclarationService/SubmitDeclaration"
	DeclarationService_GetDeclaration_FullMethodName          = "/tradegateway.declaration.v1.DeclarationService/GetDeclaration"
	DeclarationService_ListDeclarations_FullMethodName        = "/tradegateway.declaration.v1.DeclarationService/ListDeclarations"
	DeclarationService_UpdateDeclarationStatus_FullMethodName = "/tradegateway.declaration.v1.DeclarationService/UpdateDeclarationStatus"
	DeclarationService_AssessDeclaration_FullMethodName       = "/tradegateway.declaration.v1.DeclarationService/AssessDeclaration"
	DeclarationService_ClearDeclaration_FullMethodName        = "/tradegateway.declaration.v1.DeclarationService/ClearDeclaration"
	DeclarationService_GetDeclarationStats_FullMethodName     = "/tradegateway.declaration.v1.DeclarationService/GetDeclarationStats"
)

// DeclarationServiceClient is the client API for DeclarationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeclarationServiceClient interface {
	CreateDeclaration(ctx context.Context, in *CreateDeclarationRequest, opts ...grpc.CallOption) (*DeclarationResponse, error)
	SubmitDeclaration(ctx context.Context, in *SubmitDeclarationRequest, opts ...grpc.CallOption) (*DeclarationResponse, error)
	GetDeclaration(ctx context.Context, in *GetDeclarationRequest, opts ...grpc.CallOption) (*DeclarationResponse, error)
	ListDeclarations(ctx context.Context, in *ListDeclarationsRequest, opts ...grpc.CallOption) (*ListDeclarationsResponse, error)
	UpdateDeclarationStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*DeclarationResponse, error)
	AssessDeclaration(ctx context.Context, in *AssessDeclarationRequest, opts ...grpc.CallOption) (*AssessmentResponse, error)
	ClearDeclaration(ctx context.Context, in *ClearDeclarationRequest, opts ...grpc.CallOption) (*DeclarationResponse, error)
	GetDeclarationStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*DeclarationStatsResponse, error)
}

type declarationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeclarationServiceClient(cc grpc.ClientConnInterface) DeclarationServiceClient {
	return &declarationServiceClient{cc}
}

func (c *declarationServiceClient) CreateDeclaration(ctx context.Context, in *CreateDeclarationRequest, opts ...grpc.CallOption) (*DeclarationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeclarationResponse)
	err := c.cc.Invoke(ctx, DeclarationService_CreateDeclaration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *declarationServiceClient) SubmitDeclaration(ctx context.Context, in *SubmitDeclarationRequest, opts ...grpc.CallOption) (*DeclarationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeclarationResponse)
	err := c.cc.Invoke(ctx, DeclarationService_SubmitDeclaration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *declarationServiceClient) GetDeclaration(ctx context.Context, in *GetDeclarationRequest, opts ...grpc.CallOption) (*DeclarationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeclarationResponse)
	err := c.cc.Invoke(ctx, DeclarationService_GetDeclaration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *declarationServiceClient) ListDeclarations(ctx context.Context, in *ListDeclarationsRequest, opts ...grpc.CallOption) (*ListDeclarationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeclarationsResponse)
	err := c.cc.Invoke(ctx, DeclarationService_ListDeclarations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *declarationServiceClient) UpdateDeclarationStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*DeclarationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeclarationResponse)
	err := c.cc.Invoke(ctx, DeclarationService_UpdateDeclarationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *declarationServiceClient) AssessDeclaration(ctx context.Context, in *AssessDeclarationRequest, opts ...grpc.CallOption) (*AssessmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssessmentResponse)
	err := c.cc.Invoke(ctx, DeclarationService_AssessDeclaration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *declarationServiceClient) ClearDeclaration(ctx context.Context, in *ClearDeclarationRequest, opts ...grpc.CallOption) (*DeclarationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeclarationResponse)
	err := c.cc.Invoke(ctx, DeclarationService_ClearDeclaration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *declarationServiceClient) GetDeclarationStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*DeclarationStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeclarationStatsResponse)
	err := c.cc.Invoke(ctx, DeclarationService_GetDeclarationStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeclarationServiceServer is the server API for DeclarationService service.
// All implementations must embed UnimplementedDeclarationServiceServer
// for forward compatibility.
type DeclarationServiceServer interface {
	CreateDeclaration(context.Context, *CreateDeclarationRequest) (*DeclarationResponse, error)
	SubmitDeclaration(context.Context, *SubmitDeclarationRequest) (*DeclarationResponse, error)
	GetDeclaration(context.Context, *GetDeclarationRequest) (*DeclarationResponse, error)
	ListDeclarations(context.Context, *ListDeclarationsRequest) (*ListDeclarationsResponse, error)
	UpdateDeclarationStatus(context.Context, *UpdateStatusRequest) (*DeclarationResponse, error)
	AssessDeclaration(context.Context, *AssessDeclarationRequest) (*AssessmentResponse, error)
	ClearDeclaration(context.Context, *ClearDeclarationRequest) (*DeclarationResponse, error)
	GetDeclarationStats(context.Context, *GetStatsRequest) (*DeclarationStatsResponse, error)
	mustEmbedUnimplementedDeclarationServiceServer()
}

// UnimplementedDeclarationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeclarationServiceServer struct{}

func (UnimplementedDeclarationServiceServer) CreateDeclaration(context.Context, *CreateDeclarationRequest) (*DeclarationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeclaration not implemented")
}
func (UnimplementedDeclarationServiceServer) SubmitDeclaration(context.Context, *SubmitDeclarationRequest) (*DeclarationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitDeclaration not implemented")
}
func (UnimplementedDeclarationServiceServer) GetDeclaration(context.Context, *GetDeclarationRequest) (*DeclarationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeclaration not implemented")
}
func (UnimplementedDeclarationServiceServer) ListDeclarations(context.Context, *ListDeclarationsRequest) (*ListDeclarationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeclarations not implemented")
}
func (UnimplementedDeclarationServiceServer) UpdateDeclarationStatus(context.Context, *UpdateStatusRequest) (*DeclarationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDeclarationStatus not implemented")
}
func (UnimplementedDeclarationServiceServer) AssessDeclaration(context.Context, *AssessDeclarationRequest) (*AssessmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssessDeclaration not implemented")
}
func (UnimplementedDeclarationServiceServer) ClearDeclaration(context.Context, *ClearDeclarationRequest) (*DeclarationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearDeclaration not implemented")
}
func (UnimplementedDeclarationServiceServer) GetDeclarationStats(context.Context, *GetStatsRequest) (*DeclarationStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeclarationStats not implemented")
}
func (UnimplementedDeclarationServiceServer) mustEmbedUnimplementedDeclarationServiceServer() {}
func (UnimplementedDeclarationServiceServer) testEmbeddedByValue()                            {}

// UnsafeDeclarationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeclarationServiceServer will
// result in compilation errors.
type UnsafeDeclarationServiceServer interface {
	mustEmbedUnimplementedDeclarationServiceServer()
}

func RegisterDeclarationServiceServer(s grpc.ServiceRegistrar, srv DeclarationServiceServer) {
	// If the following call pancis, it indicates UnimplementedDeclarationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeclarationService_ServiceDesc, srv)
}

func _DeclarationService_CreateDeclaration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeclarationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeclarationServiceServer).CreateDeclaration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeclarationService_CreateDeclaration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeclarationServiceServer).CreateDeclaration(ctx, req.(*CreateDeclarationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeclarationService_SubmitDeclaration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitDeclarationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeclarationServiceServer).SubmitDeclaration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeclarationService_SubmitDeclaration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeclarationServiceServer).SubmitDeclaration(ctx, req.(*SubmitDeclarationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeclarationService_GetDeclaration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeclarationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeclarationServiceServer).GetDeclaration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeclarationService_GetDeclaration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeclarationServiceServer).GetDeclaration(ctx, req.(*GetDeclarationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeclarationService_ListDeclarations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeclarationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeclarationServiceServer).ListDeclarations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeclarationService_ListDeclarations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeclarationServiceServer).ListDeclarations(ctx, req.(*ListDeclarationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeclarationService_UpdateDeclarationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeclarationServiceServer).UpdateDeclarationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeclarationService_UpdateDeclarationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeclarationServiceServer).UpdateDeclarationStatus(ctx, req.(*UpdateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeclarationService_AssessDeclaration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssessDeclarationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeclarationServiceServer).AssessDeclaration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeclarationService_AssessDeclaration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeclarationServiceServer).AssessDeclaration(ctx, req.(*AssessDeclarationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeclarationService_ClearDeclaration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearDeclarationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeclarationServiceServer).ClearDeclaration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeclarationService_ClearDeclaration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeclarationServiceServer).ClearDeclaration(ctx, req.(*ClearDeclarationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeclarationService_GetDeclarationStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeclarationServiceServer).GetDeclarationStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeclarationService_GetDeclarationStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeclarationServiceServer).GetDeclarationStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeclarationService_ServiceDesc is the grpc.ServiceDesc for DeclarationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeclarationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tradegateway.declaration.v1.DeclarationService",
	HandlerType: (*DeclarationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDeclaration",
			Handler:    _DeclarationService_CreateDeclaration_Handler,
		},
		{
			MethodName: "SubmitDeclaration",
			Handler:    _DeclarationService_SubmitDeclaration_Handler,
		},
		{
			MethodName: "GetDeclaration",
			Handler:    _DeclarationService_GetDeclaration_Handler,
		},
		{
			MethodName: "ListDeclarations",
			Handler:    _DeclarationService_ListDeclarations_Handler,
		},
		{
			MethodName: "UpdateDeclarationStatus",
			Handler:    _DeclarationService_UpdateDeclarationStatus_Handler,
		},
		{
			MethodName: "AssessDeclaration",
			Handler:    _DeclarationService_AssessDeclaration_Handler,
		},
		{
			MethodName: "ClearDeclaration",
			Handler:    _DeclarationService_ClearDeclaration_Handler,
		},
		{
			MethodName: "GetDeclarationStats",
			Handler:    _DeclarationService_GetDeclarationStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "declaration.proto",
}
