apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
  namespace: tradegateway
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: "kafka:9092"
  - name: consumerGroup
    value: "dapr-consumers"
  - name: authRequired
    value: "false"
  - name: initialOffset
    value: "newest"
  - name: maxMessageBytes
    value: "1048576"
