// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: rules/rules.proto

package rules

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	common "tradegateway/proto/common"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuleSeverity int32

const (
	RuleSeverity_RULE_SEVERITY_UNSPECIFIED RuleSeverity = 0
	RuleSeverity_INFO                      RuleSeverity = 1
	RuleSeverity_WARNING                   RuleSeverity = 2
	RuleSeverity_ERROR                     RuleSeverity = 3
	RuleSeverity_BLOCKING                  RuleSeverity = 4
)

// Enum value maps for RuleSeverity.
var (
	RuleSeverity_name = map[int32]string{
		0: "RULE_SEVERITY_UNSPECIFIED",
		1: "INFO",
		2: "WARNING",
		3: "ERROR",
		4: "BLOCKING",
	}
	RuleSeverity_value = map[string]int32{
		"RULE_SEVERITY_UNSPECIFIED": 0,
		"INFO":                      1,
		"WARNING":                   2,
		"ERROR":                     3,
		"BLOCKING":                  4,
	}
)

func (x RuleSeverity) Enum() *RuleSeverity {
	p := new(RuleSeverity)
	*p = x
	return p
}

func (x RuleSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuleSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_rules_rules_proto_enumTypes[0].Descriptor()
}

func (RuleSeverity) Type() protoreflect.EnumType {
	return &file_rules_rules_proto_enumTypes[0]
}

func (x RuleSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuleSeverity.Descriptor instead.
func (RuleSeverity) EnumDescriptor() ([]byte, []int) {
	return file_rules_rules_proto_rawDescGZIP(), []int{0}
}

type RuleCategory int32

const (
	RuleCategory_RULE_CATEGORY_UNSPECIFIED RuleCategory = 0
	RuleCategory_HS_CODE_VALIDATION        RuleCategory = 1
	RuleCategory_VALUATION                 RuleCategory = 2
	RuleCategory_WEIGHT_VOLUME             RuleCategory = 3
	RuleCategory_DOCUMENT_COMPLETENESS     RuleCategory = 4
	RuleCategory_PROHIBITED_GOODS          RuleCategory = 5
	RuleCategory_RESTRICTED_GOODS          RuleCategory = 6
	RuleCategory_TARIFF_CLASSIFICATION     RuleCategory = 7
	RuleCategory_ORIGIN_VERIFICATION       RuleCategory = 8
	RuleCategory_LICENSING                 RuleCategory = 9
	RuleCategory_QUOTA                     RuleCategory = 10
	RuleCategory_ANTI_DUMPING              RuleCategory = 11
	RuleCategory_SAFEGUARD                 RuleCategory = 12
	RuleCategory_PHYTOSANITARY             RuleCategory = 13
	RuleCategory_VETERINARY                RuleCategory = 14
	RuleCategory_FOOD_SAFETY               RuleCategory = 15
	RuleCategory_DRUG_PRECURSOR            RuleCategory = 16
	RuleCategory_DUAL_USE                  RuleCategory = 17
	RuleCategory_ARMS_MUNITIONS            RuleCategory = 18
	RuleCategory_CITES                     RuleCategory = 19
	RuleCategory_CULTURAL_PROPERTY         RuleCategory = 20
)

// Enum value maps for RuleCategory.
var (
	RuleCategory_name = map[int32]string{
		0:  "RULE_CATEGORY_UNSPECIFIED",
		1:  "HS_CODE_VALIDATION",
		2:  "VALUATION",
		3:  "WEIGHT_VOLUME",
		4:  "DOCUMENT_COMPLETENESS",
		5:  "PROHIBITED_GOODS",
		6:  "RESTRICTED_GOODS",
		7:  "TARIFF_CLASSIFICATION",
		8:  "ORIGIN_VERIFICATION",
		9:  "LICENSING",
		10: "QUOTA",
		11: "ANTI_DUMPING",
		12: "SAFEGUARD",
		13: "PHYTOSANITARY",
		14: "VETERINARY",
		15: "FOOD_SAFETY",
		16: "DRUG_PRECURSOR",
		17: "DUAL_USE",
		18: "ARMS_MUNITIONS",
		19: "CITES",
		20: "CULTURAL_PROPERTY",
	}
	RuleCategory_value = map[string]int32{
		"RULE_CATEGORY_UNSPECIFIED": 0,
		"HS_CODE_VALIDATION":        1,
		"VALUATION":                 2,
		"WEIGHT_VOLUME":             3,
		"DOCUMENT_COMPLETENESS":     4,
		"PROHIBITED_GOODS":          5,
		"RESTRICTED_GOODS":          6,
		"TARIFF_CLASSIFICATION":     7,
		"ORIGIN_VERIFICATION":       8,
		"LICENSING":                 9,
		"QUOTA":                     10,
		"ANTI_DUMPING":              11,
		"SAFEGUARD":                 12,
		"PHYTOSANITARY":             13,
		"VETERINARY":                14,
		"FOOD_SAFETY":               15,
		"DRUG_PRECURSOR":            16,
		"DUAL_USE":                  17,
		"ARMS_MUNITIONS":            18,
		"CITES":                     19,
		"CULTURAL_PROPERTY":         20,
	}
)

func (x RuleCategory) Enum() *RuleCategory {
	p := new(RuleCategory)
	*p = x
	return p
}

func (x RuleCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuleCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_rules_rules_proto_enumTypes[1].Descriptor()
}

func (RuleCategory) Type() protoreflect.EnumType {
	return &file_rules_rules_proto_enumTypes[1]
}

func (x RuleCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuleCategory.Descriptor instead.
func (RuleCategory) EnumDescriptor() ([]byte, []int) {
	return file_rules_rules_proto_rawDescGZIP(), []int{1}
}

type RuleViolation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	RuleName      string                 `protobuf:"bytes,2,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	Category      RuleCategory           `protobuf:"varint,3,opt,name=category,proto3,enum=rules.RuleCategory" json:"category,omitempty"`
	Severity      RuleSeverity           `protobuf:"varint,4,opt,name=severity,proto3,enum=rules.RuleSeverity" json:"severity,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Field         string                 `protobuf:"bytes,6,opt,name=field,proto3" json:"field,omitempty"`             // which field triggered this
	Remediation   string                 `protobuf:"bytes,7,opt,name=remediation,proto3" json:"remediation,omitempty"` // how to fix it
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleViolation) Reset() {
	*x = RuleViolation{}
	mi := &file_rules_rules_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleViolation) ProtoMessage() {}

func (x *RuleViolation) ProtoReflect() protoreflect.Message {
	mi := &file_rules_rules_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleViolation.ProtoReflect.Descriptor instead.
func (*RuleViolation) Descriptor() ([]byte, []int) {
	return file_rules_rules_proto_rawDescGZIP(), []int{0}
}

func (x *RuleViolation) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *RuleViolation) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *RuleViolation) GetCategory() RuleCategory {
	if x != nil {
		return x.Category
	}
	return RuleCategory_RULE_CATEGORY_UNSPECIFIED
}

func (x *RuleViolation) GetSeverity() RuleSeverity {
	if x != nil {
		return x.Severity
	}
	return RuleSeverity_RULE_SEVERITY_UNSPECIFIED
}

func (x *RuleViolation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RuleViolation) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *RuleViolation) GetRemediation() string {
	if x != nil {
		return x.Remediation
	}
	return ""
}

type ValidateDeclarationRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DeclarationId        int64                  `protobuf:"varint,1,opt,name=declaration_id,json=declarationId,proto3" json:"declaration_id,omitempty"`
	HsCode               string                 `protobuf:"bytes,2,opt,name=hs_code,json=hsCode,proto3" json:"hs_code,omitempty"`
	GoodsDescription     string                 `protobuf:"bytes,3,opt,name=goods_description,json=goodsDescription,proto3" json:"goods_description,omitempty"`
	CountryOfOrigin      string                 `protobuf:"bytes,4,opt,name=country_of_origin,json=countryOfOrigin,proto3" json:"country_of_origin,omitempty"`
	CountryOfDest        string                 `protobuf:"bytes,5,opt,name=country_of_dest,json=countryOfDest,proto3" json:"country_of_dest,omitempty"`
	DeclarationType      string                 `protobuf:"bytes,6,opt,name=declaration_type,json=declarationType,proto3" json:"declaration_type,omitempty"`
	InvoiceValueUsd      float64                `protobuf:"fixed64,7,opt,name=invoice_value_usd,json=invoiceValueUsd,proto3" json:"invoice_value_usd,omitempty"`
	GrossWeightKg        float64                `protobuf:"fixed64,8,opt,name=gross_weight_kg,json=grossWeightKg,proto3" json:"gross_weight_kg,omitempty"`
	NumPackages          int32                  `protobuf:"varint,9,opt,name=num_packages,json=numPackages,proto3" json:"num_packages,omitempty"`
	DocumentTypesPresent []string               `protobuf:"bytes,10,rep,name=document_types_present,json=documentTypesPresent,proto3" json:"document_types_present,omitempty"`
	HasLicense           bool                   `protobuf:"varint,11,opt,name=has_license,json=hasLicense,proto3" json:"has_license,omitempty"`
	LicenseNumber        string                 `protobuf:"bytes,12,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ValidateDeclarationRequest) Reset() {
	*x = ValidateDeclarationRequest{}
	mi := &file_rules_rules_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateDeclarationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateDeclarationRequest) ProtoMessage() {}

func (x *ValidateDeclarationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rules_rules_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateDeclarationRequest.ProtoReflect.Descriptor instead.
func (*ValidateDeclarationRequest) Descriptor() ([]byte, []int) {
	return file_rules_rules_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateDeclarationRequest) GetDeclarationId() int64 {
	if x != nil {
		return x.DeclarationId
	}
	return 0
}

func (x *ValidateDeclarationRequest) GetHsCode() string {
	if x != nil {
		return x.HsCode
	}
	return ""
}

func (x *ValidateDeclarationRequest) GetGoodsDescription() string {
	if x != nil {
		return x.GoodsDescription
	}
	return ""
}

func (x *ValidateDeclarationRequest) GetCountryOfOrigin() string {
	if x != nil {
		return x.CountryOfOrigin
	}
	return ""
}

func (x *ValidateDeclarationRequest) GetCountryOfDest() string {
	if x != nil {
		return x.CountryOfDest
	}
	return ""
}

func (x *ValidateDeclarationRequest) GetDeclarationType() string {
	if x != nil {
		return x.DeclarationType
	}
	return ""
}

func (x *ValidateDeclarationRequest) GetInvoiceValueUsd() float64 {
	if x != nil {
		return x.InvoiceValueUsd
	}
	return 0
}

func (x *ValidateDeclarationRequest) GetGrossWeightKg() float64 {
	if x != nil {
		return x.GrossWeightKg
	}
	return 0
}

func (x *ValidateDeclarationRequest) GetNumPackages() int32 {
	if x != nil {
		return x.NumPackages
	}
	return 0
}

func (x *ValidateDeclarationRequest) GetDocumentTypesPresent() []string {
	if x != nil {
		return x.DocumentTypesPresent
	}
	return nil
}

func (x *ValidateDeclarationRequest) GetHasLicense() bool {
	if x != nil {
		return x.HasLicense
	}
	return false
}

func (x *ValidateDeclarationRequest) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

type ValidateDeclarationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Violations    []*RuleViolation       `protobuf:"bytes,2,rep,name=violations,proto3" json:"violations,omitempty"`
	RulesChecked  int32                  `protobuf:"varint,3,opt,name=rules_checked,json=rulesChecked,proto3" json:"rules_checked,omitempty"`
	RulesPassed   int32                  `protobuf:"varint,4,opt,name=rules_passed,json=rulesPassed,proto3" json:"rules_passed,omitempty"`
	RulesFailed   int32                  `protobuf:"varint,5,opt,name=rules_failed,json=rulesFailed,proto3" json:"rules_failed,omitempty"`
	ValidationId  string                 `protobuf:"bytes,6,opt,name=validation_id,json=validationId,proto3" json:"validation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateDeclarationResponse) Reset() {
	*x = ValidateDeclarationResponse{}
	mi := &file_rules_rules_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateDeclarationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateDeclarationResponse) ProtoMessage() {}

func (x *ValidateDeclarationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rules_rules_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateDeclarationResponse.ProtoReflect.Descriptor instead.
func (*ValidateDeclarationResponse) Descriptor() ([]byte, []int) {
	return file_rules_rules_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateDeclarationResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateDeclarationResponse) GetViolations() []*RuleViolation {
	if x != nil {
		return x.Violations
	}
	return nil
}

func (x *ValidateDeclarationResponse) GetRulesChecked() int32 {
	if x != nil {
		return x.RulesChecked
	}
	return 0
}

func (x *ValidateDeclarationResponse) GetRulesPassed() int32 {
	if x != nil {
		return x.RulesPassed
	}
	return 0
}

func (x *ValidateDeclarationResponse) GetRulesFailed() int32 {
	if x != nil {
		return x.RulesFailed
	}
	return 0
}

func (x *ValidateDeclarationResponse) GetValidationId() string {
	if x != nil {
		return x.ValidationId
	}
	return ""
}

type GetRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      RuleCategory           `protobuf:"varint,1,opt,name=category,proto3,enum=rules.RuleCategory" json:"category,omitempty"` // 0 = all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRulesRequest) Reset() {
	*x = GetRulesRequest{}
	mi := &file_rules_rules_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRulesRequest) ProtoMessage() {}

func (x *GetRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rules_rules_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRulesRequest.ProtoReflect.Descriptor instead.
func (*GetRulesRequest) Descriptor() ([]byte, []int) {
	return file_rules_rules_proto_rawDescGZIP(), []int{3}
}

func (x *GetRulesRequest) GetCategory() RuleCategory {
	if x != nil {
		return x.Category
	}
	return RuleCategory_RULE_CATEGORY_UNSPECIFIED
}

type Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      RuleCategory           `protobuf:"varint,3,opt,name=category,proto3,enum=rules.RuleCategory" json:"category,omitempty"`
	Severity      RuleSeverity           `protobuf:"varint,4,opt,name=severity,proto3,enum=rules.RuleSeverity" json:"severity,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Active        bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_rules_rules_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_rules_rules_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_rules_rules_proto_rawDescGZIP(), []int{4}
}

func (x *Rule) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *Rule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rule) GetCategory() RuleCategory {
	if x != nil {
		return x.Category
	}
	return RuleCategory_RULE_CATEGORY_UNSPECIFIED
}

func (x *Rule) GetSeverity() RuleSeverity {
	if x != nil {
		return x.Severity
	}
	return RuleSeverity_RULE_SEVERITY_UNSPECIFIED
}

func (x *Rule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Rule) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type GetRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*Rule                `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRulesResponse) Reset() {
	*x = GetRulesResponse{}
	mi := &file_rules_rules_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRulesResponse) ProtoMessage() {}

func (x *GetRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rules_rules_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRulesResponse.ProtoReflect.Descriptor instead.
func (*GetRulesResponse) Descriptor() ([]byte, []int) {
	return file_rules_rules_proto_rawDescGZIP(), []int{5}
}

func (x *GetRulesResponse) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *GetRulesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_rules_rules_proto protoreflect.FileDescriptor

const file_rules_rules_proto_rawDesc = "" +
	"\n" +
	"\x11rules/rules.proto\x12\x05rules\x1a\x13common/common.proto\"\xf9\x01\n" +
	"\rRuleViolation\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x1b\n" +
	"\trule_name\x18\x02 \x01(\tR\bruleName\x12/\n" +
	"\bcategory\x18\x03 \x01(\x0e2\x13.rules.RuleCategoryR\bcategory\x12/\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x13.rules.RuleSeverityR\bseverity\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x14\n" +
	"\x05field\x18\x06 \x01(\tR\x05field\x12 \n" +
	"\vremediation\x18\a \x01(\tR\vremediation\"\xfd\x03\n" +
	"\x1aValidateDeclarationRequest\x12%\n" +
	"\x0edeclaration_id\x18\x01 \x01(\x03R\rdeclarationId\x12\x17\n" +
	"\ahs_code\x18\x02 \x01(\tR\x06hsCode\x12+\n" +
	"\x11goods_description\x18\x03 \x01(\tR\x10goodsDescription\x12*\n" +
	"\x11country_of_origin\x18\x04 \x01(\tR\x0fcountryOfOrigin\x12&\n" +
	"\x0fcountry_of_dest\x18\x05 \x01(\tR\rcountryOfDest\x12)\n" +
	"\x10declaration_type\x18\x06 \x01(\tR\x0fdeclarationType\x12*\n" +
	"\x11invoice_value_usd\x18\a \x01(\x01R\x0finvoiceValueUsd\x12&\n" +
	"\x0fgross_weight_kg\x18\b \x01(\x01R\rgrossWeightKg\x12!\n" +
	"\fnum_packages\x18\t \x01(\x05R\vnumPackages\x124\n" +
	"\x16document_types_present\x18\n" +
	" \x03(\tR\x14documentTypesPresent\x12\x1f\n" +
	"\vhas_license\x18\v \x01(\bR\n" +
	"hasLicense\x12%\n" +
	"\x0elicense_number\x18\f \x01(\tR\rlicenseNumber\"\xfe\x01\n" +
	"\x1bValidateDeclarationResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x124\n" +
	"\n" +
	"violations\x18\x02 \x03(\v2\x14.rules.RuleViolationR\n" +
	"violations\x12#\n" +
	"\rrules_checked\x18\x03 \x01(\x05R\frulesChecked\x12!\n" +
	"\frules_passed\x18\x04 \x01(\x05R\vrulesPassed\x12!\n" +
	"\frules_failed\x18\x05 \x01(\x05R\vrulesFailed\x12#\n" +
	"\rvalidation_id\x18\x06 \x01(\tR\fvalidationId\"B\n" +
	"\x0fGetRulesRequest\x12/\n" +
	"\bcategory\x18\x01 \x01(\x0e2\x13.rules.RuleCategoryR\bcategory\"\xcf\x01\n" +
	"\x04Rule\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\bcategory\x18\x03 \x01(\x0e2\x13.rules.RuleCategoryR\bcategory\x12/\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x13.rules.RuleSeverityR\bseverity\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\"K\n" +
	"\x10GetRulesResponse\x12!\n" +
	"\x05rules\x18\x01 \x03(\v2\v.rules.RuleR\x05rules\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total*]\n" +
	"\fRuleSeverity\x12\x1d\n" +
	"\x19RULE_SEVERITY_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\v\n" +
	"\aWARNING\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\x12\f\n" +
	"\bBLOCKING\x10\x04*\xa9\x03\n" +
	"\fRuleCategory\x12\x1d\n" +
	"\x19RULE_CATEGORY_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12HS_CODE_VALIDATION\x10\x01\x12\r\n" +
	"\tVALUATION\x10\x02\x12\x11\n" +
	"\rWEIGHT_VOLUME\x10\x03\x12\x19\n" +
	"\x15DOCUMENT_COMPLETENESS\x10\x04\x12\x14\n" +
	"\x10PROHIBITED_GOODS\x10\x05\x12\x14\n" +
	"\x10RESTRICTED_GOODS\x10\x06\x12\x19\n" +
	"\x15TARIFF_CLASSIFICATION\x10\a\x12\x17\n" +
	"\x13ORIGIN_VERIFICATION\x10\b\x12\r\n" +
	"\tLICENSING\x10\t\x12\t\n" +
	"\x05QUOTA\x10\n" +
	"\x12\x10\n" +
	"\fANTI_DUMPING\x10\v\x12\r\n" +
	"\tSAFEGUARD\x10\f\x12\x11\n" +
	"\rPHYTOSANITARY\x10\r\x12\x0e\n" +
	"\n" +
	"VETERINARY\x10\x0e\x12\x0f\n" +
	"\vFOOD_SAFETY\x10\x0f\x12\x12\n" +
	"\x0eDRUG_PRECURSOR\x10\x10\x12\f\n" +
	"\bDUAL_USE\x10\x11\x12\x12\n" +
	"\x0eARMS_MUNITIONS\x10\x12\x12\t\n" +
	"\x05CITES\x10\x13\x12\x15\n" +
	"\x11CULTURAL_PROPERTY\x10\x142\xde\x01\n" +
	"\n" +
	"RuleEngine\x12\\\n" +
	"\x13ValidateDeclaration\x12!.rules.ValidateDeclarationRequest\x1a\".rules.ValidateDeclarationResponse\x12;\n" +
	"\bGetRules\x12\x16.rules.GetRulesRequest\x1a\x17.rules.GetRulesResponse\x125\n" +
	"\x06Health\x12\x13.common.PageRequest\x1a\x16.common.HealthResponseB\x1aZ\x18tradegateway/proto/rulesb\x06proto3"

var (
	file_rules_rules_proto_rawDescOnce sync.Once
	file_rules_rules_proto_rawDescData []byte
)

func file_rules_rules_proto_rawDescGZIP() []byte {
	file_rules_rules_proto_rawDescOnce.Do(func() {
		file_rules_rules_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rules_rules_proto_rawDesc), len(file_rules_rules_proto_rawDesc)))
	})
	return file_rules_rules_proto_rawDescData
}

var file_rules_rules_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_rules_rules_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rules_rules_proto_goTypes = []any{
	(RuleSeverity)(0),                   // 0: rules.RuleSeverity
	(RuleCategory)(0),                   // 1: rules.RuleCategory
	(*RuleViolation)(nil),               // 2: rules.RuleViolation
	(*ValidateDeclarationRequest)(nil),  // 3: rules.ValidateDeclarationRequest
	(*ValidateDeclarationResponse)(nil), // 4: rules.ValidateDeclarationResponse
	(*GetRulesRequest)(nil),             // 5: rules.GetRulesRequest
	(*Rule)(nil),                        // 6: rules.Rule
	(*GetRulesResponse)(nil),            // 7: rules.GetRulesResponse
	(*common.PageRequest)(nil),          // 8: common.PageRequest
	(*common.HealthResponse)(nil),       // 9: common.HealthResponse
}
var file_rules_rules_proto_depIdxs = []int32{
	1,  // 0: rules.RuleViolation.category:type_name -> rules.RuleCategory
	0,  // 1: rules.RuleViolation.severity:type_name -> rules.RuleSeverity
	2,  // 2: rules.ValidateDeclarationResponse.violations:type_name -> rules.RuleViolation
	1,  // 3: rules.GetRulesRequest.category:type_name -> rules.RuleCategory
	1,  // 4: rules.Rule.category:type_name -> rules.RuleCategory
	0,  // 5: rules.Rule.severity:type_name -> rules.RuleSeverity
	6,  // 6: rules.GetRulesResponse.rules:type_name -> rules.Rule
	3,  // 7: rules.RuleEngine.ValidateDeclaration:input_type -> rules.ValidateDeclarationRequest
	5,  // 8: rules.RuleEngine.GetRules:input_type -> rules.GetRulesRequest
	8,  // 9: rules.RuleEngine.Health:input_type -> common.PageRequest
	4,  // 10: rules.RuleEngine.ValidateDeclaration:output_type -> rules.ValidateDeclarationResponse
	7,  // 11: rules.RuleEngine.GetRules:output_type -> rules.GetRulesResponse
	9,  // 12: rules.RuleEngine.Health:output_type -> common.HealthResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_rules_rules_proto_init() }
func file_rules_rules_proto_init() {
	if File_rules_rules_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rules_rules_proto_rawDesc), len(file_rules_rules_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rules_rules_proto_goTypes,
		DependencyIndexes: file_rules_rules_proto_depIdxs,
		EnumInfos:         file_rules_rules_proto_enumTypes,
		MessageInfos:      file_rules_rules_proto_msgTypes,
	}.Build()
	File_rules_rules_proto = out.File
	file_rules_rules_proto_goTypes = nil
	file_rules_rules_proto_depIdxs = nil
}
