// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: rules/rules.proto

package rules

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "tradegateway/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RuleEngine_ValidateDeclaration_FullMethodName = "/rules.RuleEngine/ValidateDeclaration"
	RuleEngine_GetRules_FullMethodName            = "/rules.RuleEngine/GetRules"
	RuleEngine_Health_FullMethodName              = "/rules.RuleEngine/Health"
)

// RuleEngineClient is the client API for RuleEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuleEngineClient interface {
	ValidateDeclaration(ctx context.Context, in *ValidateDeclarationRequest, opts ...grpc.CallOption) (*ValidateDeclarationResponse, error)
	GetRules(ctx context.Context, in *GetRulesRequest, opts ...grpc.CallOption) (*GetRulesResponse, error)
	Health(ctx context.Context, in *common.PageRequest, opts ...grpc.CallOption) (*common.HealthResponse, error)
}

type ruleEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewRuleEngineClient(cc grpc.ClientConnInterface) RuleEngineClient {
	return &ruleEngineClient{cc}
}

func (c *ruleEngineClient) ValidateDeclaration(ctx context.Context, in *ValidateDeclarationRequest, opts ...grpc.CallOption) (*ValidateDeclarationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateDeclarationResponse)
	err := c.cc.Invoke(ctx, RuleEngine_ValidateDeclaration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleEngineClient) GetRules(ctx context.Context, in *GetRulesRequest, opts ...grpc.CallOption) (*GetRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRulesResponse)
	err := c.cc.Invoke(ctx, RuleEngine_GetRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleEngineClient) Health(ctx context.Context, in *common.PageRequest, opts ...grpc.CallOption) (*common.HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.HealthResponse)
	err := c.cc.Invoke(ctx, RuleEngine_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuleEngineServer is the server API for RuleEngine service.
// All implementations must embed UnimplementedRuleEngineServer
// for forward compatibility.
type RuleEngineServer interface {
	ValidateDeclaration(context.Context, *ValidateDeclarationRequest) (*ValidateDeclarationResponse, error)
	GetRules(context.Context, *GetRulesRequest) (*GetRulesResponse, error)
	Health(context.Context, *common.PageRequest) (*common.HealthResponse, error)
	mustEmbedUnimplementedRuleEngineServer()
}

// UnimplementedRuleEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuleEngineServer struct{}

func (UnimplementedRuleEngineServer) ValidateDeclaration(context.Context, *ValidateDeclarationRequest) (*ValidateDeclarationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateDeclaration not implemented")
}
func (UnimplementedRuleEngineServer) GetRules(context.Context, *GetRulesRequest) (*GetRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRules not implemented")
}
func (UnimplementedRuleEngineServer) Health(context.Context, *common.PageRequest) (*common.HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedRuleEngineServer) mustEmbedUnimplementedRuleEngineServer() {}
func (UnimplementedRuleEngineServer) testEmbeddedByValue()                    {}

// UnsafeRuleEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuleEngineServer will
// result in compilation errors.
type UnsafeRuleEngineServer interface {
	mustEmbedUnimplementedRuleEngineServer()
}

func RegisterRuleEngineServer(s grpc.ServiceRegistrar, srv RuleEngineServer) {
	// If the following call panics, it indicates UnimplementedRuleEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuleEngine_ServiceDesc, srv)
}

func _RuleEngine_ValidateDeclaration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateDeclarationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleEngineServer).ValidateDeclaration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleEngine_ValidateDeclaration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleEngineServer).ValidateDeclaration(ctx, req.(*ValidateDeclarationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleEngine_GetRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleEngineServer).GetRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleEngine_GetRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleEngineServer).GetRules(ctx, req.(*GetRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleEngine_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleEngineServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleEngine_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleEngineServer).Health(ctx, req.(*common.PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RuleEngine_ServiceDesc is the grpc.ServiceDesc for RuleEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuleEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rules.RuleEngine",
	HandlerType: (*RuleEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateDeclaration",
			Handler:    _RuleEngine_ValidateDeclaration_Handler,
		},
		{
			MethodName: "GetRules",
			Handler:    _RuleEngine_GetRules_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _RuleEngine_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rules/rules.proto",
}
