// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: profile/profile.proto

package profile

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	common "tradegateway/proto/common"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StakeholderRole int32

const (
	StakeholderRole_STAKEHOLDER_ROLE_UNSPECIFIED StakeholderRole = 0
	StakeholderRole_TRADER                       StakeholderRole = 1
	StakeholderRole_CUSTOMS_OFFICER              StakeholderRole = 2
	StakeholderRole_OGA_OFFICER                  StakeholderRole = 3
	StakeholderRole_ADMIN                        StakeholderRole = 4
	StakeholderRole_SECURITY_ANALYST             StakeholderRole = 5
	StakeholderRole_AUDITOR                      StakeholderRole = 6
)

// Enum value maps for StakeholderRole.
var (
	StakeholderRole_name = map[int32]string{
		0: "STAKEHOLDER_ROLE_UNSPECIFIED",
		1: "TRADER",
		2: "CUSTOMS_OFFICER",
		3: "OGA_OFFICER",
		4: "ADMIN",
		5: "SECURITY_ANALYST",
		6: "AUDITOR",
	}
	StakeholderRole_value = map[string]int32{
		"STAKEHOLDER_ROLE_UNSPECIFIED": 0,
		"TRADER":                       1,
		"CUSTOMS_OFFICER":              2,
		"OGA_OFFICER":                  3,
		"ADMIN":                        4,
		"SECURITY_ANALYST":             5,
		"AUDITOR":                      6,
	}
)

func (x StakeholderRole) Enum() *StakeholderRole {
	p := new(StakeholderRole)
	*p = x
	return p
}

func (x StakeholderRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StakeholderRole) Descriptor() protoreflect.EnumDescriptor {
	return file_profile_profile_proto_enumTypes[0].Descriptor()
}

func (StakeholderRole) Type() protoreflect.EnumType {
	return &file_profile_profile_proto_enumTypes[0]
}

func (x StakeholderRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StakeholderRole.Descriptor instead.
func (StakeholderRole) EnumDescriptor() ([]byte, []int) {
	return file_profile_profile_proto_rawDescGZIP(), []int{0}
}

type ProfileStatus int32

const (
	ProfileStatus_PROFILE_STATUS_UNSPECIFIED ProfileStatus = 0
	ProfileStatus_PENDING_REVIEW             ProfileStatus = 1
	ProfileStatus_APPROVED                   ProfileStatus = 2
	ProfileStatus_SUSPENDED                  ProfileStatus = 3
	ProfileStatus_REJECTED                   ProfileStatus = 4
)

// Enum value maps for ProfileStatus.
var (
	ProfileStatus_name = map[int32]string{
		0: "PROFILE_STATUS_UNSPECIFIED",
		1: "PENDING_REVIEW",
		2: "APPROVED",
		3: "SUSPENDED",
		4: "REJECTED",
	}
	ProfileStatus_value = map[string]int32{
		"PROFILE_STATUS_UNSPECIFIED": 0,
		"PENDING_REVIEW":             1,
		"APPROVED":                   2,
		"SUSPENDED":                  3,
		"REJECTED":                   4,
	}
)

func (x ProfileStatus) Enum() *ProfileStatus {
	p := new(ProfileStatus)
	*p = x
	return p
}

func (x ProfileStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProfileStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_profile_profile_proto_enumTypes[1].Descriptor()
}

func (ProfileStatus) Type() protoreflect.EnumType {
	return &file_profile_profile_proto_enumTypes[1]
}

func (x ProfileStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProfileStatus.Descriptor instead.
func (ProfileStatus) EnumDescriptor() ([]byte, []int) {
	return file_profile_profile_proto_rawDescGZIP(), []int{1}
}

type TraderType int32

const (
	TraderType_TRADER_TYPE_UNSPECIFIED TraderType = 0
	TraderType_IMPORTER                TraderType = 1
	TraderType_EXPORTER                TraderType = 2
	TraderType_CUSTOMS_BROKER          TraderType = 3
	TraderType_FREIGHT_FORWARDER       TraderType = 4
	TraderType_WAREHOUSE_OPERATOR      TraderType = 5
	TraderType_SHIPPING_LINE           TraderType = 6
)

// Enum value maps for TraderType.
var (
	TraderType_name = map[int32]string{
		0: "TRADER_TYPE_UNSPECIFIED",
		1: "IMPORTER",
		2: "EXPORTER",
		3: "CUSTOMS_BROKER",
		4: "FREIGHT_FORWARDER",
		5: "WAREHOUSE_OPERATOR",
		6: "SHIPPING_LINE",
	}
	TraderType_value = map[string]int32{
		"TRADER_TYPE_UNSPECIFIED": 0,
		"IMPORTER":                1,
		"EXPORTER":                2,
		"CUSTOMS_BROKER":          3,
		"FREIGHT_FORWARDER":       4,
		"WAREHOUSE_OPERATOR":      5,
		"SHIPPING_LINE":           6,
	}
)

func (x TraderType) Enum() *TraderType {
	p := new(TraderType)
	*p = x
	return p
}

func (x TraderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TraderType) Descriptor() protoreflect.EnumDescriptor {
	return file_profile_profile_proto_enumTypes[2].Descriptor()
}

func (TraderType) Type() protoreflect.EnumType {
	return &file_profile_profile_proto_enumTypes[2]
}

func (x TraderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TraderType.Descriptor instead.
func (TraderType) EnumDescriptor() ([]byte, []int) {
	return file_profile_profile_proto_rawDescGZIP(), []int{2}
}

type StakeholderProfile struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId             int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role               StakeholderRole        `protobuf:"varint,3,opt,name=role,proto3,enum=profile.StakeholderRole" json:"role,omitempty"`
	OrganizationName   string                 `protobuf:"bytes,4,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	TaxId              string                 `protobuf:"bytes,5,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"`
	RegistrationNumber string                 `protobuf:"bytes,6,opt,name=registration_number,json=registrationNumber,proto3" json:"registration_number,omitempty"`
	TraderType         TraderType             `protobuf:"varint,7,opt,name=trader_type,json=traderType,proto3,enum=profile.TraderType" json:"trader_type,omitempty"`
	Country            string                 `protobuf:"bytes,8,opt,name=country,proto3" json:"country,omitempty"`
	Address            string                 `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	Phone              string                 `protobuf:"bytes,10,opt,name=phone,proto3" json:"phone,omitempty"`
	ContactEmail       string                 `protobuf:"bytes,11,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	Status             ProfileStatus          `protobuf:"varint,12,opt,name=status,proto3,enum=profile.ProfileStatus" json:"status,omitempty"`
	IsAeo              bool                   `protobuf:"varint,13,opt,name=is_aeo,json=isAeo,proto3" json:"is_aeo,omitempty"`
	AeoCertificate     string                 `protobuf:"bytes,14,opt,name=aeo_certificate,json=aeoCertificate,proto3" json:"aeo_certificate,omitempty"`
	ComplianceScore    int32                  `protobuf:"varint,15,opt,name=compliance_score,json=complianceScore,proto3" json:"compliance_score,omitempty"`
	ReviewedByName     string                 `protobuf:"bytes,16,opt,name=reviewed_by_name,json=reviewedByName,proto3" json:"reviewed_by_name,omitempty"`
	AeoExpiresAt       *timestamp.Timestamp   `protobuf:"bytes,17,opt,name=aeo_expires_at,json=aeoExpiresAt,proto3" json:"aeo_expires_at,omitempty"`
	CreatedAt          *timestamp.Timestamp   `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamp.Timestamp   `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StakeholderProfile) Reset() {
	*x = StakeholderProfile{}
	mi := &file_profile_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StakeholderProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StakeholderProfile) ProtoMessage() {}

func (x *StakeholderProfile) ProtoReflect() protoreflect.Message {
	mi := &file_profile_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StakeholderProfile.ProtoReflect.Descriptor instead.
func (*StakeholderProfile) Descriptor() ([]byte, []int) {
	return file_profile_profile_proto_rawDescGZIP(), []int{0}
}

func (x *StakeholderProfile) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StakeholderProfile) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *StakeholderProfile) GetRole() StakeholderRole {
	if x != nil {
		return x.Role
	}
	return StakeholderRole_STAKEHOLDER_ROLE_UNSPECIFIED
}

func (x *StakeholderProfile) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *StakeholderProfile) GetTaxId() string {
	if x != nil {
		return x.TaxId
	}
	return ""
}

func (x *StakeholderProfile) GetRegistrationNumber() string {
	if x != nil {
		return x.RegistrationNumber
	}
	return ""
}

func (x *StakeholderProfile) GetTraderType() TraderType {
	if x != nil {
		return x.TraderType
	}
	return TraderType_TRADER_TYPE_UNSPECIFIED
}

func (x *StakeholderProfile) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *StakeholderProfile) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *StakeholderProfile) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *StakeholderProfile) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *StakeholderProfile) GetStatus() ProfileStatus {
	if x != nil {
		return x.Status
	}
	return ProfileStatus_PROFILE_STATUS_UNSPECIFIED
}

func (x *StakeholderProfile) GetIsAeo() bool {
	if x != nil {
		return x.IsAeo
	}
	return false
}

func (x *StakeholderProfile) GetAeoCertificate() string {
	if x != nil {
		return x.AeoCertificate
	}
	return ""
}

func (x *StakeholderProfile) GetComplianceScore() int32 {
	if x != nil {
		return x.ComplianceScore
	}
	return 0
}

func (x *StakeholderProfile) GetReviewedByName() string {
	if x != nil {
		return x.ReviewedByName
	}
	return ""
}

func (x *StakeholderProfile) GetAeoExpiresAt() *timestamp.Timestamp {
	if x != nil {
		return x.AeoExpiresAt
	}
	return nil
}

func (x *StakeholderProfile) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *StakeholderProfile) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateProfileRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role               StakeholderRole        `protobuf:"varint,2,opt,name=role,proto3,enum=profile.StakeholderRole" json:"role,omitempty"`
	OrganizationName   string                 `protobuf:"bytes,3,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	TaxId              string                 `protobuf:"bytes,4,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"`
	RegistrationNumber string                 `protobuf:"bytes,5,opt,name=registration_number,json=registrationNumber,proto3" json:"registration_number,omitempty"`
	TraderType         TraderType             `protobuf:"varint,6,opt,name=trader_type,json=traderType,proto3,enum=profile.TraderType" json:"trader_type,omitempty"`
	Country            string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	Address            string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Phone              string                 `protobuf:"bytes,9,opt,name=phone,proto3" json:"phone,omitempty"`
	ContactEmail       string                 `protobuf:"bytes,10,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_profile_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_profile_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProfileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateProfileRequest) GetRole() StakeholderRole {
	if x != nil {
		return x.Role
	}
	return StakeholderRole_STAKEHOLDER_ROLE_UNSPECIFIED
}

func (x *CreateProfileRequest) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *CreateProfileRequest) GetTaxId() string {
	if x != nil {
		return x.TaxId
	}
	return ""
}

func (x *CreateProfileRequest) GetRegistrationNumber() string {
	if x != nil {
		return x.RegistrationNumber
	}
	return ""
}

func (x *CreateProfileRequest) GetTraderType() TraderType {
	if x != nil {
		return x.TraderType
	}
	return TraderType_TRADER_TYPE_UNSPECIFIED
}

func (x *CreateProfileRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreateProfileRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateProfileRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateProfileRequest) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProfileId     int64                  `protobuf:"varint,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_profile_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_profile_proto_rawDescGZIP(), []int{2}
}

func (x *GetProfileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetProfileRequest) GetProfileId() int64 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

type UpdateProfileStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     int64                  `protobuf:"varint,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Status        ProfileStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=profile.ProfileStatus" json:"status,omitempty"`
	Notes         string                 `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	ReviewerId    int64                  `protobuf:"varint,4,opt,name=reviewer_id,json=reviewerId,proto3" json:"reviewer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileStatusRequest) Reset() {
	*x = UpdateProfileStatusRequest{}
	mi := &file_profile_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileStatusRequest) ProtoMessage() {}

func (x *UpdateProfileStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileStatusRequest) Descriptor() ([]byte, []int) {
	return file_profile_profile_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProfileStatusRequest) GetProfileId() int64 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

func (x *UpdateProfileStatusRequest) GetStatus() ProfileStatus {
	if x != nil {
		return x.Status
	}
	return ProfileStatus_PROFILE_STATUS_UNSPECIFIED
}

func (x *UpdateProfileStatusRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *UpdateProfileStatusRequest) GetReviewerId() int64 {
	if x != nil {
		return x.ReviewerId
	}
	return 0
}

type ListProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          StakeholderRole        `protobuf:"varint,1,opt,name=role,proto3,enum=profile.StakeholderRole" json:"role,omitempty"`   // 0 = all
	Status        ProfileStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=profile.ProfileStatus" json:"status,omitempty"` // 0 = all
	Page          *common.PageRequest    `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesRequest) Reset() {
	*x = ListProfilesRequest{}
	mi := &file_profile_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesRequest) ProtoMessage() {}

func (x *ListProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListProfilesRequest) Descriptor() ([]byte, []int) {
	return file_profile_profile_proto_rawDescGZIP(), []int{4}
}

func (x *ListProfilesRequest) GetRole() StakeholderRole {
	if x != nil {
		return x.Role
	}
	return StakeholderRole_STAKEHOLDER_ROLE_UNSPECIFIED
}

func (x *ListProfilesRequest) GetStatus() ProfileStatus {
	if x != nil {
		return x.Status
	}
	return ProfileStatus_PROFILE_STATUS_UNSPECIFIED
}

func (x *ListProfilesRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*StakeholderProfile  `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	Meta          *common.PageMeta       `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesResponse) Reset() {
	*x = ListProfilesResponse{}
	mi := &file_profile_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesResponse) ProtoMessage() {}

func (x *ListProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListProfilesResponse) Descriptor() ([]byte, []int) {
	return file_profile_profile_proto_rawDescGZIP(), []int{5}
}

func (x *ListProfilesResponse) GetProfiles() []*StakeholderProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *ListProfilesResponse) GetMeta() *common.PageMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type OnboardingChecklist struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ProfileId            int64                  `protobuf:"varint,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	ProfileSubmitted     bool                   `protobuf:"varint,2,opt,name=profile_submitted,json=profileSubmitted,proto3" json:"profile_submitted,omitempty"`
	ProfileApproved      bool                   `protobuf:"varint,3,opt,name=profile_approved,json=profileApproved,proto3" json:"profile_approved,omitempty"`
	DocumentsUploaded    bool                   `protobuf:"varint,4,opt,name=documents_uploaded,json=documentsUploaded,proto3" json:"documents_uploaded,omitempty"`
	TaxIdVerified        bool                   `protobuf:"varint,5,opt,name=tax_id_verified,json=taxIdVerified,proto3" json:"tax_id_verified,omitempty"`
	BankAccountLinked    bool                   `protobuf:"varint,6,opt,name=bank_account_linked,json=bankAccountLinked,proto3" json:"bank_account_linked,omitempty"`
	TrainingCompleted    bool                   `protobuf:"varint,7,opt,name=training_completed,json=trainingCompleted,proto3" json:"training_completed,omitempty"`
	SystemAccessGranted  bool                   `protobuf:"varint,8,opt,name=system_access_granted,json=systemAccessGranted,proto3" json:"system_access_granted,omitempty"`
	CompletionPercentage int32                  `protobuf:"varint,9,opt,name=completion_percentage,json=completionPercentage,proto3" json:"completion_percentage,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OnboardingChecklist) Reset() {
	*x = OnboardingChecklist{}
	mi := &file_profile_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnboardingChecklist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnboardingChecklist) ProtoMessage() {}

func (x *OnboardingChecklist) ProtoReflect() protoreflect.Message {
	mi := &file_profile_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnboardingChecklist.ProtoReflect.Descriptor instead.
func (*OnboardingChecklist) Descriptor() ([]byte, []int) {
	return file_profile_profile_proto_rawDescGZIP(), []int{6}
}

func (x *OnboardingChecklist) GetProfileId() int64 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

func (x *OnboardingChecklist) GetProfileSubmitted() bool {
	if x != nil {
		return x.ProfileSubmitted
	}
	return false
}

func (x *OnboardingChecklist) GetProfileApproved() bool {
	if x != nil {
		return x.ProfileApproved
	}
	return false
}

func (x *OnboardingChecklist) GetDocumentsUploaded() bool {
	if x != nil {
		return x.DocumentsUploaded
	}
	return false
}

func (x *OnboardingChecklist) GetTaxIdVerified() bool {
	if x != nil {
		return x.TaxIdVerified
	}
	return false
}

func (x *OnboardingChecklist) GetBankAccountLinked() bool {
	if x != nil {
		return x.BankAccountLinked
	}
	return false
}

func (x *OnboardingChecklist) GetTrainingCompleted() bool {
	if x != nil {
		return x.TrainingCompleted
	}
	return false
}

func (x *OnboardingChecklist) GetSystemAccessGranted() bool {
	if x != nil {
		return x.SystemAccessGranted
	}
	return false
}

func (x *OnboardingChecklist) GetCompletionPercentage() int32 {
	if x != nil {
		return x.CompletionPercentage
	}
	return 0
}

var File_profile_profile_proto protoreflect.FileDescriptor

const file_profile_profile_proto_rawDesc = "" +
	"\n" +
	"\x15profile/profile.proto\x12\aprofile\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\x82\x06\n" +
	"\x12StakeholderProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12,\n" +
	"\x04role\x18\x03 \x01(\x0e2\x18.profile.StakeholderRoleR\x04role\x12+\n" +
	"\x11organization_name\x18\x04 \x01(\tR\x10organizationName\x12\x15\n" +
	"\x06tax_id\x18\x05 \x01(\tR\x05taxId\x12/\n" +
	"\x13registration_number\x18\x06 \x01(\tR\x12registrationNumber\x124\n" +
	"\vtrader_type\x18\a \x01(\x0e2\x13.profile.TraderTypeR\n" +
	"traderType\x12\x18\n" +
	"\acountry\x18\b \x01(\tR\acountry\x12\x18\n" +
	"\aaddress\x18\t \x01(\tR\aaddress\x12\x14\n" +
	"\x05phone\x18\n" +
	" \x01(\tR\x05phone\x12#\n" +
	"\rcontact_email\x18\v \x01(\tR\fcontactEmail\x12.\n" +
	"\x06status\x18\f \x01(\x0e2\x16.profile.ProfileStatusR\x06status\x12\x15\n" +
	"\x06is_aeo\x18\r \x01(\bR\x05isAeo\x12'\n" +
	"\x0faeo_certificate\x18\x0e \x01(\tR\x0eaeoCertificate\x12)\n" +
	"\x10compliance_score\x18\x0f \x01(\x05R\x0fcomplianceScore\x12(\n" +
	"\x10reviewed_by_name\x18\x10 \x01(\tR\x0ereviewedByName\x12@\n" +
	"\x0eaeo_expires_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\faeoExpiresAt\x129\n" +
	"\n" +
	"created_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf7\x02\n" +
	"\x14CreateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12,\n" +
	"\x04role\x18\x02 \x01(\x0e2\x18.profile.StakeholderRoleR\x04role\x12+\n" +
	"\x11organization_name\x18\x03 \x01(\tR\x10organizationName\x12\x15\n" +
	"\x06tax_id\x18\x04 \x01(\tR\x05taxId\x12/\n" +
	"\x13registration_number\x18\x05 \x01(\tR\x12registrationNumber\x124\n" +
	"\vtrader_type\x18\x06 \x01(\x0e2\x13.profile.TraderTypeR\n" +
	"traderType\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x14\n" +
	"\x05phone\x18\t \x01(\tR\x05phone\x12#\n" +
	"\rcontact_email\x18\n" +
	" \x01(\tR\fcontactEmail\"K\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\x03R\tprofileId\"\xa2\x01\n" +
	"\x1aUpdateProfileStatusRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\x03R\tprofileId\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.profile.ProfileStatusR\x06status\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\x12\x1f\n" +
	"\vreviewer_id\x18\x04 \x01(\x03R\n" +
	"reviewerId\"\x9c\x01\n" +
	"\x13ListProfilesRequest\x12,\n" +
	"\x04role\x18\x01 \x01(\x0e2\x18.profile.StakeholderRoleR\x04role\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.profile.ProfileStatusR\x06status\x12'\n" +
	"\x04page\x18\x03 \x01(\v2\x13.common.PageRequestR\x04page\"u\n" +
	"\x14ListProfilesResponse\x127\n" +
	"\bprofiles\x18\x01 \x03(\v2\x1b.profile.StakeholderProfileR\bprofiles\x12$\n" +
	"\x04meta\x18\x02 \x01(\v2\x10.common.PageMetaR\x04meta\"\xab\x03\n" +
	"\x13OnboardingChecklist\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\x03R\tprofileId\x12+\n" +
	"\x11profile_submitted\x18\x02 \x01(\bR\x10profileSubmitted\x12)\n" +
	"\x10profile_approved\x18\x03 \x01(\bR\x0fprofileApproved\x12-\n" +
	"\x12documents_uploaded\x18\x04 \x01(\bR\x11documentsUploaded\x12&\n" +
	"\x0ftax_id_verified\x18\x05 \x01(\bR\rtaxIdVerified\x12.\n" +
	"\x13bank_account_linked\x18\x06 \x01(\bR\x11bankAccountLinked\x12-\n" +
	"\x12training_completed\x18\a \x01(\bR\x11trainingCompleted\x122\n" +
	"\x15system_access_granted\x18\b \x01(\bR\x13systemAccessGranted\x123\n" +
	"\x15completion_percentage\x18\t \x01(\x05R\x14completionPercentage*\x93\x01\n" +
	"\x0fStakeholderRole\x12 \n" +
	"\x1cSTAKEHOLDER_ROLE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06TRADER\x10\x01\x12\x13\n" +
	"\x0fCUSTOMS_OFFICER\x10\x02\x12\x0f\n" +
	"\vOGA_OFFICER\x10\x03\x12\t\n" +
	"\x05ADMIN\x10\x04\x12\x14\n" +
	"\x10SECURITY_ANALYST\x10\x05\x12\v\n" +
	"\aAUDITOR\x10\x06*n\n" +
	"\rProfileStatus\x12\x1e\n" +
	"\x1aPROFILE_STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePENDING_REVIEW\x10\x01\x12\f\n" +
	"\bAPPROVED\x10\x02\x12\r\n" +
	"\tSUSPENDED\x10\x03\x12\f\n" +
	"\bREJECTED\x10\x04*\x9b\x01\n" +
	"\n" +
	"TraderType\x12\x1b\n" +
	"\x17TRADER_TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bIMPORTER\x10\x01\x12\f\n" +
	"\bEXPORTER\x10\x02\x12\x12\n" +
	"\x0eCUSTOMS_BROKER\x10\x03\x12\x15\n" +
	"\x11FREIGHT_FORWARDER\x10\x04\x12\x16\n" +
	"\x12WAREHOUSE_OPERATOR\x10\x05\x12\x11\n" +
	"\rSHIPPING_LINE\x10\x062\xd2\x03\n" +
	"\x0eProfileService\x12K\n" +
	"\rCreateProfile\x12\x1d.profile.CreateProfileRequest\x1a\x1b.profile.StakeholderProfile\x12E\n" +
	"\n" +
	"GetProfile\x12\x1a.profile.GetProfileRequest\x1a\x1b.profile.StakeholderProfile\x12W\n" +
	"\x13UpdateProfileStatus\x12#.profile.UpdateProfileStatusRequest\x1a\x1b.profile.StakeholderProfile\x12K\n" +
	"\fListProfiles\x12\x1c.profile.ListProfilesRequest\x1a\x1d.profile.ListProfilesResponse\x12O\n" +
	"\x13GetOnboardingStatus\x12\x1a.profile.GetProfileRequest\x1a\x1c.profile.OnboardingChecklist\x125\n" +
	"\x06Health\x12\x13.common.PageRequest\x1a\x16.common.HealthResponseB\x1cZ\x1atradegateway/proto/profileb\x06proto3"

var (
	file_profile_profile_proto_rawDescOnce sync.Once
	file_profile_profile_proto_rawDescData []byte
)

func file_profile_profile_proto_rawDescGZIP() []byte {
	file_profile_profile_proto_rawDescOnce.Do(func() {
		file_profile_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_profile_proto_rawDesc), len(file_profile_profile_proto_rawDesc)))
	})
	return file_profile_profile_proto_rawDescData
}

var file_profile_profile_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_profile_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_profile_profile_proto_goTypes = []any{
	(StakeholderRole)(0),               // 0: profile.StakeholderRole
	(ProfileStatus)(0),                 // 1: profile.ProfileStatus
	(TraderType)(0),                    // 2: profile.TraderType
	(*StakeholderProfile)(nil),         // 3: profile.StakeholderProfile
	(*CreateProfileRequest)(nil),       // 4: profile.CreateProfileRequest
	(*GetProfileRequest)(nil),          // 5: profile.GetProfileRequest
	(*UpdateProfileStatusRequest)(nil), // 6: profile.UpdateProfileStatusRequest
	(*ListProfilesRequest)(nil),        // 7: profile.ListProfilesRequest
	(*ListProfilesResponse)(nil),       // 8: profile.ListProfilesResponse
	(*OnboardingChecklist)(nil),        // 9: profile.OnboardingChecklist
	(*timestamp.Timestamp)(nil),        // 10: google.protobuf.Timestamp
	(*common.PageRequest)(nil),         // 11: common.PageRequest
	(*common.PageMeta)(nil),            // 12: common.PageMeta
	(*common.HealthResponse)(nil),      // 13: common.HealthResponse
}
var file_profile_profile_proto_depIdxs = []int32{
	0,  // 0: profile.StakeholderProfile.role:type_name -> profile.StakeholderRole
	2,  // 1: profile.StakeholderProfile.trader_type:type_name -> profile.TraderType
	1,  // 2: profile.StakeholderProfile.status:type_name -> profile.ProfileStatus
	10, // 3: profile.StakeholderProfile.aeo_expires_at:type_name -> google.protobuf.Timestamp
	10, // 4: profile.StakeholderProfile.created_at:type_name -> google.protobuf.Timestamp
	10, // 5: profile.StakeholderProfile.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 6: profile.CreateProfileRequest.role:type_name -> profile.StakeholderRole
	2,  // 7: profile.CreateProfileRequest.trader_type:type_name -> profile.TraderType
	1,  // 8: profile.UpdateProfileStatusRequest.status:type_name -> profile.ProfileStatus
	0,  // 9: profile.ListProfilesRequest.role:type_name -> profile.StakeholderRole
	1,  // 10: profile.ListProfilesRequest.status:type_name -> profile.ProfileStatus
	11, // 11: profile.ListProfilesRequest.page:type_name -> common.PageRequest
	3,  // 12: profile.ListProfilesResponse.profiles:type_name -> profile.StakeholderProfile
	12, // 13: profile.ListProfilesResponse.meta:type_name -> common.PageMeta
	4,  // 14: profile.ProfileService.CreateProfile:input_type -> profile.CreateProfileRequest
	5,  // 15: profile.ProfileService.GetProfile:input_type -> profile.GetProfileRequest
	6,  // 16: profile.ProfileService.UpdateProfileStatus:input_type -> profile.UpdateProfileStatusRequest
	7,  // 17: profile.ProfileService.ListProfiles:input_type -> profile.ListProfilesRequest
	5,  // 18: profile.ProfileService.GetOnboardingStatus:input_type -> profile.GetProfileRequest
	11, // 19: profile.ProfileService.Health:input_type -> common.PageRequest
	3,  // 20: profile.ProfileService.CreateProfile:output_type -> profile.StakeholderProfile
	3,  // 21: profile.ProfileService.GetProfile:output_type -> profile.StakeholderProfile
	3,  // 22: profile.ProfileService.UpdateProfileStatus:output_type -> profile.StakeholderProfile
	8,  // 23: profile.ProfileService.ListProfiles:output_type -> profile.ListProfilesResponse
	9,  // 24: profile.ProfileService.GetOnboardingStatus:output_type -> profile.OnboardingChecklist
	13, // 25: profile.ProfileService.Health:output_type -> common.HealthResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_profile_profile_proto_init() }
func file_profile_profile_proto_init() {
	if File_profile_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_profile_proto_rawDesc), len(file_profile_profile_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profile_profile_proto_goTypes,
		DependencyIndexes: file_profile_profile_proto_depIdxs,
		EnumInfos:         file_profile_profile_proto_enumTypes,
		MessageInfos:      file_profile_profile_proto_msgTypes,
	}.Build()
	File_profile_profile_proto = out.File
	file_profile_profile_proto_goTypes = nil
	file_profile_profile_proto_depIdxs = nil
}
