// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.6
// source: cargo.proto

package cargov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CargoService_RegisterCargo_FullMethodName     = "/tradegateway.cargo.v1.CargoService/RegisterCargo"
	CargoService_UpdateCargoStatus_FullMethodName = "/tradegateway.cargo.v1.CargoService/UpdateCargoStatus"
	CargoService_GetCargo_FullMethodName          = "/tradegateway.cargo.v1.CargoService/GetCargo"
	CargoService_GetCargoByUCR_FullMethodName     = "/tradegateway.cargo.v1.CargoService/GetCargoByUCR"
	CargoService_ListCargoEvents_FullMethodName   = "/tradegateway.cargo.v1.CargoService/ListCargoEvents"
	CargoService_GetPortCongestion_FullMethodName = "/tradegateway.cargo.v1.CargoService/GetPortCongestion"
	CargoService_TrackShipment_FullMethodName     = "/tradegateway.cargo.v1.CargoService/TrackShipment"
)

// CargoServiceClient is the client API for CargoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CargoServiceClient interface {
	RegisterCargo(ctx context.Context, in *RegisterCargoRequest, opts ...grpc.CallOption) (*CargoResponse, error)
	UpdateCargoStatus(ctx context.Context, in *UpdateCargoStatusRequest, opts ...grpc.CallOption) (*CargoResponse, error)
	GetCargo(ctx context.Context, in *GetCargoRequest, opts ...grpc.CallOption) (*CargoResponse, error)
	GetCargoByUCR(ctx context.Context, in *GetCargoByUCRRequest, opts ...grpc.CallOption) (*CargoResponse, error)
	ListCargoEvents(ctx context.Context, in *ListCargoEventsRequest, opts ...grpc.CallOption) (*ListCargoEventsResponse, error)
	GetPortCongestion(ctx context.Context, in *PortCongestionRequest, opts ...grpc.CallOption) (*PortCongestionResponse, error)
	TrackShipment(ctx context.Context, in *TrackShipmentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CargoEvent], error)
}

type cargoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCargoServiceClient(cc grpc.ClientConnInterface) CargoServiceClient {
	return &cargoServiceClient{cc}
}

func (c *cargoServiceClient) RegisterCargo(ctx context.Context, in *RegisterCargoRequest, opts ...grpc.CallOption) (*CargoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CargoResponse)
	err := c.cc.Invoke(ctx, CargoService_RegisterCargo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cargoServiceClient) UpdateCargoStatus(ctx context.Context, in *UpdateCargoStatusRequest, opts ...grpc.CallOption) (*CargoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CargoResponse)
	err := c.cc.Invoke(ctx, CargoService_UpdateCargoStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cargoServiceClient) GetCargo(ctx context.Context, in *GetCargoRequest, opts ...grpc.CallOption) (*CargoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CargoResponse)
	err := c.cc.Invoke(ctx, CargoService_GetCargo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cargoServiceClient) GetCargoByUCR(ctx context.Context, in *GetCargoByUCRRequest, opts ...grpc.CallOption) (*CargoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CargoResponse)
	err := c.cc.Invoke(ctx, CargoService_GetCargoByUCR_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cargoServiceClient) ListCargoEvents(ctx context.Context, in *ListCargoEventsRequest, opts ...grpc.CallOption) (*ListCargoEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCargoEventsResponse)
	err := c.cc.Invoke(ctx, CargoService_ListCargoEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cargoServiceClient) GetPortCongestion(ctx context.Context, in *PortCongestionRequest, opts ...grpc.CallOption) (*PortCongestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PortCongestionResponse)
	err := c.cc.Invoke(ctx, CargoService_GetPortCongestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cargoServiceClient) TrackShipment(ctx context.Context, in *TrackShipmentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CargoEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CargoService_ServiceDesc.Streams[0], CargoService_TrackShipment_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TrackShipmentRequest, CargoEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CargoService_TrackShipmentClient = grpc.ServerStreamingClient[CargoEvent]

// CargoServiceServer is the server API for CargoService service.
// All implementations must embed UnimplementedCargoServiceServer
// for forward compatibility.
type CargoServiceServer interface {
	RegisterCargo(context.Context, *RegisterCargoRequest) (*CargoResponse, error)
	UpdateCargoStatus(context.Context, *UpdateCargoStatusRequest) (*CargoResponse, error)
	GetCargo(context.Context, *GetCargoRequest) (*CargoResponse, error)
	GetCargoByUCR(context.Context, *GetCargoByUCRRequest) (*CargoResponse, error)
	ListCargoEvents(context.Context, *ListCargoEventsRequest) (*ListCargoEventsResponse, error)
	GetPortCongestion(context.Context, *PortCongestionRequest) (*PortCongestionResponse, error)
	TrackShipment(*TrackShipmentRequest, grpc.ServerStreamingServer[CargoEvent]) error
	mustEmbedUnimplementedCargoServiceServer()
}

// UnimplementedCargoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCargoServiceServer struct{}

func (UnimplementedCargoServiceServer) RegisterCargo(context.Context, *RegisterCargoRequest) (*CargoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterCargo not implemented")
}
func (UnimplementedCargoServiceServer) UpdateCargoStatus(context.Context, *UpdateCargoStatusRequest) (*CargoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCargoStatus not implemented")
}
func (UnimplementedCargoServiceServer) GetCargo(context.Context, *GetCargoRequest) (*CargoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCargo not implemented")
}
func (UnimplementedCargoServiceServer) GetCargoByUCR(context.Context, *GetCargoByUCRRequest) (*CargoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCargoByUCR not implemented")
}
func (UnimplementedCargoServiceServer) ListCargoEvents(context.Context, *ListCargoEventsRequest) (*ListCargoEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCargoEvents not implemented")
}
func (UnimplementedCargoServiceServer) GetPortCongestion(context.Context, *PortCongestionRequest) (*PortCongestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPortCongestion not implemented")
}
func (UnimplementedCargoServiceServer) TrackShipment(*TrackShipmentRequest, grpc.ServerStreamingServer[CargoEvent]) error {
	return status.Errorf(codes.Unimplemented, "method TrackShipment not implemented")
}
func (UnimplementedCargoServiceServer) mustEmbedUnimplementedCargoServiceServer() {}
func (UnimplementedCargoServiceServer) testEmbeddedByValue()                      {}

// UnsafeCargoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CargoServiceServer will
// result in compilation errors.
type UnsafeCargoServiceServer interface {
	mustEmbedUnimplementedCargoServiceServer()
}

func RegisterCargoServiceServer(s grpc.ServiceRegistrar, srv CargoServiceServer) {
	// If the following call pancis, it indicates UnimplementedCargoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CargoService_ServiceDesc, srv)
}

func _CargoService_RegisterCargo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterCargoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CargoServiceServer).RegisterCargo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CargoService_RegisterCargo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CargoServiceServer).RegisterCargo(ctx, req.(*RegisterCargoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CargoService_UpdateCargoStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCargoStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CargoServiceServer).UpdateCargoStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CargoService_UpdateCargoStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CargoServiceServer).UpdateCargoStatus(ctx, req.(*UpdateCargoStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CargoService_GetCargo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCargoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CargoServiceServer).GetCargo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CargoService_GetCargo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CargoServiceServer).GetCargo(ctx, req.(*GetCargoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CargoService_GetCargoByUCR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCargoByUCRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CargoServiceServer).GetCargoByUCR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CargoService_GetCargoByUCR_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CargoServiceServer).GetCargoByUCR(ctx, req.(*GetCargoByUCRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CargoService_ListCargoEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCargoEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CargoServiceServer).ListCargoEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CargoService_ListCargoEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CargoServiceServer).ListCargoEvents(ctx, req.(*ListCargoEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CargoService_GetPortCongestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PortCongestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CargoServiceServer).GetPortCongestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CargoService_GetPortCongestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CargoServiceServer).GetPortCongestion(ctx, req.(*PortCongestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CargoService_TrackShipment_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TrackShipmentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CargoServiceServer).TrackShipment(m, &grpc.GenericServerStream[TrackShipmentRequest, CargoEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CargoService_TrackShipmentServer = grpc.ServerStreamingServer[CargoEvent]

// CargoService_ServiceDesc is the grpc.ServiceDesc for CargoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CargoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tradegateway.cargo.v1.CargoService",
	HandlerType: (*CargoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterCargo",
			Handler:    _CargoService_RegisterCargo_Handler,
		},
		{
			MethodName: "UpdateCargoStatus",
			Handler:    _CargoService_UpdateCargoStatus_Handler,
		},
		{
			MethodName: "GetCargo",
			Handler:    _CargoService_GetCargo_Handler,
		},
		{
			MethodName: "GetCargoByUCR",
			Handler:    _CargoService_GetCargoByUCR_Handler,
		},
		{
			MethodName: "ListCargoEvents",
			Handler:    _CargoService_ListCargoEvents_Handler,
		},
		{
			MethodName: "GetPortCongestion",
			Handler:    _CargoService_GetPortCongestion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TrackShipment",
			Handler:       _CargoService_TrackShipment_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cargo.proto",
}
