// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: ledger/ledger.proto

package ledger

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	common "tradegateway/proto/common"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountType int32

const (
	AccountType_ACCOUNT_TYPE_UNSPECIFIED AccountType = 0
	AccountType_TRADER_LIABILITY         AccountType = 1 // what trader owes
	AccountType_DUTY_REVENUE             AccountType = 2 // collected duties
	AccountType_VAT_REVENUE              AccountType = 3 // collected VAT
	AccountType_BOND_ACCOUNT             AccountType = 4 // customs bond
	AccountType_PENALTY_ACCOUNT          AccountType = 5 // fines
	AccountType_DRAWBACK_ACCOUNT         AccountType = 6 // duty drawback refunds
	AccountType_SUSPENSE                 AccountType = 7 // pending settlement
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "ACCOUNT_TYPE_UNSPECIFIED",
		1: "TRADER_LIABILITY",
		2: "DUTY_REVENUE",
		3: "VAT_REVENUE",
		4: "BOND_ACCOUNT",
		5: "PENALTY_ACCOUNT",
		6: "DRAWBACK_ACCOUNT",
		7: "SUSPENSE",
	}
	AccountType_value = map[string]int32{
		"ACCOUNT_TYPE_UNSPECIFIED": 0,
		"TRADER_LIABILITY":         1,
		"DUTY_REVENUE":             2,
		"VAT_REVENUE":              3,
		"BOND_ACCOUNT":             4,
		"PENALTY_ACCOUNT":          5,
		"DRAWBACK_ACCOUNT":         6,
		"SUSPENSE":                 7,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_ledger_ledger_proto_enumTypes[0].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_ledger_ledger_proto_enumTypes[0]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_ledger_ledger_proto_rawDescGZIP(), []int{0}
}

type TransferType int32

const (
	TransferType_TRANSFER_TYPE_UNSPECIFIED TransferType = 0
	TransferType_DUTY_ASSESSMENT           TransferType = 1
	TransferType_DUTY_PAYMENT              TransferType = 2
	TransferType_VAT_PAYMENT               TransferType = 3
	TransferType_BOND_DEPOSIT              TransferType = 4
	TransferType_BOND_RELEASE              TransferType = 5
	TransferType_PENALTY_LEVY              TransferType = 6
	TransferType_DUTY_DRAWBACK             TransferType = 7
	TransferType_REFUND                    TransferType = 8
)

// Enum value maps for TransferType.
var (
	TransferType_name = map[int32]string{
		0: "TRANSFER_TYPE_UNSPECIFIED",
		1: "DUTY_ASSESSMENT",
		2: "DUTY_PAYMENT",
		3: "VAT_PAYMENT",
		4: "BOND_DEPOSIT",
		5: "BOND_RELEASE",
		6: "PENALTY_LEVY",
		7: "DUTY_DRAWBACK",
		8: "REFUND",
	}
	TransferType_value = map[string]int32{
		"TRANSFER_TYPE_UNSPECIFIED": 0,
		"DUTY_ASSESSMENT":           1,
		"DUTY_PAYMENT":              2,
		"VAT_PAYMENT":               3,
		"BOND_DEPOSIT":              4,
		"BOND_RELEASE":              5,
		"PENALTY_LEVY":              6,
		"DUTY_DRAWBACK":             7,
		"REFUND":                    8,
	}
)

func (x TransferType) Enum() *TransferType {
	p := new(TransferType)
	*p = x
	return p
}

func (x TransferType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferType) Descriptor() protoreflect.EnumDescriptor {
	return file_ledger_ledger_proto_enumTypes[1].Descriptor()
}

func (TransferType) Type() protoreflect.EnumType {
	return &file_ledger_ledger_proto_enumTypes[1]
}

func (x TransferType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferType.Descriptor instead.
func (TransferType) EnumDescriptor() ([]byte, []int) {
	return file_ledger_ledger_proto_rawDescGZIP(), []int{1}
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          AccountType            `protobuf:"varint,2,opt,name=type,proto3,enum=ledger.AccountType" json:"type,omitempty"`
	TraderId      int64                  `protobuf:"varint,3,opt,name=trader_id,json=traderId,proto3" json:"trader_id,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	DebitsPosted  uint64                 `protobuf:"varint,5,opt,name=debits_posted,json=debitsPosted,proto3" json:"debits_posted,omitempty"`
	CreditsPosted uint64                 `protobuf:"varint,6,opt,name=credits_posted,json=creditsPosted,proto3" json:"credits_posted,omitempty"`
	Balance       uint64                 `protobuf:"varint,7,opt,name=balance,proto3" json:"balance,omitempty"` // credits - debits (in minor units)
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_ledger_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_ledger_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Account) GetType() AccountType {
	if x != nil {
		return x.Type
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *Account) GetTraderId() int64 {
	if x != nil {
		return x.TraderId
	}
	return 0
}

func (x *Account) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Account) GetDebitsPosted() uint64 {
	if x != nil {
		return x.DebitsPosted
	}
	return 0
}

func (x *Account) GetCreditsPosted() uint64 {
	if x != nil {
		return x.CreditsPosted
	}
	return 0
}

func (x *Account) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Account) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          AccountType            `protobuf:"varint,1,opt,name=type,proto3,enum=ledger.AccountType" json:"type,omitempty"`
	TraderId      int64                  `protobuf:"varint,2,opt,name=trader_id,json=traderId,proto3" json:"trader_id,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_ledger_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_ledger_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountRequest) GetType() AccountType {
	if x != nil {
		return x.Type
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *CreateAccountRequest) GetTraderId() int64 {
	if x != nil {
		return x.TraderId
	}
	return 0
}

func (x *CreateAccountRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type TransferRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DebitAccountId  uint64                 `protobuf:"varint,1,opt,name=debit_account_id,json=debitAccountId,proto3" json:"debit_account_id,omitempty"`
	CreditAccountId uint64                 `protobuf:"varint,2,opt,name=credit_account_id,json=creditAccountId,proto3" json:"credit_account_id,omitempty"`
	Amount          uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"` // minor units (cents)
	Currency        string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	TransferType    TransferType           `protobuf:"varint,5,opt,name=transfer_type,json=transferType,proto3,enum=ledger.TransferType" json:"transfer_type,omitempty"`
	DeclarationId   int64                  `protobuf:"varint,6,opt,name=declaration_id,json=declarationId,proto3" json:"declaration_id,omitempty"`
	Reference       string                 `protobuf:"bytes,7,opt,name=reference,proto3" json:"reference,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,8,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_ledger_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_ledger_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *TransferRequest) GetDebitAccountId() uint64 {
	if x != nil {
		return x.DebitAccountId
	}
	return 0
}

func (x *TransferRequest) GetCreditAccountId() uint64 {
	if x != nil {
		return x.CreditAccountId
	}
	return 0
}

func (x *TransferRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TransferRequest) GetTransferType() TransferType {
	if x != nil {
		return x.TransferType
	}
	return TransferType_TRANSFER_TYPE_UNSPECIFIED
}

func (x *TransferRequest) GetDeclarationId() int64 {
	if x != nil {
		return x.DeclarationId
	}
	return 0
}

func (x *TransferRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *TransferRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type TransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    uint64                 `protobuf:"varint,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_ledger_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_ledger_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *TransferResponse) GetTransferId() uint64 {
	if x != nil {
		return x.TransferId
	}
	return 0
}

func (x *TransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransferResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint64                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_ledger_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_ledger_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *GetAccountRequest) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraderId      int64                  `protobuf:"varint,1,opt,name=trader_id,json=traderId,proto3" json:"trader_id,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_ledger_ledger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_ledger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_ledger_ledger_proto_rawDescGZIP(), []int{5}
}

func (x *GetBalanceRequest) GetTraderId() int64 {
	if x != nil {
		return x.TraderId
	}
	return 0
}

func (x *GetBalanceRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type BalanceResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TraderId         int64                  `protobuf:"varint,1,opt,name=trader_id,json=traderId,proto3" json:"trader_id,omitempty"`
	LiabilityBalance uint64                 `protobuf:"varint,2,opt,name=liability_balance,json=liabilityBalance,proto3" json:"liability_balance,omitempty"`
	BondBalance      uint64                 `protobuf:"varint,3,opt,name=bond_balance,json=bondBalance,proto3" json:"bond_balance,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BalanceResponse) Reset() {
	*x = BalanceResponse{}
	mi := &file_ledger_ledger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResponse) ProtoMessage() {}

func (x *BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_ledger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResponse.ProtoReflect.Descriptor instead.
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return file_ledger_ledger_proto_rawDescGZIP(), []int{6}
}

func (x *BalanceResponse) GetTraderId() int64 {
	if x != nil {
		return x.TraderId
	}
	return 0
}

func (x *BalanceResponse) GetLiabilityBalance() uint64 {
	if x != nil {
		return x.LiabilityBalance
	}
	return 0
}

func (x *BalanceResponse) GetBondBalance() uint64 {
	if x != nil {
		return x.BondBalance
	}
	return 0
}

func (x *BalanceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type TransferHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeclarationId int64                  `protobuf:"varint,1,opt,name=declaration_id,json=declarationId,proto3" json:"declaration_id,omitempty"`
	TraderId      int64                  `protobuf:"varint,2,opt,name=trader_id,json=traderId,proto3" json:"trader_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferHistoryRequest) Reset() {
	*x = TransferHistoryRequest{}
	mi := &file_ledger_ledger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferHistoryRequest) ProtoMessage() {}

func (x *TransferHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_ledger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferHistoryRequest.ProtoReflect.Descriptor instead.
func (*TransferHistoryRequest) Descriptor() ([]byte, []int) {
	return file_ledger_ledger_proto_rawDescGZIP(), []int{7}
}

func (x *TransferHistoryRequest) GetDeclarationId() int64 {
	if x != nil {
		return x.DeclarationId
	}
	return 0
}

func (x *TransferHistoryRequest) GetTraderId() int64 {
	if x != nil {
		return x.TraderId
	}
	return 0
}

func (x *TransferHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Transfer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DebitAccountId  uint64                 `protobuf:"varint,2,opt,name=debit_account_id,json=debitAccountId,proto3" json:"debit_account_id,omitempty"`
	CreditAccountId uint64                 `protobuf:"varint,3,opt,name=credit_account_id,json=creditAccountId,proto3" json:"credit_account_id,omitempty"`
	Amount          uint64                 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	TransferType    TransferType           `protobuf:"varint,6,opt,name=transfer_type,json=transferType,proto3,enum=ledger.TransferType" json:"transfer_type,omitempty"`
	DeclarationId   int64                  `protobuf:"varint,7,opt,name=declaration_id,json=declarationId,proto3" json:"declaration_id,omitempty"`
	Reference       string                 `protobuf:"bytes,8,opt,name=reference,proto3" json:"reference,omitempty"`
	Timestamp       *timestamp.Timestamp   `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_ledger_ledger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_ledger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_ledger_ledger_proto_rawDescGZIP(), []int{8}
}

func (x *Transfer) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transfer) GetDebitAccountId() uint64 {
	if x != nil {
		return x.DebitAccountId
	}
	return 0
}

func (x *Transfer) GetCreditAccountId() uint64 {
	if x != nil {
		return x.CreditAccountId
	}
	return 0
}

func (x *Transfer) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transfer) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Transfer) GetTransferType() TransferType {
	if x != nil {
		return x.TransferType
	}
	return TransferType_TRANSFER_TYPE_UNSPECIFIED
}

func (x *Transfer) GetDeclarationId() int64 {
	if x != nil {
		return x.DeclarationId
	}
	return 0
}

func (x *Transfer) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *Transfer) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type TransferHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfers     []*Transfer            `protobuf:"bytes,1,rep,name=transfers,proto3" json:"transfers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferHistoryResponse) Reset() {
	*x = TransferHistoryResponse{}
	mi := &file_ledger_ledger_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferHistoryResponse) ProtoMessage() {}

func (x *TransferHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_ledger_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferHistoryResponse.ProtoReflect.Descriptor instead.
func (*TransferHistoryResponse) Descriptor() ([]byte, []int) {
	return file_ledger_ledger_proto_rawDescGZIP(), []int{9}
}

func (x *TransferHistoryResponse) GetTransfers() []*Transfer {
	if x != nil {
		return x.Transfers
	}
	return nil
}

var File_ledger_ledger_proto protoreflect.FileDescriptor

const file_ledger_ledger_proto_rawDesc = "" +
	"\n" +
	"\x13ledger/ledger.proto\x12\x06ledger\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\x9c\x02\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.ledger.AccountTypeR\x04type\x12\x1b\n" +
	"\ttrader_id\x18\x03 \x01(\x03R\btraderId\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12#\n" +
	"\rdebits_posted\x18\x05 \x01(\x04R\fdebitsPosted\x12%\n" +
	"\x0ecredits_posted\x18\x06 \x01(\x04R\rcreditsPosted\x12\x18\n" +
	"\abalance\x18\a \x01(\x04R\abalance\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"x\n" +
	"\x14CreateAccountRequest\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.ledger.AccountTypeR\x04type\x12\x1b\n" +
	"\ttrader_id\x18\x02 \x01(\x03R\btraderId\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"\xc4\x02\n" +
	"\x0fTransferRequest\x12(\n" +
	"\x10debit_account_id\x18\x01 \x01(\x04R\x0edebitAccountId\x12*\n" +
	"\x11credit_account_id\x18\x02 \x01(\x04R\x0fcreditAccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x129\n" +
	"\rtransfer_type\x18\x05 \x01(\x0e2\x14.ledger.TransferTypeR\ftransferType\x12%\n" +
	"\x0edeclaration_id\x18\x06 \x01(\x03R\rdeclarationId\x12\x1c\n" +
	"\treference\x18\a \x01(\tR\treference\x12'\n" +
	"\x0fidempotency_key\x18\b \x01(\tR\x0eidempotencyKey\"c\n" +
	"\x10TransferResponse\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\x04R\n" +
	"transferId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"2\n" +
	"\x11GetAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x04R\taccountId\"L\n" +
	"\x11GetBalanceRequest\x12\x1b\n" +
	"\ttrader_id\x18\x01 \x01(\x03R\btraderId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\x9a\x01\n" +
	"\x0fBalanceResponse\x12\x1b\n" +
	"\ttrader_id\x18\x01 \x01(\x03R\btraderId\x12+\n" +
	"\x11liability_balance\x18\x02 \x01(\x04R\x10liabilityBalance\x12!\n" +
	"\fbond_balance\x18\x03 \x01(\x04R\vbondBalance\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"r\n" +
	"\x16TransferHistoryRequest\x12%\n" +
	"\x0edeclaration_id\x18\x01 \x01(\x03R\rdeclarationId\x12\x1b\n" +
	"\ttrader_id\x18\x02 \x01(\x03R\btraderId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xde\x02\n" +
	"\bTransfer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12(\n" +
	"\x10debit_account_id\x18\x02 \x01(\x04R\x0edebitAccountId\x12*\n" +
	"\x11credit_account_id\x18\x03 \x01(\x04R\x0fcreditAccountId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x04R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x129\n" +
	"\rtransfer_type\x18\x06 \x01(\x0e2\x14.ledger.TransferTypeR\ftransferType\x12%\n" +
	"\x0edeclaration_id\x18\a \x01(\x03R\rdeclarationId\x12\x1c\n" +
	"\treference\x18\b \x01(\tR\treference\x128\n" +
	"\ttimestamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"I\n" +
	"\x17TransferHistoryResponse\x12.\n" +
	"\ttransfers\x18\x01 \x03(\v2\x10.ledger.TransferR\ttransfers*\xaf\x01\n" +
	"\vAccountType\x12\x1c\n" +
	"\x18ACCOUNT_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TRADER_LIABILITY\x10\x01\x12\x10\n" +
	"\fDUTY_REVENUE\x10\x02\x12\x0f\n" +
	"\vVAT_REVENUE\x10\x03\x12\x10\n" +
	"\fBOND_ACCOUNT\x10\x04\x12\x13\n" +
	"\x0fPENALTY_ACCOUNT\x10\x05\x12\x14\n" +
	"\x10DRAWBACK_ACCOUNT\x10\x06\x12\f\n" +
	"\bSUSPENSE\x10\a*\xba\x01\n" +
	"\fTransferType\x12\x1d\n" +
	"\x19TRANSFER_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fDUTY_ASSESSMENT\x10\x01\x12\x10\n" +
	"\fDUTY_PAYMENT\x10\x02\x12\x0f\n" +
	"\vVAT_PAYMENT\x10\x03\x12\x10\n" +
	"\fBOND_DEPOSIT\x10\x04\x12\x10\n" +
	"\fBOND_RELEASE\x10\x05\x12\x10\n" +
	"\fPENALTY_LEVY\x10\x06\x12\x11\n" +
	"\rDUTY_DRAWBACK\x10\a\x12\n" +
	"\n" +
	"\x06REFUND\x10\b2\x98\x03\n" +
	"\rLedgerService\x12>\n" +
	"\rCreateAccount\x12\x1c.ledger.CreateAccountRequest\x1a\x0f.ledger.Account\x128\n" +
	"\n" +
	"GetAccount\x12\x19.ledger.GetAccountRequest\x1a\x0f.ledger.Account\x12@\n" +
	"\n" +
	"GetBalance\x12\x19.ledger.GetBalanceRequest\x1a\x17.ledger.BalanceResponse\x12=\n" +
	"\bTransfer\x12\x17.ledger.TransferRequest\x1a\x18.ledger.TransferResponse\x12U\n" +
	"\x12GetTransferHistory\x12\x1e.ledger.TransferHistoryRequest\x1a\x1f.ledger.TransferHistoryResponse\x125\n" +
	"\x06Health\x12\x13.common.PageRequest\x1a\x16.common.HealthResponseB\x1bZ\x19tradegateway/proto/ledgerb\x06proto3"

var (
	file_ledger_ledger_proto_rawDescOnce sync.Once
	file_ledger_ledger_proto_rawDescData []byte
)

func file_ledger_ledger_proto_rawDescGZIP() []byte {
	file_ledger_ledger_proto_rawDescOnce.Do(func() {
		file_ledger_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ledger_ledger_proto_rawDesc), len(file_ledger_ledger_proto_rawDesc)))
	})
	return file_ledger_ledger_proto_rawDescData
}

var file_ledger_ledger_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ledger_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ledger_ledger_proto_goTypes = []any{
	(AccountType)(0),                // 0: ledger.AccountType
	(TransferType)(0),               // 1: ledger.TransferType
	(*Account)(nil),                 // 2: ledger.Account
	(*CreateAccountRequest)(nil),    // 3: ledger.CreateAccountRequest
	(*TransferRequest)(nil),         // 4: ledger.TransferRequest
	(*TransferResponse)(nil),        // 5: ledger.TransferResponse
	(*GetAccountRequest)(nil),       // 6: ledger.GetAccountRequest
	(*GetBalanceRequest)(nil),       // 7: ledger.GetBalanceRequest
	(*BalanceResponse)(nil),         // 8: ledger.BalanceResponse
	(*TransferHistoryRequest)(nil),  // 9: ledger.TransferHistoryRequest
	(*Transfer)(nil),                // 10: ledger.Transfer
	(*TransferHistoryResponse)(nil), // 11: ledger.TransferHistoryResponse
	(*timestamp.Timestamp)(nil),     // 12: google.protobuf.Timestamp
	(*common.PageRequest)(nil),      // 13: common.PageRequest
	(*common.HealthResponse)(nil),   // 14: common.HealthResponse
}
var file_ledger_ledger_proto_depIdxs = []int32{
	0,  // 0: ledger.Account.type:type_name -> ledger.AccountType
	12, // 1: ledger.Account.created_at:type_name -> google.protobuf.Timestamp
	0,  // 2: ledger.CreateAccountRequest.type:type_name -> ledger.AccountType
	1,  // 3: ledger.TransferRequest.transfer_type:type_name -> ledger.TransferType
	1,  // 4: ledger.Transfer.transfer_type:type_name -> ledger.TransferType
	12, // 5: ledger.Transfer.timestamp:type_name -> google.protobuf.Timestamp
	10, // 6: ledger.TransferHistoryResponse.transfers:type_name -> ledger.Transfer
	3,  // 7: ledger.LedgerService.CreateAccount:input_type -> ledger.CreateAccountRequest
	6,  // 8: ledger.LedgerService.GetAccount:input_type -> ledger.GetAccountRequest
	7,  // 9: ledger.LedgerService.GetBalance:input_type -> ledger.GetBalanceRequest
	4,  // 10: ledger.LedgerService.Transfer:input_type -> ledger.TransferRequest
	9,  // 11: ledger.LedgerService.GetTransferHistory:input_type -> ledger.TransferHistoryRequest
	13, // 12: ledger.LedgerService.Health:input_type -> common.PageRequest
	2,  // 13: ledger.LedgerService.CreateAccount:output_type -> ledger.Account
	2,  // 14: ledger.LedgerService.GetAccount:output_type -> ledger.Account
	8,  // 15: ledger.LedgerService.GetBalance:output_type -> ledger.BalanceResponse
	5,  // 16: ledger.LedgerService.Transfer:output_type -> ledger.TransferResponse
	11, // 17: ledger.LedgerService.GetTransferHistory:output_type -> ledger.TransferHistoryResponse
	14, // 18: ledger.LedgerService.Health:output_type -> common.HealthResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_ledger_ledger_proto_init() }
func file_ledger_ledger_proto_init() {
	if File_ledger_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ledger_ledger_proto_rawDesc), len(file_ledger_ledger_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ledger_ledger_proto_goTypes,
		DependencyIndexes: file_ledger_ledger_proto_depIdxs,
		EnumInfos:         file_ledger_ledger_proto_enumTypes,
		MessageInfos:      file_ledger_ledger_proto_msgTypes,
	}.Build()
	File_ledger_ledger_proto = out.File
	file_ledger_ledger_proto_goTypes = nil
	file_ledger_ledger_proto_depIdxs = nil
}
