// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: risk/risk.proto

package risk

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "tradegateway/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RiskEngine_ScoreDeclaration_FullMethodName = "/risk.RiskEngine/ScoreDeclaration"
	RiskEngine_BatchScore_FullMethodName       = "/risk.RiskEngine/BatchScore"
	RiskEngine_Health_FullMethodName           = "/risk.RiskEngine/Health"
)

// RiskEngineClient is the client API for RiskEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RiskEngineClient interface {
	ScoreDeclaration(ctx context.Context, in *RiskScoreRequest, opts ...grpc.CallOption) (*RiskScoreResponse, error)
	BatchScore(ctx context.Context, in *BatchRiskRequest, opts ...grpc.CallOption) (*BatchRiskResponse, error)
	Health(ctx context.Context, in *common.PageRequest, opts ...grpc.CallOption) (*common.HealthResponse, error)
}

type riskEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewRiskEngineClient(cc grpc.ClientConnInterface) RiskEngineClient {
	return &riskEngineClient{cc}
}

func (c *riskEngineClient) ScoreDeclaration(ctx context.Context, in *RiskScoreRequest, opts ...grpc.CallOption) (*RiskScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiskScoreResponse)
	err := c.cc.Invoke(ctx, RiskEngine_ScoreDeclaration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskEngineClient) BatchScore(ctx context.Context, in *BatchRiskRequest, opts ...grpc.CallOption) (*BatchRiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchRiskResponse)
	err := c.cc.Invoke(ctx, RiskEngine_BatchScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskEngineClient) Health(ctx context.Context, in *common.PageRequest, opts ...grpc.CallOption) (*common.HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.HealthResponse)
	err := c.cc.Invoke(ctx, RiskEngine_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiskEngineServer is the server API for RiskEngine service.
// All implementations must embed UnimplementedRiskEngineServer
// for forward compatibility.
type RiskEngineServer interface {
	ScoreDeclaration(context.Context, *RiskScoreRequest) (*RiskScoreResponse, error)
	BatchScore(context.Context, *BatchRiskRequest) (*BatchRiskResponse, error)
	Health(context.Context, *common.PageRequest) (*common.HealthResponse, error)
	mustEmbedUnimplementedRiskEngineServer()
}

// UnimplementedRiskEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRiskEngineServer struct{}

func (UnimplementedRiskEngineServer) ScoreDeclaration(context.Context, *RiskScoreRequest) (*RiskScoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScoreDeclaration not implemented")
}
func (UnimplementedRiskEngineServer) BatchScore(context.Context, *BatchRiskRequest) (*BatchRiskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchScore not implemented")
}
func (UnimplementedRiskEngineServer) Health(context.Context, *common.PageRequest) (*common.HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedRiskEngineServer) mustEmbedUnimplementedRiskEngineServer() {}
func (UnimplementedRiskEngineServer) testEmbeddedByValue()                    {}

// UnsafeRiskEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiskEngineServer will
// result in compilation errors.
type UnsafeRiskEngineServer interface {
	mustEmbedUnimplementedRiskEngineServer()
}

func RegisterRiskEngineServer(s grpc.ServiceRegistrar, srv RiskEngineServer) {
	// If the following call panics, it indicates UnimplementedRiskEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RiskEngine_ServiceDesc, srv)
}

func _RiskEngine_ScoreDeclaration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RiskScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskEngineServer).ScoreDeclaration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskEngine_ScoreDeclaration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskEngineServer).ScoreDeclaration(ctx, req.(*RiskScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskEngine_BatchScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskEngineServer).BatchScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskEngine_BatchScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskEngineServer).BatchScore(ctx, req.(*BatchRiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskEngine_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskEngineServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskEngine_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskEngineServer).Health(ctx, req.(*common.PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RiskEngine_ServiceDesc is the grpc.ServiceDesc for RiskEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RiskEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "risk.RiskEngine",
	HandlerType: (*RiskEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScoreDeclaration",
			Handler:    _RiskEngine_ScoreDeclaration_Handler,
		},
		{
			MethodName: "BatchScore",
			Handler:    _RiskEngine_BatchScore_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _RiskEngine_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "risk/risk.proto",
}
