// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: risk/risk.proto

package risk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	common "tradegateway/proto/common"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RiskLevel int32

const (
	RiskLevel_RISK_LEVEL_UNSPECIFIED RiskLevel = 0
	RiskLevel_LOW                    RiskLevel = 1
	RiskLevel_MEDIUM                 RiskLevel = 2
	RiskLevel_HIGH                   RiskLevel = 3
	RiskLevel_CRITICAL               RiskLevel = 4
)

// Enum value maps for RiskLevel.
var (
	RiskLevel_name = map[int32]string{
		0: "RISK_LEVEL_UNSPECIFIED",
		1: "LOW",
		2: "MEDIUM",
		3: "HIGH",
		4: "CRITICAL",
	}
	RiskLevel_value = map[string]int32{
		"RISK_LEVEL_UNSPECIFIED": 0,
		"LOW":                    1,
		"MEDIUM":                 2,
		"HIGH":                   3,
		"CRITICAL":               4,
	}
)

func (x RiskLevel) Enum() *RiskLevel {
	p := new(RiskLevel)
	*p = x
	return p
}

func (x RiskLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_risk_risk_proto_enumTypes[0].Descriptor()
}

func (RiskLevel) Type() protoreflect.EnumType {
	return &file_risk_risk_proto_enumTypes[0]
}

func (x RiskLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskLevel.Descriptor instead.
func (RiskLevel) EnumDescriptor() ([]byte, []int) {
	return file_risk_risk_proto_rawDescGZIP(), []int{0}
}

type RiskFactor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Contribution  float64                `protobuf:"fixed64,2,opt,name=contribution,proto3" json:"contribution,omitempty"` // 0.0 – 1.0 SHAP value
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Direction     string                 `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"` // "increases_risk" | "decreases_risk"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskFactor) Reset() {
	*x = RiskFactor{}
	mi := &file_risk_risk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskFactor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskFactor) ProtoMessage() {}

func (x *RiskFactor) ProtoReflect() protoreflect.Message {
	mi := &file_risk_risk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskFactor.ProtoReflect.Descriptor instead.
func (*RiskFactor) Descriptor() ([]byte, []int) {
	return file_risk_risk_proto_rawDescGZIP(), []int{0}
}

func (x *RiskFactor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RiskFactor) GetContribution() float64 {
	if x != nil {
		return x.Contribution
	}
	return 0
}

func (x *RiskFactor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RiskFactor) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

type RiskScoreRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DeclarationId       int64                  `protobuf:"varint,1,opt,name=declaration_id,json=declarationId,proto3" json:"declaration_id,omitempty"`
	TraderId            int64                  `protobuf:"varint,2,opt,name=trader_id,json=traderId,proto3" json:"trader_id,omitempty"`
	HsCode              string                 `protobuf:"bytes,3,opt,name=hs_code,json=hsCode,proto3" json:"hs_code,omitempty"`
	CountryOfOrigin     string                 `protobuf:"bytes,4,opt,name=country_of_origin,json=countryOfOrigin,proto3" json:"country_of_origin,omitempty"`
	CountryOfDest       string                 `protobuf:"bytes,5,opt,name=country_of_dest,json=countryOfDest,proto3" json:"country_of_dest,omitempty"`
	PortOfEntry         string                 `protobuf:"bytes,6,opt,name=port_of_entry,json=portOfEntry,proto3" json:"port_of_entry,omitempty"`
	InvoiceValueUsd     float64                `protobuf:"fixed64,7,opt,name=invoice_value_usd,json=invoiceValueUsd,proto3" json:"invoice_value_usd,omitempty"`
	GrossWeightKg       float64                `protobuf:"fixed64,8,opt,name=gross_weight_kg,json=grossWeightKg,proto3" json:"gross_weight_kg,omitempty"`
	NumPackages         int32                  `protobuf:"varint,9,opt,name=num_packages,json=numPackages,proto3" json:"num_packages,omitempty"`
	DeclarationType     string                 `protobuf:"bytes,10,opt,name=declaration_type,json=declarationType,proto3" json:"declaration_type,omitempty"`
	TraderIsAeo         bool                   `protobuf:"varint,11,opt,name=trader_is_aeo,json=traderIsAeo,proto3" json:"trader_is_aeo,omitempty"`
	TraderHistoryCount  int32                  `protobuf:"varint,12,opt,name=trader_history_count,json=traderHistoryCount,proto3" json:"trader_history_count,omitempty"`
	TraderViolationRate float64                `protobuf:"fixed64,13,opt,name=trader_violation_rate,json=traderViolationRate,proto3" json:"trader_violation_rate,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RiskScoreRequest) Reset() {
	*x = RiskScoreRequest{}
	mi := &file_risk_risk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskScoreRequest) ProtoMessage() {}

func (x *RiskScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_risk_risk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskScoreRequest.ProtoReflect.Descriptor instead.
func (*RiskScoreRequest) Descriptor() ([]byte, []int) {
	return file_risk_risk_proto_rawDescGZIP(), []int{1}
}

func (x *RiskScoreRequest) GetDeclarationId() int64 {
	if x != nil {
		return x.DeclarationId
	}
	return 0
}

func (x *RiskScoreRequest) GetTraderId() int64 {
	if x != nil {
		return x.TraderId
	}
	return 0
}

func (x *RiskScoreRequest) GetHsCode() string {
	if x != nil {
		return x.HsCode
	}
	return ""
}

func (x *RiskScoreRequest) GetCountryOfOrigin() string {
	if x != nil {
		return x.CountryOfOrigin
	}
	return ""
}

func (x *RiskScoreRequest) GetCountryOfDest() string {
	if x != nil {
		return x.CountryOfDest
	}
	return ""
}

func (x *RiskScoreRequest) GetPortOfEntry() string {
	if x != nil {
		return x.PortOfEntry
	}
	return ""
}

func (x *RiskScoreRequest) GetInvoiceValueUsd() float64 {
	if x != nil {
		return x.InvoiceValueUsd
	}
	return 0
}

func (x *RiskScoreRequest) GetGrossWeightKg() float64 {
	if x != nil {
		return x.GrossWeightKg
	}
	return 0
}

func (x *RiskScoreRequest) GetNumPackages() int32 {
	if x != nil {
		return x.NumPackages
	}
	return 0
}

func (x *RiskScoreRequest) GetDeclarationType() string {
	if x != nil {
		return x.DeclarationType
	}
	return ""
}

func (x *RiskScoreRequest) GetTraderIsAeo() bool {
	if x != nil {
		return x.TraderIsAeo
	}
	return false
}

func (x *RiskScoreRequest) GetTraderHistoryCount() int32 {
	if x != nil {
		return x.TraderHistoryCount
	}
	return 0
}

func (x *RiskScoreRequest) GetTraderViolationRate() float64 {
	if x != nil {
		return x.TraderViolationRate
	}
	return 0
}

type RiskScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         float64                `protobuf:"fixed64,1,opt,name=score,proto3" json:"score,omitempty"` // 0–100
	Lane          string                 `protobuf:"bytes,2,opt,name=lane,proto3" json:"lane,omitempty"`     // green|yellow|red|blue
	Level         RiskLevel              `protobuf:"varint,3,opt,name=level,proto3,enum=risk.RiskLevel" json:"level,omitempty"`
	Factors       []*RiskFactor          `protobuf:"bytes,4,rep,name=factors,proto3" json:"factors,omitempty"`
	Explanation   string                 `protobuf:"bytes,5,opt,name=explanation,proto3" json:"explanation,omitempty"`             // human-readable summary
	DutyRate      float64                `protobuf:"fixed64,6,opt,name=duty_rate,json=dutyRate,proto3" json:"duty_rate,omitempty"` // e.g. 0.10 = 10%
	VatRate       float64                `protobuf:"fixed64,7,opt,name=vat_rate,json=vatRate,proto3" json:"vat_rate,omitempty"`    // e.g. 0.15 = 15%
	DutyAmount    float64                `protobuf:"fixed64,8,opt,name=duty_amount,json=dutyAmount,proto3" json:"duty_amount,omitempty"`
	VatAmount     float64                `protobuf:"fixed64,9,opt,name=vat_amount,json=vatAmount,proto3" json:"vat_amount,omitempty"`
	TotalDue      float64                `protobuf:"fixed64,10,opt,name=total_due,json=totalDue,proto3" json:"total_due,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,11,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	GnnFlagged    bool                   `protobuf:"varint,12,opt,name=gnn_flagged,json=gnnFlagged,proto3" json:"gnn_flagged,omitempty"` // GNN fraud graph flag
	GnnScore      float64                `protobuf:"fixed64,13,opt,name=gnn_score,json=gnnScore,proto3" json:"gnn_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskScoreResponse) Reset() {
	*x = RiskScoreResponse{}
	mi := &file_risk_risk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskScoreResponse) ProtoMessage() {}

func (x *RiskScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_risk_risk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskScoreResponse.ProtoReflect.Descriptor instead.
func (*RiskScoreResponse) Descriptor() ([]byte, []int) {
	return file_risk_risk_proto_rawDescGZIP(), []int{2}
}

func (x *RiskScoreResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RiskScoreResponse) GetLane() string {
	if x != nil {
		return x.Lane
	}
	return ""
}

func (x *RiskScoreResponse) GetLevel() RiskLevel {
	if x != nil {
		return x.Level
	}
	return RiskLevel_RISK_LEVEL_UNSPECIFIED
}

func (x *RiskScoreResponse) GetFactors() []*RiskFactor {
	if x != nil {
		return x.Factors
	}
	return nil
}

func (x *RiskScoreResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *RiskScoreResponse) GetDutyRate() float64 {
	if x != nil {
		return x.DutyRate
	}
	return 0
}

func (x *RiskScoreResponse) GetVatRate() float64 {
	if x != nil {
		return x.VatRate
	}
	return 0
}

func (x *RiskScoreResponse) GetDutyAmount() float64 {
	if x != nil {
		return x.DutyAmount
	}
	return 0
}

func (x *RiskScoreResponse) GetVatAmount() float64 {
	if x != nil {
		return x.VatAmount
	}
	return 0
}

func (x *RiskScoreResponse) GetTotalDue() float64 {
	if x != nil {
		return x.TotalDue
	}
	return 0
}

func (x *RiskScoreResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *RiskScoreResponse) GetGnnFlagged() bool {
	if x != nil {
		return x.GnnFlagged
	}
	return false
}

func (x *RiskScoreResponse) GetGnnScore() float64 {
	if x != nil {
		return x.GnnScore
	}
	return 0
}

type BatchRiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*RiskScoreRequest    `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRiskRequest) Reset() {
	*x = BatchRiskRequest{}
	mi := &file_risk_risk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRiskRequest) ProtoMessage() {}

func (x *BatchRiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_risk_risk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRiskRequest.ProtoReflect.Descriptor instead.
func (*BatchRiskRequest) Descriptor() ([]byte, []int) {
	return file_risk_risk_proto_rawDescGZIP(), []int{3}
}

func (x *BatchRiskRequest) GetRequests() []*RiskScoreRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchRiskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*RiskScoreResponse   `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRiskResponse) Reset() {
	*x = BatchRiskResponse{}
	mi := &file_risk_risk_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRiskResponse) ProtoMessage() {}

func (x *BatchRiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_risk_risk_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRiskResponse.ProtoReflect.Descriptor instead.
func (*BatchRiskResponse) Descriptor() ([]byte, []int) {
	return file_risk_risk_proto_rawDescGZIP(), []int{4}
}

func (x *BatchRiskResponse) GetResponses() []*RiskScoreResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

var File_risk_risk_proto protoreflect.FileDescriptor

const file_risk_risk_proto_rawDesc = "" +
	"\n" +
	"\x0frisk/risk.proto\x12\x04risk\x1a\x13common/common.proto\"\x84\x01\n" +
	"\n" +
	"RiskFactor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\fcontribution\x18\x02 \x01(\x01R\fcontribution\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\"\x93\x04\n" +
	"\x10RiskScoreRequest\x12%\n" +
	"\x0edeclaration_id\x18\x01 \x01(\x03R\rdeclarationId\x12\x1b\n" +
	"\ttrader_id\x18\x02 \x01(\x03R\btraderId\x12\x17\n" +
	"\ahs_code\x18\x03 \x01(\tR\x06hsCode\x12*\n" +
	"\x11country_of_origin\x18\x04 \x01(\tR\x0fcountryOfOrigin\x12&\n" +
	"\x0fcountry_of_dest\x18\x05 \x01(\tR\rcountryOfDest\x12\"\n" +
	"\rport_of_entry\x18\x06 \x01(\tR\vportOfEntry\x12*\n" +
	"\x11invoice_value_usd\x18\a \x01(\x01R\x0finvoiceValueUsd\x12&\n" +
	"\x0fgross_weight_kg\x18\b \x01(\x01R\rgrossWeightKg\x12!\n" +
	"\fnum_packages\x18\t \x01(\x05R\vnumPackages\x12)\n" +
	"\x10declaration_type\x18\n" +
	" \x01(\tR\x0fdeclarationType\x12\"\n" +
	"\rtrader_is_aeo\x18\v \x01(\bR\vtraderIsAeo\x120\n" +
	"\x14trader_history_count\x18\f \x01(\x05R\x12traderHistoryCount\x122\n" +
	"\x15trader_violation_rate\x18\r \x01(\x01R\x13traderViolationRate\"\xaa\x03\n" +
	"\x11RiskScoreResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x01R\x05score\x12\x12\n" +
	"\x04lane\x18\x02 \x01(\tR\x04lane\x12%\n" +
	"\x05level\x18\x03 \x01(\x0e2\x0f.risk.RiskLevelR\x05level\x12*\n" +
	"\afactors\x18\x04 \x03(\v2\x10.risk.RiskFactorR\afactors\x12 \n" +
	"\vexplanation\x18\x05 \x01(\tR\vexplanation\x12\x1b\n" +
	"\tduty_rate\x18\x06 \x01(\x01R\bdutyRate\x12\x19\n" +
	"\bvat_rate\x18\a \x01(\x01R\avatRate\x12\x1f\n" +
	"\vduty_amount\x18\b \x01(\x01R\n" +
	"dutyAmount\x12\x1d\n" +
	"\n" +
	"vat_amount\x18\t \x01(\x01R\tvatAmount\x12\x1b\n" +
	"\ttotal_due\x18\n" +
	" \x01(\x01R\btotalDue\x12#\n" +
	"\rmodel_version\x18\v \x01(\tR\fmodelVersion\x12\x1f\n" +
	"\vgnn_flagged\x18\f \x01(\bR\n" +
	"gnnFlagged\x12\x1b\n" +
	"\tgnn_score\x18\r \x01(\x01R\bgnnScore\"F\n" +
	"\x10BatchRiskRequest\x122\n" +
	"\brequests\x18\x01 \x03(\v2\x16.risk.RiskScoreRequestR\brequests\"J\n" +
	"\x11BatchRiskResponse\x125\n" +
	"\tresponses\x18\x01 \x03(\v2\x17.risk.RiskScoreResponseR\tresponses*T\n" +
	"\tRiskLevel\x12\x1a\n" +
	"\x16RISK_LEVEL_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x02\x12\b\n" +
	"\x04HIGH\x10\x03\x12\f\n" +
	"\bCRITICAL\x10\x042\xc7\x01\n" +
	"\n" +
	"RiskEngine\x12C\n" +
	"\x10ScoreDeclaration\x12\x16.risk.RiskScoreRequest\x1a\x17.risk.RiskScoreResponse\x12=\n" +
	"\n" +
	"BatchScore\x12\x16.risk.BatchRiskRequest\x1a\x17.risk.BatchRiskResponse\x125\n" +
	"\x06Health\x12\x13.common.PageRequest\x1a\x16.common.HealthResponseB\x19Z\x17tradegateway/proto/riskb\x06proto3"

var (
	file_risk_risk_proto_rawDescOnce sync.Once
	file_risk_risk_proto_rawDescData []byte
)

func file_risk_risk_proto_rawDescGZIP() []byte {
	file_risk_risk_proto_rawDescOnce.Do(func() {
		file_risk_risk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_risk_risk_proto_rawDesc), len(file_risk_risk_proto_rawDesc)))
	})
	return file_risk_risk_proto_rawDescData
}

var file_risk_risk_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_risk_risk_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_risk_risk_proto_goTypes = []any{
	(RiskLevel)(0),                // 0: risk.RiskLevel
	(*RiskFactor)(nil),            // 1: risk.RiskFactor
	(*RiskScoreRequest)(nil),      // 2: risk.RiskScoreRequest
	(*RiskScoreResponse)(nil),     // 3: risk.RiskScoreResponse
	(*BatchRiskRequest)(nil),      // 4: risk.BatchRiskRequest
	(*BatchRiskResponse)(nil),     // 5: risk.BatchRiskResponse
	(*common.PageRequest)(nil),    // 6: common.PageRequest
	(*common.HealthResponse)(nil), // 7: common.HealthResponse
}
var file_risk_risk_proto_depIdxs = []int32{
	0, // 0: risk.RiskScoreResponse.level:type_name -> risk.RiskLevel
	1, // 1: risk.RiskScoreResponse.factors:type_name -> risk.RiskFactor
	2, // 2: risk.BatchRiskRequest.requests:type_name -> risk.RiskScoreRequest
	3, // 3: risk.BatchRiskResponse.responses:type_name -> risk.RiskScoreResponse
	2, // 4: risk.RiskEngine.ScoreDeclaration:input_type -> risk.RiskScoreRequest
	4, // 5: risk.RiskEngine.BatchScore:input_type -> risk.BatchRiskRequest
	6, // 6: risk.RiskEngine.Health:input_type -> common.PageRequest
	3, // 7: risk.RiskEngine.ScoreDeclaration:output_type -> risk.RiskScoreResponse
	5, // 8: risk.RiskEngine.BatchScore:output_type -> risk.BatchRiskResponse
	7, // 9: risk.RiskEngine.Health:output_type -> common.HealthResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_risk_risk_proto_init() }
func file_risk_risk_proto_init() {
	if File_risk_risk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_risk_risk_proto_rawDesc), len(file_risk_risk_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_risk_risk_proto_goTypes,
		DependencyIndexes: file_risk_risk_proto_depIdxs,
		EnumInfos:         file_risk_risk_proto_enumTypes,
		MessageInfos:      file_risk_risk_proto_msgTypes,
	}.Build()
	File_risk_risk_proto = out.File
	file_risk_risk_proto_goTypes = nil
	file_risk_risk_proto_depIdxs = nil
}
