// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: declaration/declaration.proto

package declaration

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	common "tradegateway/proto/common"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ─── ENUMS ───────────────────────────────────────────────────────────────────
type DeclarationType int32

const (
	DeclarationType_DECLARATION_TYPE_UNSPECIFIED DeclarationType = 0
	DeclarationType_IMPORT                       DeclarationType = 1
	DeclarationType_EXPORT                       DeclarationType = 2
	DeclarationType_TRANSIT                      DeclarationType = 3
	DeclarationType_REEXPORT                     DeclarationType = 4
	DeclarationType_BONDED                       DeclarationType = 5
)

// Enum value maps for DeclarationType.
var (
	DeclarationType_name = map[int32]string{
		0: "DECLARATION_TYPE_UNSPECIFIED",
		1: "IMPORT",
		2: "EXPORT",
		3: "TRANSIT",
		4: "REEXPORT",
		5: "BONDED",
	}
	DeclarationType_value = map[string]int32{
		"DECLARATION_TYPE_UNSPECIFIED": 0,
		"IMPORT":                       1,
		"EXPORT":                       2,
		"TRANSIT":                      3,
		"REEXPORT":                     4,
		"BONDED":                       5,
	}
)

func (x DeclarationType) Enum() *DeclarationType {
	p := new(DeclarationType)
	*p = x
	return p
}

func (x DeclarationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeclarationType) Descriptor() protoreflect.EnumDescriptor {
	return file_declaration_declaration_proto_enumTypes[0].Descriptor()
}

func (DeclarationType) Type() protoreflect.EnumType {
	return &file_declaration_declaration_proto_enumTypes[0]
}

func (x DeclarationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeclarationType.Descriptor instead.
func (DeclarationType) EnumDescriptor() ([]byte, []int) {
	return file_declaration_declaration_proto_rawDescGZIP(), []int{0}
}

type DeclarationStatus int32

const (
	DeclarationStatus_DECLARATION_STATUS_UNSPECIFIED DeclarationStatus = 0
	DeclarationStatus_DRAFT                          DeclarationStatus = 1
	DeclarationStatus_SUBMITTED                      DeclarationStatus = 2
	DeclarationStatus_UNDER_ASSESSMENT               DeclarationStatus = 3
	DeclarationStatus_DOCS_REQUIRED                  DeclarationStatus = 4
	DeclarationStatus_PAYMENT_PENDING                DeclarationStatus = 5
	DeclarationStatus_PAYMENT_CONFIRMED              DeclarationStatus = 6
	DeclarationStatus_UNDER_EXAMINATION              DeclarationStatus = 7
	DeclarationStatus_EXAMINATION_DONE               DeclarationStatus = 8
	DeclarationStatus_CLEARED                        DeclarationStatus = 9
	DeclarationStatus_REJECTED                       DeclarationStatus = 10
	DeclarationStatus_SUSPENDED                      DeclarationStatus = 11
)

// Enum value maps for DeclarationStatus.
var (
	DeclarationStatus_name = map[int32]string{
		0:  "DECLARATION_STATUS_UNSPECIFIED",
		1:  "DRAFT",
		2:  "SUBMITTED",
		3:  "UNDER_ASSESSMENT",
		4:  "DOCS_REQUIRED",
		5:  "PAYMENT_PENDING",
		6:  "PAYMENT_CONFIRMED",
		7:  "UNDER_EXAMINATION",
		8:  "EXAMINATION_DONE",
		9:  "CLEARED",
		10: "REJECTED",
		11: "SUSPENDED",
	}
	DeclarationStatus_value = map[string]int32{
		"DECLARATION_STATUS_UNSPECIFIED": 0,
		"DRAFT":                          1,
		"SUBMITTED":                      2,
		"UNDER_ASSESSMENT":               3,
		"DOCS_REQUIRED":                  4,
		"PAYMENT_PENDING":                5,
		"PAYMENT_CONFIRMED":              6,
		"UNDER_EXAMINATION":              7,
		"EXAMINATION_DONE":               8,
		"CLEARED":                        9,
		"REJECTED":                       10,
		"SUSPENDED":                      11,
	}
)

func (x DeclarationStatus) Enum() *DeclarationStatus {
	p := new(DeclarationStatus)
	*p = x
	return p
}

func (x DeclarationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeclarationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_declaration_declaration_proto_enumTypes[1].Descriptor()
}

func (DeclarationStatus) Type() protoreflect.EnumType {
	return &file_declaration_declaration_proto_enumTypes[1]
}

func (x DeclarationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeclarationStatus.Descriptor instead.
func (DeclarationStatus) EnumDescriptor() ([]byte, []int) {
	return file_declaration_declaration_proto_rawDescGZIP(), []int{1}
}

type RiskLane int32

const (
	RiskLane_RISK_LANE_UNSPECIFIED RiskLane = 0
	RiskLane_GREEN                 RiskLane = 1 // auto-clear
	RiskLane_YELLOW                RiskLane = 2 // doc review
	RiskLane_RED                   RiskLane = 3 // physical inspection
	RiskLane_BLUE                  RiskLane = 4 // AEO fast-track
)

// Enum value maps for RiskLane.
var (
	RiskLane_name = map[int32]string{
		0: "RISK_LANE_UNSPECIFIED",
		1: "GREEN",
		2: "YELLOW",
		3: "RED",
		4: "BLUE",
	}
	RiskLane_value = map[string]int32{
		"RISK_LANE_UNSPECIFIED": 0,
		"GREEN":                 1,
		"YELLOW":                2,
		"RED":                   3,
		"BLUE":                  4,
	}
)

func (x RiskLane) Enum() *RiskLane {
	p := new(RiskLane)
	*p = x
	return p
}

func (x RiskLane) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskLane) Descriptor() protoreflect.EnumDescriptor {
	return file_declaration_declaration_proto_enumTypes[2].Descriptor()
}

func (RiskLane) Type() protoreflect.EnumType {
	return &file_declaration_declaration_proto_enumTypes[2]
}

func (x RiskLane) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskLane.Descriptor instead.
func (RiskLane) EnumDescriptor() ([]byte, []int) {
	return file_declaration_declaration_proto_rawDescGZIP(), []int{2}
}

// ─── MESSAGES ────────────────────────────────────────────────────────────────
type Declaration struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DeclarationNumber string                 `protobuf:"bytes,2,opt,name=declaration_number,json=declarationNumber,proto3" json:"declaration_number,omitempty"`
	Ucr               string                 `protobuf:"bytes,3,opt,name=ucr,proto3" json:"ucr,omitempty"`
	TraderId          int64                  `protobuf:"varint,4,opt,name=trader_id,json=traderId,proto3" json:"trader_id,omitempty"`
	DeclarationType   DeclarationType        `protobuf:"varint,5,opt,name=declaration_type,json=declarationType,proto3,enum=declaration.DeclarationType" json:"declaration_type,omitempty"`
	Status            DeclarationStatus      `protobuf:"varint,6,opt,name=status,proto3,enum=declaration.DeclarationStatus" json:"status,omitempty"`
	HsCode            string                 `protobuf:"bytes,7,opt,name=hs_code,json=hsCode,proto3" json:"hs_code,omitempty"`
	GoodsDescription  string                 `protobuf:"bytes,8,opt,name=goods_description,json=goodsDescription,proto3" json:"goods_description,omitempty"`
	CountryOfOrigin   string                 `protobuf:"bytes,9,opt,name=country_of_origin,json=countryOfOrigin,proto3" json:"country_of_origin,omitempty"`
	CountryOfDest     string                 `protobuf:"bytes,10,opt,name=country_of_dest,json=countryOfDest,proto3" json:"country_of_dest,omitempty"`
	PortOfEntry       string                 `protobuf:"bytes,11,opt,name=port_of_entry,json=portOfEntry,proto3" json:"port_of_entry,omitempty"`
	GrossWeight       string                 `protobuf:"bytes,12,opt,name=gross_weight,json=grossWeight,proto3" json:"gross_weight,omitempty"`
	NetWeight         string                 `protobuf:"bytes,13,opt,name=net_weight,json=netWeight,proto3" json:"net_weight,omitempty"`
	NumberOfPackages  int32                  `protobuf:"varint,14,opt,name=number_of_packages,json=numberOfPackages,proto3" json:"number_of_packages,omitempty"`
	InvoiceValue      *common.Money          `protobuf:"bytes,15,opt,name=invoice_value,json=invoiceValue,proto3" json:"invoice_value,omitempty"`
	RiskScore         string                 `protobuf:"bytes,16,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	RiskLane          RiskLane               `protobuf:"varint,17,opt,name=risk_lane,json=riskLane,proto3,enum=declaration.RiskLane" json:"risk_lane,omitempty"`
	DutyAmount        *common.Money          `protobuf:"bytes,18,opt,name=duty_amount,json=dutyAmount,proto3" json:"duty_amount,omitempty"`
	VatAmount         *common.Money          `protobuf:"bytes,19,opt,name=vat_amount,json=vatAmount,proto3" json:"vat_amount,omitempty"`
	TotalDue          *common.Money          `protobuf:"bytes,20,opt,name=total_due,json=totalDue,proto3" json:"total_due,omitempty"`
	AiExplanation     string                 `protobuf:"bytes,21,opt,name=ai_explanation,json=aiExplanation,proto3" json:"ai_explanation,omitempty"` // JSON
	SubmittedAt       *timestamp.Timestamp   `protobuf:"bytes,22,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	ClearedAt         *timestamp.Timestamp   `protobuf:"bytes,23,opt,name=cleared_at,json=clearedAt,proto3" json:"cleared_at,omitempty"`
	CreatedAt         *timestamp.Timestamp   `protobuf:"bytes,24,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamp.Timestamp   `protobuf:"bytes,25,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Declaration) Reset() {
	*x = Declaration{}
	mi := &file_declaration_declaration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Declaration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Declaration) ProtoMessage() {}

func (x *Declaration) ProtoReflect() protoreflect.Message {
	mi := &file_declaration_declaration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Declaration.ProtoReflect.Descriptor instead.
func (*Declaration) Descriptor() ([]byte, []int) {
	return file_declaration_declaration_proto_rawDescGZIP(), []int{0}
}

func (x *Declaration) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Declaration) GetDeclarationNumber() string {
	if x != nil {
		return x.DeclarationNumber
	}
	return ""
}

func (x *Declaration) GetUcr() string {
	if x != nil {
		return x.Ucr
	}
	return ""
}

func (x *Declaration) GetTraderId() int64 {
	if x != nil {
		return x.TraderId
	}
	return 0
}

func (x *Declaration) GetDeclarationType() DeclarationType {
	if x != nil {
		return x.DeclarationType
	}
	return DeclarationType_DECLARATION_TYPE_UNSPECIFIED
}

func (x *Declaration) GetStatus() DeclarationStatus {
	if x != nil {
		return x.Status
	}
	return DeclarationStatus_DECLARATION_STATUS_UNSPECIFIED
}

func (x *Declaration) GetHsCode() string {
	if x != nil {
		return x.HsCode
	}
	return ""
}

func (x *Declaration) GetGoodsDescription() string {
	if x != nil {
		return x.GoodsDescription
	}
	return ""
}

func (x *Declaration) GetCountryOfOrigin() string {
	if x != nil {
		return x.CountryOfOrigin
	}
	return ""
}

func (x *Declaration) GetCountryOfDest() string {
	if x != nil {
		return x.CountryOfDest
	}
	return ""
}

func (x *Declaration) GetPortOfEntry() string {
	if x != nil {
		return x.PortOfEntry
	}
	return ""
}

func (x *Declaration) GetGrossWeight() string {
	if x != nil {
		return x.GrossWeight
	}
	return ""
}

func (x *Declaration) GetNetWeight() string {
	if x != nil {
		return x.NetWeight
	}
	return ""
}

func (x *Declaration) GetNumberOfPackages() int32 {
	if x != nil {
		return x.NumberOfPackages
	}
	return 0
}

func (x *Declaration) GetInvoiceValue() *common.Money {
	if x != nil {
		return x.InvoiceValue
	}
	return nil
}

func (x *Declaration) GetRiskScore() string {
	if x != nil {
		return x.RiskScore
	}
	return ""
}

func (x *Declaration) GetRiskLane() RiskLane {
	if x != nil {
		return x.RiskLane
	}
	return RiskLane_RISK_LANE_UNSPECIFIED
}

func (x *Declaration) GetDutyAmount() *common.Money {
	if x != nil {
		return x.DutyAmount
	}
	return nil
}

func (x *Declaration) GetVatAmount() *common.Money {
	if x != nil {
		return x.VatAmount
	}
	return nil
}

func (x *Declaration) GetTotalDue() *common.Money {
	if x != nil {
		return x.TotalDue
	}
	return nil
}

func (x *Declaration) GetAiExplanation() string {
	if x != nil {
		return x.AiExplanation
	}
	return ""
}

func (x *Declaration) GetSubmittedAt() *timestamp.Timestamp {
	if x != nil {
		return x.SubmittedAt
	}
	return nil
}

func (x *Declaration) GetClearedAt() *timestamp.Timestamp {
	if x != nil {
		return x.ClearedAt
	}
	return nil
}

func (x *Declaration) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Declaration) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DeclarationId int64                  `protobuf:"varint,2,opt,name=declaration_id,json=declarationId,proto3" json:"declaration_id,omitempty"`
	DocumentType  string                 `protobuf:"bytes,3,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"`
	FileName      string                 `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileUrl       string                 `protobuf:"bytes,5,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	FileKey       string                 `protobuf:"bytes,6,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty"`
	MimeType      string                 `protobuf:"bytes,7,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FileSize      int64                  `protobuf:"varint,8,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Verified      bool                   `protobuf:"varint,9,opt,name=verified,proto3" json:"verified,omitempty"`
	UploadedAt    *timestamp.Timestamp   `protobuf:"bytes,10,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_declaration_declaration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_declaration_declaration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_declaration_declaration_proto_rawDescGZIP(), []int{1}
}

func (x *Document) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Document) GetDeclarationId() int64 {
	if x != nil {
		return x.DeclarationId
	}
	return 0
}

func (x *Document) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *Document) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Document) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *Document) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

func (x *Document) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Document) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *Document) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *Document) GetUploadedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UploadedAt
	}
	return nil
}

// ─── REQUESTS / RESPONSES ────────────────────────────────────────────────────
type CreateDeclarationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TraderId         int64                  `protobuf:"varint,1,opt,name=trader_id,json=traderId,proto3" json:"trader_id,omitempty"`
	DeclarationType  DeclarationType        `protobuf:"varint,2,opt,name=declaration_type,json=declarationType,proto3,enum=declaration.DeclarationType" json:"declaration_type,omitempty"`
	HsCode           string                 `protobuf:"bytes,3,opt,name=hs_code,json=hsCode,proto3" json:"hs_code,omitempty"`
	GoodsDescription string                 `protobuf:"bytes,4,opt,name=goods_description,json=goodsDescription,proto3" json:"goods_description,omitempty"`
	CountryOfOrigin  string                 `protobuf:"bytes,5,opt,name=country_of_origin,json=countryOfOrigin,proto3" json:"country_of_origin,omitempty"`
	CountryOfDest    string                 `protobuf:"bytes,6,opt,name=country_of_dest,json=countryOfDest,proto3" json:"country_of_dest,omitempty"`
	PortOfEntry      string                 `protobuf:"bytes,7,opt,name=port_of_entry,json=portOfEntry,proto3" json:"port_of_entry,omitempty"`
	GrossWeight      string                 `protobuf:"bytes,8,opt,name=gross_weight,json=grossWeight,proto3" json:"gross_weight,omitempty"`
	NetWeight        string                 `protobuf:"bytes,9,opt,name=net_weight,json=netWeight,proto3" json:"net_weight,omitempty"`
	NumberOfPackages int32                  `protobuf:"varint,10,opt,name=number_of_packages,json=numberOfPackages,proto3" json:"number_of_packages,omitempty"`
	InvoiceValue     *common.Money          `protobuf:"bytes,11,opt,name=invoice_value,json=invoiceValue,proto3" json:"invoice_value,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateDeclarationRequest) Reset() {
	*x = CreateDeclarationRequest{}
	mi := &file_declaration_declaration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeclarationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeclarationRequest) ProtoMessage() {}

func (x *CreateDeclarationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_declaration_declaration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeclarationRequest.ProtoReflect.Descriptor instead.
func (*CreateDeclarationRequest) Descriptor() ([]byte, []int) {
	return file_declaration_declaration_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDeclarationRequest) GetTraderId() int64 {
	if x != nil {
		return x.TraderId
	}
	return 0
}

func (x *CreateDeclarationRequest) GetDeclarationType() DeclarationType {
	if x != nil {
		return x.DeclarationType
	}
	return DeclarationType_DECLARATION_TYPE_UNSPECIFIED
}

func (x *CreateDeclarationRequest) GetHsCode() string {
	if x != nil {
		return x.HsCode
	}
	return ""
}

func (x *CreateDeclarationRequest) GetGoodsDescription() string {
	if x != nil {
		return x.GoodsDescription
	}
	return ""
}

func (x *CreateDeclarationRequest) GetCountryOfOrigin() string {
	if x != nil {
		return x.CountryOfOrigin
	}
	return ""
}

func (x *CreateDeclarationRequest) GetCountryOfDest() string {
	if x != nil {
		return x.CountryOfDest
	}
	return ""
}

func (x *CreateDeclarationRequest) GetPortOfEntry() string {
	if x != nil {
		return x.PortOfEntry
	}
	return ""
}

func (x *CreateDeclarationRequest) GetGrossWeight() string {
	if x != nil {
		return x.GrossWeight
	}
	return ""
}

func (x *CreateDeclarationRequest) GetNetWeight() string {
	if x != nil {
		return x.NetWeight
	}
	return ""
}

func (x *CreateDeclarationRequest) GetNumberOfPackages() int32 {
	if x != nil {
		return x.NumberOfPackages
	}
	return 0
}

func (x *CreateDeclarationRequest) GetInvoiceValue() *common.Money {
	if x != nil {
		return x.InvoiceValue
	}
	return nil
}

type GetDeclarationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeclarationRequest) Reset() {
	*x = GetDeclarationRequest{}
	mi := &file_declaration_declaration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeclarationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeclarationRequest) ProtoMessage() {}

func (x *GetDeclarationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_declaration_declaration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeclarationRequest.ProtoReflect.Descriptor instead.
func (*GetDeclarationRequest) Descriptor() ([]byte, []int) {
	return file_declaration_declaration_proto_rawDescGZIP(), []int{3}
}

func (x *GetDeclarationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListDeclarationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraderId      int64                  `protobuf:"varint,1,opt,name=trader_id,json=traderId,proto3" json:"trader_id,omitempty"`                // 0 = all (admin)
	Status        DeclarationStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=declaration.DeclarationStatus" json:"status,omitempty"` // 0 = all
	Page          *common.PageRequest    `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeclarationsRequest) Reset() {
	*x = ListDeclarationsRequest{}
	mi := &file_declaration_declaration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeclarationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeclarationsRequest) ProtoMessage() {}

func (x *ListDeclarationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_declaration_declaration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeclarationsRequest.ProtoReflect.Descriptor instead.
func (*ListDeclarationsRequest) Descriptor() ([]byte, []int) {
	return file_declaration_declaration_proto_rawDescGZIP(), []int{4}
}

func (x *ListDeclarationsRequest) GetTraderId() int64 {
	if x != nil {
		return x.TraderId
	}
	return 0
}

func (x *ListDeclarationsRequest) GetStatus() DeclarationStatus {
	if x != nil {
		return x.Status
	}
	return DeclarationStatus_DECLARATION_STATUS_UNSPECIFIED
}

func (x *ListDeclarationsRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListDeclarationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Declarations  []*Declaration         `protobuf:"bytes,1,rep,name=declarations,proto3" json:"declarations,omitempty"`
	Meta          *common.PageMeta       `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeclarationsResponse) Reset() {
	*x = ListDeclarationsResponse{}
	mi := &file_declaration_declaration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeclarationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeclarationsResponse) ProtoMessage() {}

func (x *ListDeclarationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_declaration_declaration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeclarationsResponse.ProtoReflect.Descriptor instead.
func (*ListDeclarationsResponse) Descriptor() ([]byte, []int) {
	return file_declaration_declaration_proto_rawDescGZIP(), []int{5}
}

func (x *ListDeclarationsResponse) GetDeclarations() []*Declaration {
	if x != nil {
		return x.Declarations
	}
	return nil
}

func (x *ListDeclarationsResponse) GetMeta() *common.PageMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type SubmitDeclarationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitDeclarationRequest) Reset() {
	*x = SubmitDeclarationRequest{}
	mi := &file_declaration_declaration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDeclarationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDeclarationRequest) ProtoMessage() {}

func (x *SubmitDeclarationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_declaration_declaration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDeclarationRequest.ProtoReflect.Descriptor instead.
func (*SubmitDeclarationRequest) Descriptor() ([]byte, []int) {
	return file_declaration_declaration_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitDeclarationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        DeclarationStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=declaration.DeclarationStatus" json:"status,omitempty"`
	Notes         string                 `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	ActorId       int64                  `protobuf:"varint,4,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_declaration_declaration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_declaration_declaration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_declaration_declaration_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateStatusRequest) GetStatus() DeclarationStatus {
	if x != nil {
		return x.Status
	}
	return DeclarationStatus_DECLARATION_STATUS_UNSPECIFIED
}

func (x *UpdateStatusRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *UpdateStatusRequest) GetActorId() int64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

type AttachDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeclarationId int64                  `protobuf:"varint,1,opt,name=declaration_id,json=declarationId,proto3" json:"declaration_id,omitempty"`
	DocumentType  string                 `protobuf:"bytes,2,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileUrl       string                 `protobuf:"bytes,4,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	FileKey       string                 `protobuf:"bytes,5,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty"`
	MimeType      string                 `protobuf:"bytes,6,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FileSize      int64                  `protobuf:"varint,7,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachDocumentRequest) Reset() {
	*x = AttachDocumentRequest{}
	mi := &file_declaration_declaration_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachDocumentRequest) ProtoMessage() {}

func (x *AttachDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_declaration_declaration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachDocumentRequest.ProtoReflect.Descriptor instead.
func (*AttachDocumentRequest) Descriptor() ([]byte, []int) {
	return file_declaration_declaration_proto_rawDescGZIP(), []int{8}
}

func (x *AttachDocumentRequest) GetDeclarationId() int64 {
	if x != nil {
		return x.DeclarationId
	}
	return 0
}

func (x *AttachDocumentRequest) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *AttachDocumentRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *AttachDocumentRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *AttachDocumentRequest) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

func (x *AttachDocumentRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *AttachDocumentRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type GetDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeclarationId int64                  `protobuf:"varint,1,opt,name=declaration_id,json=declarationId,proto3" json:"declaration_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentsRequest) Reset() {
	*x = GetDocumentsRequest{}
	mi := &file_declaration_declaration_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentsRequest) ProtoMessage() {}

func (x *GetDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_declaration_declaration_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentsRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_declaration_declaration_proto_rawDescGZIP(), []int{9}
}

func (x *GetDocumentsRequest) GetDeclarationId() int64 {
	if x != nil {
		return x.DeclarationId
	}
	return 0
}

type GetDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentsResponse) Reset() {
	*x = GetDocumentsResponse{}
	mi := &file_declaration_declaration_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentsResponse) ProtoMessage() {}

func (x *GetDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_declaration_declaration_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentsResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_declaration_declaration_proto_rawDescGZIP(), []int{10}
}

func (x *GetDocumentsResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

type DeclarationStatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Total           int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Draft           int64                  `protobuf:"varint,2,opt,name=draft,proto3" json:"draft,omitempty"`
	UnderAssessment int64                  `protobuf:"varint,3,opt,name=under_assessment,json=underAssessment,proto3" json:"under_assessment,omitempty"`
	PaymentPending  int64                  `protobuf:"varint,4,opt,name=payment_pending,json=paymentPending,proto3" json:"payment_pending,omitempty"`
	Cleared         int64                  `protobuf:"varint,5,opt,name=cleared,proto3" json:"cleared,omitempty"`
	Rejected        int64                  `protobuf:"varint,6,opt,name=rejected,proto3" json:"rejected,omitempty"`
	GreenLane       int64                  `protobuf:"varint,7,opt,name=green_lane,json=greenLane,proto3" json:"green_lane,omitempty"`
	YellowLane      int64                  `protobuf:"varint,8,opt,name=yellow_lane,json=yellowLane,proto3" json:"yellow_lane,omitempty"`
	RedLane         int64                  `protobuf:"varint,9,opt,name=red_lane,json=redLane,proto3" json:"red_lane,omitempty"`
	BlueLane        int64                  `protobuf:"varint,10,opt,name=blue_lane,json=blueLane,proto3" json:"blue_lane,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeclarationStatsResponse) Reset() {
	*x = DeclarationStatsResponse{}
	mi := &file_declaration_declaration_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclarationStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclarationStatsResponse) ProtoMessage() {}

func (x *DeclarationStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_declaration_declaration_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclarationStatsResponse.ProtoReflect.Descriptor instead.
func (*DeclarationStatsResponse) Descriptor() ([]byte, []int) {
	return file_declaration_declaration_proto_rawDescGZIP(), []int{11}
}

func (x *DeclarationStatsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DeclarationStatsResponse) GetDraft() int64 {
	if x != nil {
		return x.Draft
	}
	return 0
}

func (x *DeclarationStatsResponse) GetUnderAssessment() int64 {
	if x != nil {
		return x.UnderAssessment
	}
	return 0
}

func (x *DeclarationStatsResponse) GetPaymentPending() int64 {
	if x != nil {
		return x.PaymentPending
	}
	return 0
}

func (x *DeclarationStatsResponse) GetCleared() int64 {
	if x != nil {
		return x.Cleared
	}
	return 0
}

func (x *DeclarationStatsResponse) GetRejected() int64 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

func (x *DeclarationStatsResponse) GetGreenLane() int64 {
	if x != nil {
		return x.GreenLane
	}
	return 0
}

func (x *DeclarationStatsResponse) GetYellowLane() int64 {
	if x != nil {
		return x.YellowLane
	}
	return 0
}

func (x *DeclarationStatsResponse) GetRedLane() int64 {
	if x != nil {
		return x.RedLane
	}
	return 0
}

func (x *DeclarationStatsResponse) GetBlueLane() int64 {
	if x != nil {
		return x.BlueLane
	}
	return 0
}

var File_declaration_declaration_proto protoreflect.FileDescriptor

const file_declaration_declaration_proto_rawDesc = "" +
	"\n" +
	"\x1ddeclaration/declaration.proto\x12\vdeclaration\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\xd2\b\n" +
	"\vDeclaration\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12-\n" +
	"\x12declaration_number\x18\x02 \x01(\tR\x11declarationNumber\x12\x10\n" +
	"\x03ucr\x18\x03 \x01(\tR\x03ucr\x12\x1b\n" +
	"\ttrader_id\x18\x04 \x01(\x03R\btraderId\x12G\n" +
	"\x10declaration_type\x18\x05 \x01(\x0e2\x1c.declaration.DeclarationTypeR\x0fdeclarationType\x126\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1e.declaration.DeclarationStatusR\x06status\x12\x17\n" +
	"\ahs_code\x18\a \x01(\tR\x06hsCode\x12+\n" +
	"\x11goods_description\x18\b \x01(\tR\x10goodsDescription\x12*\n" +
	"\x11country_of_origin\x18\t \x01(\tR\x0fcountryOfOrigin\x12&\n" +
	"\x0fcountry_of_dest\x18\n" +
	" \x01(\tR\rcountryOfDest\x12\"\n" +
	"\rport_of_entry\x18\v \x01(\tR\vportOfEntry\x12!\n" +
	"\fgross_weight\x18\f \x01(\tR\vgrossWeight\x12\x1d\n" +
	"\n" +
	"net_weight\x18\r \x01(\tR\tnetWeight\x12,\n" +
	"\x12number_of_packages\x18\x0e \x01(\x05R\x10numberOfPackages\x122\n" +
	"\rinvoice_value\x18\x0f \x01(\v2\r.common.MoneyR\finvoiceValue\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x10 \x01(\tR\triskScore\x122\n" +
	"\trisk_lane\x18\x11 \x01(\x0e2\x15.declaration.RiskLaneR\briskLane\x12.\n" +
	"\vduty_amount\x18\x12 \x01(\v2\r.common.MoneyR\n" +
	"dutyAmount\x12,\n" +
	"\n" +
	"vat_amount\x18\x13 \x01(\v2\r.common.MoneyR\tvatAmount\x12*\n" +
	"\ttotal_due\x18\x14 \x01(\v2\r.common.MoneyR\btotalDue\x12%\n" +
	"\x0eai_explanation\x18\x15 \x01(\tR\raiExplanation\x12=\n" +
	"\fsubmitted_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\vsubmittedAt\x129\n" +
	"\n" +
	"cleared_at\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampR\tclearedAt\x129\n" +
	"\n" +
	"created_at\x18\x18 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x19 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xcc\x02\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\x0edeclaration_id\x18\x02 \x01(\x03R\rdeclarationId\x12#\n" +
	"\rdocument_type\x18\x03 \x01(\tR\fdocumentType\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\x12\x19\n" +
	"\bfile_url\x18\x05 \x01(\tR\afileUrl\x12\x19\n" +
	"\bfile_key\x18\x06 \x01(\tR\afileKey\x12\x1b\n" +
	"\tmime_type\x18\a \x01(\tR\bmimeType\x12\x1b\n" +
	"\tfile_size\x18\b \x01(\x03R\bfileSize\x12\x1a\n" +
	"\bverified\x18\t \x01(\bR\bverified\x12;\n" +
	"\vuploaded_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"uploadedAt\"\xe2\x03\n" +
	"\x18CreateDeclarationRequest\x12\x1b\n" +
	"\ttrader_id\x18\x01 \x01(\x03R\btraderId\x12G\n" +
	"\x10declaration_type\x18\x02 \x01(\x0e2\x1c.declaration.DeclarationTypeR\x0fdeclarationType\x12\x17\n" +
	"\ahs_code\x18\x03 \x01(\tR\x06hsCode\x12+\n" +
	"\x11goods_description\x18\x04 \x01(\tR\x10goodsDescription\x12*\n" +
	"\x11country_of_origin\x18\x05 \x01(\tR\x0fcountryOfOrigin\x12&\n" +
	"\x0fcountry_of_dest\x18\x06 \x01(\tR\rcountryOfDest\x12\"\n" +
	"\rport_of_entry\x18\a \x01(\tR\vportOfEntry\x12!\n" +
	"\fgross_weight\x18\b \x01(\tR\vgrossWeight\x12\x1d\n" +
	"\n" +
	"net_weight\x18\t \x01(\tR\tnetWeight\x12,\n" +
	"\x12number_of_packages\x18\n" +
	" \x01(\x05R\x10numberOfPackages\x122\n" +
	"\rinvoice_value\x18\v \x01(\v2\r.common.MoneyR\finvoiceValue\"'\n" +
	"\x15GetDeclarationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x97\x01\n" +
	"\x17ListDeclarationsRequest\x12\x1b\n" +
	"\ttrader_id\x18\x01 \x01(\x03R\btraderId\x126\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1e.declaration.DeclarationStatusR\x06status\x12'\n" +
	"\x04page\x18\x03 \x01(\v2\x13.common.PageRequestR\x04page\"~\n" +
	"\x18ListDeclarationsResponse\x12<\n" +
	"\fdeclarations\x18\x01 \x03(\v2\x18.declaration.DeclarationR\fdeclarations\x12$\n" +
	"\x04meta\x18\x02 \x01(\v2\x10.common.PageMetaR\x04meta\"*\n" +
	"\x18SubmitDeclarationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x8e\x01\n" +
	"\x13UpdateStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x126\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1e.declaration.DeclarationStatusR\x06status\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\x12\x19\n" +
	"\bactor_id\x18\x04 \x01(\x03R\aactorId\"\xf0\x01\n" +
	"\x15AttachDocumentRequest\x12%\n" +
	"\x0edeclaration_id\x18\x01 \x01(\x03R\rdeclarationId\x12#\n" +
	"\rdocument_type\x18\x02 \x01(\tR\fdocumentType\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x19\n" +
	"\bfile_url\x18\x04 \x01(\tR\afileUrl\x12\x19\n" +
	"\bfile_key\x18\x05 \x01(\tR\afileKey\x12\x1b\n" +
	"\tmime_type\x18\x06 \x01(\tR\bmimeType\x12\x1b\n" +
	"\tfile_size\x18\a \x01(\x03R\bfileSize\"<\n" +
	"\x13GetDocumentsRequest\x12%\n" +
	"\x0edeclaration_id\x18\x01 \x01(\x03R\rdeclarationId\"K\n" +
	"\x14GetDocumentsResponse\x123\n" +
	"\tdocuments\x18\x01 \x03(\v2\x15.declaration.DocumentR\tdocuments\"\xc8\x02\n" +
	"\x18DeclarationStatsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x14\n" +
	"\x05draft\x18\x02 \x01(\x03R\x05draft\x12)\n" +
	"\x10under_assessment\x18\x03 \x01(\x03R\x0funderAssessment\x12'\n" +
	"\x0fpayment_pending\x18\x04 \x01(\x03R\x0epaymentPending\x12\x18\n" +
	"\acleared\x18\x05 \x01(\x03R\acleared\x12\x1a\n" +
	"\brejected\x18\x06 \x01(\x03R\brejected\x12\x1d\n" +
	"\n" +
	"green_lane\x18\a \x01(\x03R\tgreenLane\x12\x1f\n" +
	"\vyellow_lane\x18\b \x01(\x03R\n" +
	"yellowLane\x12\x19\n" +
	"\bred_lane\x18\t \x01(\x03R\aredLane\x12\x1b\n" +
	"\tblue_lane\x18\n" +
	" \x01(\x03R\bblueLane*r\n" +
	"\x0fDeclarationType\x12 \n" +
	"\x1cDECLARATION_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06IMPORT\x10\x01\x12\n" +
	"\n" +
	"\x06EXPORT\x10\x02\x12\v\n" +
	"\aTRANSIT\x10\x03\x12\f\n" +
	"\bREEXPORT\x10\x04\x12\n" +
	"\n" +
	"\x06BONDED\x10\x05*\xfd\x01\n" +
	"\x11DeclarationStatus\x12\"\n" +
	"\x1eDECLARATION_STATUS_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05DRAFT\x10\x01\x12\r\n" +
	"\tSUBMITTED\x10\x02\x12\x14\n" +
	"\x10UNDER_ASSESSMENT\x10\x03\x12\x11\n" +
	"\rDOCS_REQUIRED\x10\x04\x12\x13\n" +
	"\x0fPAYMENT_PENDING\x10\x05\x12\x15\n" +
	"\x11PAYMENT_CONFIRMED\x10\x06\x12\x15\n" +
	"\x11UNDER_EXAMINATION\x10\a\x12\x14\n" +
	"\x10EXAMINATION_DONE\x10\b\x12\v\n" +
	"\aCLEARED\x10\t\x12\f\n" +
	"\bREJECTED\x10\n" +
	"\x12\r\n" +
	"\tSUSPENDED\x10\v*O\n" +
	"\bRiskLane\x12\x19\n" +
	"\x15RISK_LANE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05GREEN\x10\x01\x12\n" +
	"\n" +
	"\x06YELLOW\x10\x02\x12\a\n" +
	"\x03RED\x10\x03\x12\b\n" +
	"\x04BLUE\x10\x042\xde\x05\n" +
	"\x12DeclarationService\x12T\n" +
	"\x11CreateDeclaration\x12%.declaration.CreateDeclarationRequest\x1a\x18.declaration.Declaration\x12N\n" +
	"\x0eGetDeclaration\x12\".declaration.GetDeclarationRequest\x1a\x18.declaration.Declaration\x12_\n" +
	"\x10ListDeclarations\x12$.declaration.ListDeclarationsRequest\x1a%.declaration.ListDeclarationsResponse\x12T\n" +
	"\x11SubmitDeclaration\x12%.declaration.SubmitDeclarationRequest\x1a\x18.declaration.Declaration\x12J\n" +
	"\fUpdateStatus\x12 .declaration.UpdateStatusRequest\x1a\x18.declaration.Declaration\x12K\n" +
	"\x0eAttachDocument\x12\".declaration.AttachDocumentRequest\x1a\x15.declaration.Document\x12S\n" +
	"\fGetDocuments\x12 .declaration.GetDocumentsRequest\x1a!.declaration.GetDocumentsResponse\x12F\n" +
	"\bGetStats\x12\x13.common.PageRequest\x1a%.declaration.DeclarationStatsResponse\x125\n" +
	"\x06Health\x12\x13.common.PageRequest\x1a\x16.common.HealthResponseB Z\x1etradegateway/proto/declarationb\x06proto3"

var (
	file_declaration_declaration_proto_rawDescOnce sync.Once
	file_declaration_declaration_proto_rawDescData []byte
)

func file_declaration_declaration_proto_rawDescGZIP() []byte {
	file_declaration_declaration_proto_rawDescOnce.Do(func() {
		file_declaration_declaration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_declaration_declaration_proto_rawDesc), len(file_declaration_declaration_proto_rawDesc)))
	})
	return file_declaration_declaration_proto_rawDescData
}

var file_declaration_declaration_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_declaration_declaration_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_declaration_declaration_proto_goTypes = []any{
	(DeclarationType)(0),             // 0: declaration.DeclarationType
	(DeclarationStatus)(0),           // 1: declaration.DeclarationStatus
	(RiskLane)(0),                    // 2: declaration.RiskLane
	(*Declaration)(nil),              // 3: declaration.Declaration
	(*Document)(nil),                 // 4: declaration.Document
	(*CreateDeclarationRequest)(nil), // 5: declaration.CreateDeclarationRequest
	(*GetDeclarationRequest)(nil),    // 6: declaration.GetDeclarationRequest
	(*ListDeclarationsRequest)(nil),  // 7: declaration.ListDeclarationsRequest
	(*ListDeclarationsResponse)(nil), // 8: declaration.ListDeclarationsResponse
	(*SubmitDeclarationRequest)(nil), // 9: declaration.SubmitDeclarationRequest
	(*UpdateStatusRequest)(nil),      // 10: declaration.UpdateStatusRequest
	(*AttachDocumentRequest)(nil),    // 11: declaration.AttachDocumentRequest
	(*GetDocumentsRequest)(nil),      // 12: declaration.GetDocumentsRequest
	(*GetDocumentsResponse)(nil),     // 13: declaration.GetDocumentsResponse
	(*DeclarationStatsResponse)(nil), // 14: declaration.DeclarationStatsResponse
	(*common.Money)(nil),             // 15: common.Money
	(*timestamp.Timestamp)(nil),      // 16: google.protobuf.Timestamp
	(*common.PageRequest)(nil),       // 17: common.PageRequest
	(*common.PageMeta)(nil),          // 18: common.PageMeta
	(*common.HealthResponse)(nil),    // 19: common.HealthResponse
}
var file_declaration_declaration_proto_depIdxs = []int32{
	0,  // 0: declaration.Declaration.declaration_type:type_name -> declaration.DeclarationType
	1,  // 1: declaration.Declaration.status:type_name -> declaration.DeclarationStatus
	15, // 2: declaration.Declaration.invoice_value:type_name -> common.Money
	2,  // 3: declaration.Declaration.risk_lane:type_name -> declaration.RiskLane
	15, // 4: declaration.Declaration.duty_amount:type_name -> common.Money
	15, // 5: declaration.Declaration.vat_amount:type_name -> common.Money
	15, // 6: declaration.Declaration.total_due:type_name -> common.Money
	16, // 7: declaration.Declaration.submitted_at:type_name -> google.protobuf.Timestamp
	16, // 8: declaration.Declaration.cleared_at:type_name -> google.protobuf.Timestamp
	16, // 9: declaration.Declaration.created_at:type_name -> google.protobuf.Timestamp
	16, // 10: declaration.Declaration.updated_at:type_name -> google.protobuf.Timestamp
	16, // 11: declaration.Document.uploaded_at:type_name -> google.protobuf.Timestamp
	0,  // 12: declaration.CreateDeclarationRequest.declaration_type:type_name -> declaration.DeclarationType
	15, // 13: declaration.CreateDeclarationRequest.invoice_value:type_name -> common.Money
	1,  // 14: declaration.ListDeclarationsRequest.status:type_name -> declaration.DeclarationStatus
	17, // 15: declaration.ListDeclarationsRequest.page:type_name -> common.PageRequest
	3,  // 16: declaration.ListDeclarationsResponse.declarations:type_name -> declaration.Declaration
	18, // 17: declaration.ListDeclarationsResponse.meta:type_name -> common.PageMeta
	1,  // 18: declaration.UpdateStatusRequest.status:type_name -> declaration.DeclarationStatus
	4,  // 19: declaration.GetDocumentsResponse.documents:type_name -> declaration.Document
	5,  // 20: declaration.DeclarationService.CreateDeclaration:input_type -> declaration.CreateDeclarationRequest
	6,  // 21: declaration.DeclarationService.GetDeclaration:input_type -> declaration.GetDeclarationRequest
	7,  // 22: declaration.DeclarationService.ListDeclarations:input_type -> declaration.ListDeclarationsRequest
	9,  // 23: declaration.DeclarationService.SubmitDeclaration:input_type -> declaration.SubmitDeclarationRequest
	10, // 24: declaration.DeclarationService.UpdateStatus:input_type -> declaration.UpdateStatusRequest
	11, // 25: declaration.DeclarationService.AttachDocument:input_type -> declaration.AttachDocumentRequest
	12, // 26: declaration.DeclarationService.GetDocuments:input_type -> declaration.GetDocumentsRequest
	17, // 27: declaration.DeclarationService.GetStats:input_type -> common.PageRequest
	17, // 28: declaration.DeclarationService.Health:input_type -> common.PageRequest
	3,  // 29: declaration.DeclarationService.CreateDeclaration:output_type -> declaration.Declaration
	3,  // 30: declaration.DeclarationService.GetDeclaration:output_type -> declaration.Declaration
	8,  // 31: declaration.DeclarationService.ListDeclarations:output_type -> declaration.ListDeclarationsResponse
	3,  // 32: declaration.DeclarationService.SubmitDeclaration:output_type -> declaration.Declaration
	3,  // 33: declaration.DeclarationService.UpdateStatus:output_type -> declaration.Declaration
	4,  // 34: declaration.DeclarationService.AttachDocument:output_type -> declaration.Document
	13, // 35: declaration.DeclarationService.GetDocuments:output_type -> declaration.GetDocumentsResponse
	14, // 36: declaration.DeclarationService.GetStats:output_type -> declaration.DeclarationStatsResponse
	19, // 37: declaration.DeclarationService.Health:output_type -> common.HealthResponse
	29, // [29:38] is the sub-list for method output_type
	20, // [20:29] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_declaration_declaration_proto_init() }
func file_declaration_declaration_proto_init() {
	if File_declaration_declaration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_declaration_declaration_proto_rawDesc), len(file_declaration_declaration_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_declaration_declaration_proto_goTypes,
		DependencyIndexes: file_declaration_declaration_proto_depIdxs,
		EnumInfos:         file_declaration_declaration_proto_enumTypes,
		MessageInfos:      file_declaration_declaration_proto_msgTypes,
	}.Build()
	File_declaration_declaration_proto = out.File
	file_declaration_declaration_proto_goTypes = nil
	file_declaration_declaration_proto_depIdxs = nil
}
