// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: declaration/declaration.proto

package declaration

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "tradegateway/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeclarationService_CreateDeclaration_FullMethodName = "/declaration.DeclarationService/CreateDeclaration"
	DeclarationService_GetDeclaration_FullMethodName    = "/declaration.DeclarationService/GetDeclaration"
	DeclarationService_ListDeclarations_FullMethodName  = "/declaration.DeclarationService/ListDeclarations"
	DeclarationService_SubmitDeclaration_FullMethodName = "/declaration.DeclarationService/SubmitDeclaration"
	DeclarationService_UpdateStatus_FullMethodName      = "/declaration.DeclarationService/UpdateStatus"
	DeclarationService_AttachDocument_FullMethodName    = "/declaration.DeclarationService/AttachDocument"
	DeclarationService_GetDocuments_FullMethodName      = "/declaration.DeclarationService/GetDocuments"
	DeclarationService_GetStats_FullMethodName          = "/declaration.DeclarationService/GetStats"
	DeclarationService_Health_FullMethodName            = "/declaration.DeclarationService/Health"
)

// DeclarationServiceClient is the client API for DeclarationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ─── SERVICE ─────────────────────────────────────────────────────────────────
type DeclarationServiceClient interface {
	CreateDeclaration(ctx context.Context, in *CreateDeclarationRequest, opts ...grpc.CallOption) (*Declaration, error)
	GetDeclaration(ctx context.Context, in *GetDeclarationRequest, opts ...grpc.CallOption) (*Declaration, error)
	ListDeclarations(ctx context.Context, in *ListDeclarationsRequest, opts ...grpc.CallOption) (*ListDeclarationsResponse, error)
	SubmitDeclaration(ctx context.Context, in *SubmitDeclarationRequest, opts ...grpc.CallOption) (*Declaration, error)
	UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*Declaration, error)
	AttachDocument(ctx context.Context, in *AttachDocumentRequest, opts ...grpc.CallOption) (*Document, error)
	GetDocuments(ctx context.Context, in *GetDocumentsRequest, opts ...grpc.CallOption) (*GetDocumentsResponse, error)
	GetStats(ctx context.Context, in *common.PageRequest, opts ...grpc.CallOption) (*DeclarationStatsResponse, error)
	Health(ctx context.Context, in *common.PageRequest, opts ...grpc.CallOption) (*common.HealthResponse, error)
}

type declarationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeclarationServiceClient(cc grpc.ClientConnInterface) DeclarationServiceClient {
	return &declarationServiceClient{cc}
}

func (c *declarationServiceClient) CreateDeclaration(ctx context.Context, in *CreateDeclarationRequest, opts ...grpc.CallOption) (*Declaration, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Declaration)
	err := c.cc.Invoke(ctx, DeclarationService_CreateDeclaration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *declarationServiceClient) GetDeclaration(ctx context.Context, in *GetDeclarationRequest, opts ...grpc.CallOption) (*Declaration, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Declaration)
	err := c.cc.Invoke(ctx, DeclarationService_GetDeclaration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *declarationServiceClient) ListDeclarations(ctx context.Context, in *ListDeclarationsRequest, opts ...grpc.CallOption) (*ListDeclarationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeclarationsResponse)
	err := c.cc.Invoke(ctx, DeclarationService_ListDeclarations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *declarationServiceClient) SubmitDeclaration(ctx context.Context, in *SubmitDeclarationRequest, opts ...grpc.CallOption) (*Declaration, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Declaration)
	err := c.cc.Invoke(ctx, DeclarationService_SubmitDeclaration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *declarationServiceClient) UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*Declaration, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Declaration)
	err := c.cc.Invoke(ctx, DeclarationService_UpdateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *declarationServiceClient) AttachDocument(ctx context.Context, in *AttachDocumentRequest, opts ...grpc.CallOption) (*Document, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Document)
	err := c.cc.Invoke(ctx, DeclarationService_AttachDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *declarationServiceClient) GetDocuments(ctx context.Context, in *GetDocumentsRequest, opts ...grpc.CallOption) (*GetDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDocumentsResponse)
	err := c.cc.Invoke(ctx, DeclarationService_GetDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *declarationServiceClient) GetStats(ctx context.Context, in *common.PageRequest, opts ...grpc.CallOption) (*DeclarationStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeclarationStatsResponse)
	err := c.cc.Invoke(ctx, DeclarationService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *declarationServiceClient) Health(ctx context.Context, in *common.PageRequest, opts ...grpc.CallOption) (*common.HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.HealthResponse)
	err := c.cc.Invoke(ctx, DeclarationService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeclarationServiceServer is the server API for DeclarationService service.
// All implementations must embed UnimplementedDeclarationServiceServer
// for forward compatibility.
//
// ─── SERVICE ─────────────────────────────────────────────────────────────────
type DeclarationServiceServer interface {
	CreateDeclaration(context.Context, *CreateDeclarationRequest) (*Declaration, error)
	GetDeclaration(context.Context, *GetDeclarationRequest) (*Declaration, error)
	ListDeclarations(context.Context, *ListDeclarationsRequest) (*ListDeclarationsResponse, error)
	SubmitDeclaration(context.Context, *SubmitDeclarationRequest) (*Declaration, error)
	UpdateStatus(context.Context, *UpdateStatusRequest) (*Declaration, error)
	AttachDocument(context.Context, *AttachDocumentRequest) (*Document, error)
	GetDocuments(context.Context, *GetDocumentsRequest) (*GetDocumentsResponse, error)
	GetStats(context.Context, *common.PageRequest) (*DeclarationStatsResponse, error)
	Health(context.Context, *common.PageRequest) (*common.HealthResponse, error)
	mustEmbedUnimplementedDeclarationServiceServer()
}

// UnimplementedDeclarationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeclarationServiceServer struct{}

func (UnimplementedDeclarationServiceServer) CreateDeclaration(context.Context, *CreateDeclarationRequest) (*Declaration, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDeclaration not implemented")
}
func (UnimplementedDeclarationServiceServer) GetDeclaration(context.Context, *GetDeclarationRequest) (*Declaration, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeclaration not implemented")
}
func (UnimplementedDeclarationServiceServer) ListDeclarations(context.Context, *ListDeclarationsRequest) (*ListDeclarationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDeclarations not implemented")
}
func (UnimplementedDeclarationServiceServer) SubmitDeclaration(context.Context, *SubmitDeclarationRequest) (*Declaration, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitDeclaration not implemented")
}
func (UnimplementedDeclarationServiceServer) UpdateStatus(context.Context, *UpdateStatusRequest) (*Declaration, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (UnimplementedDeclarationServiceServer) AttachDocument(context.Context, *AttachDocumentRequest) (*Document, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachDocument not implemented")
}
func (UnimplementedDeclarationServiceServer) GetDocuments(context.Context, *GetDocumentsRequest) (*GetDocumentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDocuments not implemented")
}
func (UnimplementedDeclarationServiceServer) GetStats(context.Context, *common.PageRequest) (*DeclarationStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedDeclarationServiceServer) Health(context.Context, *common.PageRequest) (*common.HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedDeclarationServiceServer) mustEmbedUnimplementedDeclarationServiceServer() {}
func (UnimplementedDeclarationServiceServer) testEmbeddedByValue()                            {}

// UnsafeDeclarationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeclarationServiceServer will
// result in compilation errors.
type UnsafeDeclarationServiceServer interface {
	mustEmbedUnimplementedDeclarationServiceServer()
}

func RegisterDeclarationServiceServer(s grpc.ServiceRegistrar, srv DeclarationServiceServer) {
	// If the following call panics, it indicates UnimplementedDeclarationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeclarationService_ServiceDesc, srv)
}

func _DeclarationService_CreateDeclaration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeclarationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeclarationServiceServer).CreateDeclaration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeclarationService_CreateDeclaration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeclarationServiceServer).CreateDeclaration(ctx, req.(*CreateDeclarationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeclarationService_GetDeclaration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeclarationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeclarationServiceServer).GetDeclaration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeclarationService_GetDeclaration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeclarationServiceServer).GetDeclaration(ctx, req.(*GetDeclarationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeclarationService_ListDeclarations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeclarationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeclarationServiceServer).ListDeclarations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeclarationService_ListDeclarations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeclarationServiceServer).ListDeclarations(ctx, req.(*ListDeclarationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeclarationService_SubmitDeclaration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitDeclarationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeclarationServiceServer).SubmitDeclaration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeclarationService_SubmitDeclaration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeclarationServiceServer).SubmitDeclaration(ctx, req.(*SubmitDeclarationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeclarationService_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeclarationServiceServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeclarationService_UpdateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeclarationServiceServer).UpdateStatus(ctx, req.(*UpdateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeclarationService_AttachDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeclarationServiceServer).AttachDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeclarationService_AttachDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeclarationServiceServer).AttachDocument(ctx, req.(*AttachDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeclarationService_GetDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeclarationServiceServer).GetDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeclarationService_GetDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeclarationServiceServer).GetDocuments(ctx, req.(*GetDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeclarationService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeclarationServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeclarationService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeclarationServiceServer).GetStats(ctx, req.(*common.PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeclarationService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeclarationServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeclarationService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeclarationServiceServer).Health(ctx, req.(*common.PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeclarationService_ServiceDesc is the grpc.ServiceDesc for DeclarationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeclarationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "declaration.DeclarationService",
	HandlerType: (*DeclarationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDeclaration",
			Handler:    _DeclarationService_CreateDeclaration_Handler,
		},
		{
			MethodName: "GetDeclaration",
			Handler:    _DeclarationService_GetDeclaration_Handler,
		},
		{
			MethodName: "ListDeclarations",
			Handler:    _DeclarationService_ListDeclarations_Handler,
		},
		{
			MethodName: "SubmitDeclaration",
			Handler:    _DeclarationService_SubmitDeclaration_Handler,
		},
		{
			MethodName: "UpdateStatus",
			Handler:    _DeclarationService_UpdateStatus_Handler,
		},
		{
			MethodName: "AttachDocument",
			Handler:    _DeclarationService_AttachDocument_Handler,
		},
		{
			MethodName: "GetDocuments",
			Handler:    _DeclarationService_GetDocuments_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _DeclarationService_GetStats_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _DeclarationService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "declaration/declaration.proto",
}
