// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: oga/oga.proto

package oga

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	common "tradegateway/proto/common"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PermitStatus int32

const (
	PermitStatus_PERMIT_STATUS_UNSPECIFIED PermitStatus = 0
	PermitStatus_PENDING                   PermitStatus = 1
	PermitStatus_APPROVED                  PermitStatus = 2
	PermitStatus_REJECTED                  PermitStatus = 3
	PermitStatus_EXPIRED                   PermitStatus = 4
	PermitStatus_REVOKED                   PermitStatus = 5
)

// Enum value maps for PermitStatus.
var (
	PermitStatus_name = map[int32]string{
		0: "PERMIT_STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "APPROVED",
		3: "REJECTED",
		4: "EXPIRED",
		5: "REVOKED",
	}
	PermitStatus_value = map[string]int32{
		"PERMIT_STATUS_UNSPECIFIED": 0,
		"PENDING":                   1,
		"APPROVED":                  2,
		"REJECTED":                  3,
		"EXPIRED":                   4,
		"REVOKED":                   5,
	}
)

func (x PermitStatus) Enum() *PermitStatus {
	p := new(PermitStatus)
	*p = x
	return p
}

func (x PermitStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermitStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_oga_oga_proto_enumTypes[0].Descriptor()
}

func (PermitStatus) Type() protoreflect.EnumType {
	return &file_oga_oga_proto_enumTypes[0]
}

func (x PermitStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermitStatus.Descriptor instead.
func (PermitStatus) EnumDescriptor() ([]byte, []int) {
	return file_oga_oga_proto_rawDescGZIP(), []int{0}
}

type OGAType int32

const (
	OGAType_OGA_TYPE_UNSPECIFIED OGAType = 0
	OGAType_HEALTH_AUTHORITY     OGAType = 1
	OGAType_AGRICULTURE          OGAType = 2
	OGAType_ENVIRONMENT          OGAType = 3
	OGAType_STANDARDS_BUREAU     OGAType = 4
	OGAType_CENTRAL_BANK         OGAType = 5
	OGAType_DRUG_AUTHORITY       OGAType = 6
	OGAType_RADIATION_AUTHORITY  OGAType = 7
	OGAType_WILDLIFE_AUTHORITY   OGAType = 8
	OGAType_ENERGY_AUTHORITY     OGAType = 9
	OGAType_DEFENSE_MINISTRY     OGAType = 10
)

// Enum value maps for OGAType.
var (
	OGAType_name = map[int32]string{
		0:  "OGA_TYPE_UNSPECIFIED",
		1:  "HEALTH_AUTHORITY",
		2:  "AGRICULTURE",
		3:  "ENVIRONMENT",
		4:  "STANDARDS_BUREAU",
		5:  "CENTRAL_BANK",
		6:  "DRUG_AUTHORITY",
		7:  "RADIATION_AUTHORITY",
		8:  "WILDLIFE_AUTHORITY",
		9:  "ENERGY_AUTHORITY",
		10: "DEFENSE_MINISTRY",
	}
	OGAType_value = map[string]int32{
		"OGA_TYPE_UNSPECIFIED": 0,
		"HEALTH_AUTHORITY":     1,
		"AGRICULTURE":          2,
		"ENVIRONMENT":          3,
		"STANDARDS_BUREAU":     4,
		"CENTRAL_BANK":         5,
		"DRUG_AUTHORITY":       6,
		"RADIATION_AUTHORITY":  7,
		"WILDLIFE_AUTHORITY":   8,
		"ENERGY_AUTHORITY":     9,
		"DEFENSE_MINISTRY":     10,
	}
)

func (x OGAType) Enum() *OGAType {
	p := new(OGAType)
	*p = x
	return p
}

func (x OGAType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OGAType) Descriptor() protoreflect.EnumDescriptor {
	return file_oga_oga_proto_enumTypes[1].Descriptor()
}

func (OGAType) Type() protoreflect.EnumType {
	return &file_oga_oga_proto_enumTypes[1]
}

func (x OGAType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OGAType.Descriptor instead.
func (OGAType) EnumDescriptor() ([]byte, []int) {
	return file_oga_oga_proto_rawDescGZIP(), []int{1}
}

type OGAPermit struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DeclarationId     int64                  `protobuf:"varint,2,opt,name=declaration_id,json=declarationId,proto3" json:"declaration_id,omitempty"`
	PermitNumber      string                 `protobuf:"bytes,3,opt,name=permit_number,json=permitNumber,proto3" json:"permit_number,omitempty"`
	OgaType           OGAType                `protobuf:"varint,4,opt,name=oga_type,json=ogaType,proto3,enum=oga.OGAType" json:"oga_type,omitempty"`
	OgaName           string                 `protobuf:"bytes,5,opt,name=oga_name,json=ogaName,proto3" json:"oga_name,omitempty"`
	Status            PermitStatus           `protobuf:"varint,6,opt,name=status,proto3,enum=oga.PermitStatus" json:"status,omitempty"`
	AssignedOfficerId int64                  `protobuf:"varint,7,opt,name=assigned_officer_id,json=assignedOfficerId,proto3" json:"assigned_officer_id,omitempty"`
	ReviewNotes       string                 `protobuf:"bytes,8,opt,name=review_notes,json=reviewNotes,proto3" json:"review_notes,omitempty"`
	Conditions        string                 `protobuf:"bytes,9,opt,name=conditions,proto3" json:"conditions,omitempty"`
	RequestedAt       *timestamp.Timestamp   `protobuf:"bytes,10,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	ReviewedAt        *timestamp.Timestamp   `protobuf:"bytes,11,opt,name=reviewed_at,json=reviewedAt,proto3" json:"reviewed_at,omitempty"`
	ExpiresAt         *timestamp.Timestamp   `protobuf:"bytes,12,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OGAPermit) Reset() {
	*x = OGAPermit{}
	mi := &file_oga_oga_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OGAPermit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OGAPermit) ProtoMessage() {}

func (x *OGAPermit) ProtoReflect() protoreflect.Message {
	mi := &file_oga_oga_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OGAPermit.ProtoReflect.Descriptor instead.
func (*OGAPermit) Descriptor() ([]byte, []int) {
	return file_oga_oga_proto_rawDescGZIP(), []int{0}
}

func (x *OGAPermit) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OGAPermit) GetDeclarationId() int64 {
	if x != nil {
		return x.DeclarationId
	}
	return 0
}

func (x *OGAPermit) GetPermitNumber() string {
	if x != nil {
		return x.PermitNumber
	}
	return ""
}

func (x *OGAPermit) GetOgaType() OGAType {
	if x != nil {
		return x.OgaType
	}
	return OGAType_OGA_TYPE_UNSPECIFIED
}

func (x *OGAPermit) GetOgaName() string {
	if x != nil {
		return x.OgaName
	}
	return ""
}

func (x *OGAPermit) GetStatus() PermitStatus {
	if x != nil {
		return x.Status
	}
	return PermitStatus_PERMIT_STATUS_UNSPECIFIED
}

func (x *OGAPermit) GetAssignedOfficerId() int64 {
	if x != nil {
		return x.AssignedOfficerId
	}
	return 0
}

func (x *OGAPermit) GetReviewNotes() string {
	if x != nil {
		return x.ReviewNotes
	}
	return ""
}

func (x *OGAPermit) GetConditions() string {
	if x != nil {
		return x.Conditions
	}
	return ""
}

func (x *OGAPermit) GetRequestedAt() *timestamp.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

func (x *OGAPermit) GetReviewedAt() *timestamp.Timestamp {
	if x != nil {
		return x.ReviewedAt
	}
	return nil
}

func (x *OGAPermit) GetExpiresAt() *timestamp.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type RequestPermitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeclarationId int64                  `protobuf:"varint,1,opt,name=declaration_id,json=declarationId,proto3" json:"declaration_id,omitempty"`
	OgaType       OGAType                `protobuf:"varint,2,opt,name=oga_type,json=ogaType,proto3,enum=oga.OGAType" json:"oga_type,omitempty"`
	OgaName       string                 `protobuf:"bytes,3,opt,name=oga_name,json=ogaName,proto3" json:"oga_name,omitempty"`
	Notes         string                 `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPermitRequest) Reset() {
	*x = RequestPermitRequest{}
	mi := &file_oga_oga_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPermitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPermitRequest) ProtoMessage() {}

func (x *RequestPermitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oga_oga_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPermitRequest.ProtoReflect.Descriptor instead.
func (*RequestPermitRequest) Descriptor() ([]byte, []int) {
	return file_oga_oga_proto_rawDescGZIP(), []int{1}
}

func (x *RequestPermitRequest) GetDeclarationId() int64 {
	if x != nil {
		return x.DeclarationId
	}
	return 0
}

func (x *RequestPermitRequest) GetOgaType() OGAType {
	if x != nil {
		return x.OgaType
	}
	return OGAType_OGA_TYPE_UNSPECIFIED
}

func (x *RequestPermitRequest) GetOgaName() string {
	if x != nil {
		return x.OgaName
	}
	return ""
}

func (x *RequestPermitRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type ReviewPermitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermitId      int64                  `protobuf:"varint,1,opt,name=permit_id,json=permitId,proto3" json:"permit_id,omitempty"`
	Status        PermitStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=oga.PermitStatus" json:"status,omitempty"`
	Notes         string                 `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	Conditions    string                 `protobuf:"bytes,4,opt,name=conditions,proto3" json:"conditions,omitempty"`
	OfficerId     int64                  `protobuf:"varint,5,opt,name=officer_id,json=officerId,proto3" json:"officer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewPermitRequest) Reset() {
	*x = ReviewPermitRequest{}
	mi := &file_oga_oga_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewPermitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewPermitRequest) ProtoMessage() {}

func (x *ReviewPermitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oga_oga_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewPermitRequest.ProtoReflect.Descriptor instead.
func (*ReviewPermitRequest) Descriptor() ([]byte, []int) {
	return file_oga_oga_proto_rawDescGZIP(), []int{2}
}

func (x *ReviewPermitRequest) GetPermitId() int64 {
	if x != nil {
		return x.PermitId
	}
	return 0
}

func (x *ReviewPermitRequest) GetStatus() PermitStatus {
	if x != nil {
		return x.Status
	}
	return PermitStatus_PERMIT_STATUS_UNSPECIFIED
}

func (x *ReviewPermitRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *ReviewPermitRequest) GetConditions() string {
	if x != nil {
		return x.Conditions
	}
	return ""
}

func (x *ReviewPermitRequest) GetOfficerId() int64 {
	if x != nil {
		return x.OfficerId
	}
	return 0
}

type GetPermitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeclarationId int64                  `protobuf:"varint,1,opt,name=declaration_id,json=declarationId,proto3" json:"declaration_id,omitempty"`
	OfficerId     int64                  `protobuf:"varint,2,opt,name=officer_id,json=officerId,proto3" json:"officer_id,omitempty"` // 0 = all
	Status        PermitStatus           `protobuf:"varint,3,opt,name=status,proto3,enum=oga.PermitStatus" json:"status,omitempty"`  // 0 = all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermitsRequest) Reset() {
	*x = GetPermitsRequest{}
	mi := &file_oga_oga_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermitsRequest) ProtoMessage() {}

func (x *GetPermitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oga_oga_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermitsRequest.ProtoReflect.Descriptor instead.
func (*GetPermitsRequest) Descriptor() ([]byte, []int) {
	return file_oga_oga_proto_rawDescGZIP(), []int{3}
}

func (x *GetPermitsRequest) GetDeclarationId() int64 {
	if x != nil {
		return x.DeclarationId
	}
	return 0
}

func (x *GetPermitsRequest) GetOfficerId() int64 {
	if x != nil {
		return x.OfficerId
	}
	return 0
}

func (x *GetPermitsRequest) GetStatus() PermitStatus {
	if x != nil {
		return x.Status
	}
	return PermitStatus_PERMIT_STATUS_UNSPECIFIED
}

type GetPermitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permits       []*OGAPermit           `protobuf:"bytes,1,rep,name=permits,proto3" json:"permits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermitsResponse) Reset() {
	*x = GetPermitsResponse{}
	mi := &file_oga_oga_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermitsResponse) ProtoMessage() {}

func (x *GetPermitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oga_oga_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermitsResponse.ProtoReflect.Descriptor instead.
func (*GetPermitsResponse) Descriptor() ([]byte, []int) {
	return file_oga_oga_proto_rawDescGZIP(), []int{4}
}

func (x *GetPermitsResponse) GetPermits() []*OGAPermit {
	if x != nil {
		return x.Permits
	}
	return nil
}

type JointInspectionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeclarationId int64                  `protobuf:"varint,1,opt,name=declaration_id,json=declarationId,proto3" json:"declaration_id,omitempty"`
	TotalAgencies int32                  `protobuf:"varint,2,opt,name=total_agencies,json=totalAgencies,proto3" json:"total_agencies,omitempty"`
	Approved      int32                  `protobuf:"varint,3,opt,name=approved,proto3" json:"approved,omitempty"`
	Rejected      int32                  `protobuf:"varint,4,opt,name=rejected,proto3" json:"rejected,omitempty"`
	Pending       int32                  `protobuf:"varint,5,opt,name=pending,proto3" json:"pending,omitempty"`
	AllCleared    bool                   `protobuf:"varint,6,opt,name=all_cleared,json=allCleared,proto3" json:"all_cleared,omitempty"`
	AnyRejected   bool                   `protobuf:"varint,7,opt,name=any_rejected,json=anyRejected,proto3" json:"any_rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JointInspectionStatus) Reset() {
	*x = JointInspectionStatus{}
	mi := &file_oga_oga_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JointInspectionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JointInspectionStatus) ProtoMessage() {}

func (x *JointInspectionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_oga_oga_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JointInspectionStatus.ProtoReflect.Descriptor instead.
func (*JointInspectionStatus) Descriptor() ([]byte, []int) {
	return file_oga_oga_proto_rawDescGZIP(), []int{5}
}

func (x *JointInspectionStatus) GetDeclarationId() int64 {
	if x != nil {
		return x.DeclarationId
	}
	return 0
}

func (x *JointInspectionStatus) GetTotalAgencies() int32 {
	if x != nil {
		return x.TotalAgencies
	}
	return 0
}

func (x *JointInspectionStatus) GetApproved() int32 {
	if x != nil {
		return x.Approved
	}
	return 0
}

func (x *JointInspectionStatus) GetRejected() int32 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

func (x *JointInspectionStatus) GetPending() int32 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *JointInspectionStatus) GetAllCleared() bool {
	if x != nil {
		return x.AllCleared
	}
	return false
}

func (x *JointInspectionStatus) GetAnyRejected() bool {
	if x != nil {
		return x.AnyRejected
	}
	return false
}

var File_oga_oga_proto protoreflect.FileDescriptor

const file_oga_oga_proto_rawDesc = "" +
	"\n" +
	"\roga/oga.proto\x12\x03oga\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\x80\x04\n" +
	"\tOGAPermit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\x0edeclaration_id\x18\x02 \x01(\x03R\rdeclarationId\x12#\n" +
	"\rpermit_number\x18\x03 \x01(\tR\fpermitNumber\x12'\n" +
	"\boga_type\x18\x04 \x01(\x0e2\f.oga.OGATypeR\aogaType\x12\x19\n" +
	"\boga_name\x18\x05 \x01(\tR\aogaName\x12)\n" +
	"\x06status\x18\x06 \x01(\x0e2\x11.oga.PermitStatusR\x06status\x12.\n" +
	"\x13assigned_officer_id\x18\a \x01(\x03R\x11assignedOfficerId\x12!\n" +
	"\freview_notes\x18\b \x01(\tR\vreviewNotes\x12\x1e\n" +
	"\n" +
	"conditions\x18\t \x01(\tR\n" +
	"conditions\x12=\n" +
	"\frequested_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vrequestedAt\x12;\n" +
	"\vreviewed_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reviewedAt\x129\n" +
	"\n" +
	"expires_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x97\x01\n" +
	"\x14RequestPermitRequest\x12%\n" +
	"\x0edeclaration_id\x18\x01 \x01(\x03R\rdeclarationId\x12'\n" +
	"\boga_type\x18\x02 \x01(\x0e2\f.oga.OGATypeR\aogaType\x12\x19\n" +
	"\boga_name\x18\x03 \x01(\tR\aogaName\x12\x14\n" +
	"\x05notes\x18\x04 \x01(\tR\x05notes\"\xb2\x01\n" +
	"\x13ReviewPermitRequest\x12\x1b\n" +
	"\tpermit_id\x18\x01 \x01(\x03R\bpermitId\x12)\n" +
	"\x06status\x18\x02 \x01(\x0e2\x11.oga.PermitStatusR\x06status\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\x12\x1e\n" +
	"\n" +
	"conditions\x18\x04 \x01(\tR\n" +
	"conditions\x12\x1d\n" +
	"\n" +
	"officer_id\x18\x05 \x01(\x03R\tofficerId\"\x84\x01\n" +
	"\x11GetPermitsRequest\x12%\n" +
	"\x0edeclaration_id\x18\x01 \x01(\x03R\rdeclarationId\x12\x1d\n" +
	"\n" +
	"officer_id\x18\x02 \x01(\x03R\tofficerId\x12)\n" +
	"\x06status\x18\x03 \x01(\x0e2\x11.oga.PermitStatusR\x06status\">\n" +
	"\x12GetPermitsResponse\x12(\n" +
	"\apermits\x18\x01 \x03(\v2\x0e.oga.OGAPermitR\apermits\"\xfb\x01\n" +
	"\x15JointInspectionStatus\x12%\n" +
	"\x0edeclaration_id\x18\x01 \x01(\x03R\rdeclarationId\x12%\n" +
	"\x0etotal_agencies\x18\x02 \x01(\x05R\rtotalAgencies\x12\x1a\n" +
	"\bapproved\x18\x03 \x01(\x05R\bapproved\x12\x1a\n" +
	"\brejected\x18\x04 \x01(\x05R\brejected\x12\x18\n" +
	"\apending\x18\x05 \x01(\x05R\apending\x12\x1f\n" +
	"\vall_cleared\x18\x06 \x01(\bR\n" +
	"allCleared\x12!\n" +
	"\fany_rejected\x18\a \x01(\bR\vanyRejected*p\n" +
	"\fPermitStatus\x12\x1d\n" +
	"\x19PERMIT_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\f\n" +
	"\bAPPROVED\x10\x02\x12\f\n" +
	"\bREJECTED\x10\x03\x12\v\n" +
	"\aEXPIRED\x10\x04\x12\v\n" +
	"\aREVOKED\x10\x05*\xf4\x01\n" +
	"\aOGAType\x12\x18\n" +
	"\x14OGA_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10HEALTH_AUTHORITY\x10\x01\x12\x0f\n" +
	"\vAGRICULTURE\x10\x02\x12\x0f\n" +
	"\vENVIRONMENT\x10\x03\x12\x14\n" +
	"\x10STANDARDS_BUREAU\x10\x04\x12\x10\n" +
	"\fCENTRAL_BANK\x10\x05\x12\x12\n" +
	"\x0eDRUG_AUTHORITY\x10\x06\x12\x17\n" +
	"\x13RADIATION_AUTHORITY\x10\a\x12\x16\n" +
	"\x12WILDLIFE_AUTHORITY\x10\b\x12\x14\n" +
	"\x10ENERGY_AUTHORITY\x10\t\x12\x14\n" +
	"\x10DEFENSE_MINISTRY\x10\n" +
	"2\xc8\x02\n" +
	"\n" +
	"OGAService\x12:\n" +
	"\rRequestPermit\x12\x19.oga.RequestPermitRequest\x1a\x0e.oga.OGAPermit\x128\n" +
	"\fReviewPermit\x12\x18.oga.ReviewPermitRequest\x1a\x0e.oga.OGAPermit\x12=\n" +
	"\n" +
	"GetPermits\x12\x16.oga.GetPermitsRequest\x1a\x17.oga.GetPermitsResponse\x12N\n" +
	"\x18GetJointInspectionStatus\x12\x16.oga.GetPermitsRequest\x1a\x1a.oga.JointInspectionStatus\x125\n" +
	"\x06Health\x12\x13.common.PageRequest\x1a\x16.common.HealthResponseB\x18Z\x16tradegateway/proto/ogab\x06proto3"

var (
	file_oga_oga_proto_rawDescOnce sync.Once
	file_oga_oga_proto_rawDescData []byte
)

func file_oga_oga_proto_rawDescGZIP() []byte {
	file_oga_oga_proto_rawDescOnce.Do(func() {
		file_oga_oga_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oga_oga_proto_rawDesc), len(file_oga_oga_proto_rawDesc)))
	})
	return file_oga_oga_proto_rawDescData
}

var file_oga_oga_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_oga_oga_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_oga_oga_proto_goTypes = []any{
	(PermitStatus)(0),             // 0: oga.PermitStatus
	(OGAType)(0),                  // 1: oga.OGAType
	(*OGAPermit)(nil),             // 2: oga.OGAPermit
	(*RequestPermitRequest)(nil),  // 3: oga.RequestPermitRequest
	(*ReviewPermitRequest)(nil),   // 4: oga.ReviewPermitRequest
	(*GetPermitsRequest)(nil),     // 5: oga.GetPermitsRequest
	(*GetPermitsResponse)(nil),    // 6: oga.GetPermitsResponse
	(*JointInspectionStatus)(nil), // 7: oga.JointInspectionStatus
	(*timestamp.Timestamp)(nil),   // 8: google.protobuf.Timestamp
	(*common.PageRequest)(nil),    // 9: common.PageRequest
	(*common.HealthResponse)(nil), // 10: common.HealthResponse
}
var file_oga_oga_proto_depIdxs = []int32{
	1,  // 0: oga.OGAPermit.oga_type:type_name -> oga.OGAType
	0,  // 1: oga.OGAPermit.status:type_name -> oga.PermitStatus
	8,  // 2: oga.OGAPermit.requested_at:type_name -> google.protobuf.Timestamp
	8,  // 3: oga.OGAPermit.reviewed_at:type_name -> google.protobuf.Timestamp
	8,  // 4: oga.OGAPermit.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 5: oga.RequestPermitRequest.oga_type:type_name -> oga.OGAType
	0,  // 6: oga.ReviewPermitRequest.status:type_name -> oga.PermitStatus
	0,  // 7: oga.GetPermitsRequest.status:type_name -> oga.PermitStatus
	2,  // 8: oga.GetPermitsResponse.permits:type_name -> oga.OGAPermit
	3,  // 9: oga.OGAService.RequestPermit:input_type -> oga.RequestPermitRequest
	4,  // 10: oga.OGAService.ReviewPermit:input_type -> oga.ReviewPermitRequest
	5,  // 11: oga.OGAService.GetPermits:input_type -> oga.GetPermitsRequest
	5,  // 12: oga.OGAService.GetJointInspectionStatus:input_type -> oga.GetPermitsRequest
	9,  // 13: oga.OGAService.Health:input_type -> common.PageRequest
	2,  // 14: oga.OGAService.RequestPermit:output_type -> oga.OGAPermit
	2,  // 15: oga.OGAService.ReviewPermit:output_type -> oga.OGAPermit
	6,  // 16: oga.OGAService.GetPermits:output_type -> oga.GetPermitsResponse
	7,  // 17: oga.OGAService.GetJointInspectionStatus:output_type -> oga.JointInspectionStatus
	10, // 18: oga.OGAService.Health:output_type -> common.HealthResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_oga_oga_proto_init() }
func file_oga_oga_proto_init() {
	if File_oga_oga_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oga_oga_proto_rawDesc), len(file_oga_oga_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oga_oga_proto_goTypes,
		DependencyIndexes: file_oga_oga_proto_depIdxs,
		EnumInfos:         file_oga_oga_proto_enumTypes,
		MessageInfos:      file_oga_oga_proto_msgTypes,
	}.Build()
	File_oga_oga_proto = out.File
	file_oga_oga_proto_goTypes = nil
	file_oga_oga_proto_depIdxs = nil
}
