// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: oga/oga.proto

package oga

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "tradegateway/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OGAService_RequestPermit_FullMethodName            = "/oga.OGAService/RequestPermit"
	OGAService_ReviewPermit_FullMethodName             = "/oga.OGAService/ReviewPermit"
	OGAService_GetPermits_FullMethodName               = "/oga.OGAService/GetPermits"
	OGAService_GetJointInspectionStatus_FullMethodName = "/oga.OGAService/GetJointInspectionStatus"
	OGAService_Health_FullMethodName                   = "/oga.OGAService/Health"
)

// OGAServiceClient is the client API for OGAService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OGAServiceClient interface {
	RequestPermit(ctx context.Context, in *RequestPermitRequest, opts ...grpc.CallOption) (*OGAPermit, error)
	ReviewPermit(ctx context.Context, in *ReviewPermitRequest, opts ...grpc.CallOption) (*OGAPermit, error)
	GetPermits(ctx context.Context, in *GetPermitsRequest, opts ...grpc.CallOption) (*GetPermitsResponse, error)
	GetJointInspectionStatus(ctx context.Context, in *GetPermitsRequest, opts ...grpc.CallOption) (*JointInspectionStatus, error)
	Health(ctx context.Context, in *common.PageRequest, opts ...grpc.CallOption) (*common.HealthResponse, error)
}

type oGAServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOGAServiceClient(cc grpc.ClientConnInterface) OGAServiceClient {
	return &oGAServiceClient{cc}
}

func (c *oGAServiceClient) RequestPermit(ctx context.Context, in *RequestPermitRequest, opts ...grpc.CallOption) (*OGAPermit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OGAPermit)
	err := c.cc.Invoke(ctx, OGAService_RequestPermit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oGAServiceClient) ReviewPermit(ctx context.Context, in *ReviewPermitRequest, opts ...grpc.CallOption) (*OGAPermit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OGAPermit)
	err := c.cc.Invoke(ctx, OGAService_ReviewPermit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oGAServiceClient) GetPermits(ctx context.Context, in *GetPermitsRequest, opts ...grpc.CallOption) (*GetPermitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPermitsResponse)
	err := c.cc.Invoke(ctx, OGAService_GetPermits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oGAServiceClient) GetJointInspectionStatus(ctx context.Context, in *GetPermitsRequest, opts ...grpc.CallOption) (*JointInspectionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JointInspectionStatus)
	err := c.cc.Invoke(ctx, OGAService_GetJointInspectionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oGAServiceClient) Health(ctx context.Context, in *common.PageRequest, opts ...grpc.CallOption) (*common.HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.HealthResponse)
	err := c.cc.Invoke(ctx, OGAService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OGAServiceServer is the server API for OGAService service.
// All implementations must embed UnimplementedOGAServiceServer
// for forward compatibility.
type OGAServiceServer interface {
	RequestPermit(context.Context, *RequestPermitRequest) (*OGAPermit, error)
	ReviewPermit(context.Context, *ReviewPermitRequest) (*OGAPermit, error)
	GetPermits(context.Context, *GetPermitsRequest) (*GetPermitsResponse, error)
	GetJointInspectionStatus(context.Context, *GetPermitsRequest) (*JointInspectionStatus, error)
	Health(context.Context, *common.PageRequest) (*common.HealthResponse, error)
	mustEmbedUnimplementedOGAServiceServer()
}

// UnimplementedOGAServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOGAServiceServer struct{}

func (UnimplementedOGAServiceServer) RequestPermit(context.Context, *RequestPermitRequest) (*OGAPermit, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestPermit not implemented")
}
func (UnimplementedOGAServiceServer) ReviewPermit(context.Context, *ReviewPermitRequest) (*OGAPermit, error) {
	return nil, status.Error(codes.Unimplemented, "method ReviewPermit not implemented")
}
func (UnimplementedOGAServiceServer) GetPermits(context.Context, *GetPermitsRequest) (*GetPermitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPermits not implemented")
}
func (UnimplementedOGAServiceServer) GetJointInspectionStatus(context.Context, *GetPermitsRequest) (*JointInspectionStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJointInspectionStatus not implemented")
}
func (UnimplementedOGAServiceServer) Health(context.Context, *common.PageRequest) (*common.HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedOGAServiceServer) mustEmbedUnimplementedOGAServiceServer() {}
func (UnimplementedOGAServiceServer) testEmbeddedByValue()                    {}

// UnsafeOGAServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OGAServiceServer will
// result in compilation errors.
type UnsafeOGAServiceServer interface {
	mustEmbedUnimplementedOGAServiceServer()
}

func RegisterOGAServiceServer(s grpc.ServiceRegistrar, srv OGAServiceServer) {
	// If the following call panics, it indicates UnimplementedOGAServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OGAService_ServiceDesc, srv)
}

func _OGAService_RequestPermit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPermitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OGAServiceServer).RequestPermit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OGAService_RequestPermit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OGAServiceServer).RequestPermit(ctx, req.(*RequestPermitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OGAService_ReviewPermit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewPermitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OGAServiceServer).ReviewPermit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OGAService_ReviewPermit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OGAServiceServer).ReviewPermit(ctx, req.(*ReviewPermitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OGAService_GetPermits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPermitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OGAServiceServer).GetPermits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OGAService_GetPermits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OGAServiceServer).GetPermits(ctx, req.(*GetPermitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OGAService_GetJointInspectionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPermitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OGAServiceServer).GetJointInspectionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OGAService_GetJointInspectionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OGAServiceServer).GetJointInspectionStatus(ctx, req.(*GetPermitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OGAService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OGAServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OGAService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OGAServiceServer).Health(ctx, req.(*common.PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OGAService_ServiceDesc is the grpc.ServiceDesc for OGAService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OGAService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oga.OGAService",
	HandlerType: (*OGAServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestPermit",
			Handler:    _OGAService_RequestPermit_Handler,
		},
		{
			MethodName: "ReviewPermit",
			Handler:    _OGAService_ReviewPermit_Handler,
		},
		{
			MethodName: "GetPermits",
			Handler:    _OGAService_GetPermits_Handler,
		},
		{
			MethodName: "GetJointInspectionStatus",
			Handler:    _OGAService_GetJointInspectionStatus_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _OGAService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oga/oga.proto",
}
