// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: sanctions/sanctions.proto

package sanctions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	common "tradegateway/proto/common"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScreeningList int32

const (
	ScreeningList_SCREENING_LIST_UNSPECIFIED ScreeningList = 0
	ScreeningList_OFAC_SDN                   ScreeningList = 1
	ScreeningList_UN_SECURITY                ScreeningList = 2
	ScreeningList_EU_CONSOLIDATED            ScreeningList = 3
	ScreeningList_OFSI_UK                    ScreeningList = 4
	ScreeningList_INTERPOL                   ScreeningList = 5
	ScreeningList_WCO_CEN                    ScreeningList = 6
	ScreeningList_DUAL_USE_EAR99             ScreeningList = 7
	ScreeningList_DUAL_USE_CCL               ScreeningList = 8
	ScreeningList_ITAR                       ScreeningList = 9
)

// Enum value maps for ScreeningList.
var (
	ScreeningList_name = map[int32]string{
		0: "SCREENING_LIST_UNSPECIFIED",
		1: "OFAC_SDN",
		2: "UN_SECURITY",
		3: "EU_CONSOLIDATED",
		4: "OFSI_UK",
		5: "INTERPOL",
		6: "WCO_CEN",
		7: "DUAL_USE_EAR99",
		8: "DUAL_USE_CCL",
		9: "ITAR",
	}
	ScreeningList_value = map[string]int32{
		"SCREENING_LIST_UNSPECIFIED": 0,
		"OFAC_SDN":                   1,
		"UN_SECURITY":                2,
		"EU_CONSOLIDATED":            3,
		"OFSI_UK":                    4,
		"INTERPOL":                   5,
		"WCO_CEN":                    6,
		"DUAL_USE_EAR99":             7,
		"DUAL_USE_CCL":               8,
		"ITAR":                       9,
	}
)

func (x ScreeningList) Enum() *ScreeningList {
	p := new(ScreeningList)
	*p = x
	return p
}

func (x ScreeningList) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScreeningList) Descriptor() protoreflect.EnumDescriptor {
	return file_sanctions_sanctions_proto_enumTypes[0].Descriptor()
}

func (ScreeningList) Type() protoreflect.EnumType {
	return &file_sanctions_sanctions_proto_enumTypes[0]
}

func (x ScreeningList) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScreeningList.Descriptor instead.
func (ScreeningList) EnumDescriptor() ([]byte, []int) {
	return file_sanctions_sanctions_proto_rawDescGZIP(), []int{0}
}

type MatchConfidence int32

const (
	MatchConfidence_MATCH_CONFIDENCE_UNSPECIFIED MatchConfidence = 0
	MatchConfidence_EXACT                        MatchConfidence = 1
	MatchConfidence_HIGH                         MatchConfidence = 2
	MatchConfidence_MEDIUM                       MatchConfidence = 3
	MatchConfidence_LOW                          MatchConfidence = 4
)

// Enum value maps for MatchConfidence.
var (
	MatchConfidence_name = map[int32]string{
		0: "MATCH_CONFIDENCE_UNSPECIFIED",
		1: "EXACT",
		2: "HIGH",
		3: "MEDIUM",
		4: "LOW",
	}
	MatchConfidence_value = map[string]int32{
		"MATCH_CONFIDENCE_UNSPECIFIED": 0,
		"EXACT":                        1,
		"HIGH":                         2,
		"MEDIUM":                       3,
		"LOW":                          4,
	}
)

func (x MatchConfidence) Enum() *MatchConfidence {
	p := new(MatchConfidence)
	*p = x
	return p
}

func (x MatchConfidence) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchConfidence) Descriptor() protoreflect.EnumDescriptor {
	return file_sanctions_sanctions_proto_enumTypes[1].Descriptor()
}

func (MatchConfidence) Type() protoreflect.EnumType {
	return &file_sanctions_sanctions_proto_enumTypes[1]
}

func (x MatchConfidence) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchConfidence.Descriptor instead.
func (MatchConfidence) EnumDescriptor() ([]byte, []int) {
	return file_sanctions_sanctions_proto_rawDescGZIP(), []int{1}
}

type ScreeningMatch struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	List           ScreeningList          `protobuf:"varint,1,opt,name=list,proto3,enum=sanctions.ScreeningList" json:"list,omitempty"`
	ListEntryId    string                 `protobuf:"bytes,2,opt,name=list_entry_id,json=listEntryId,proto3" json:"list_entry_id,omitempty"`
	MatchedName    string                 `protobuf:"bytes,3,opt,name=matched_name,json=matchedName,proto3" json:"matched_name,omitempty"`
	Confidence     MatchConfidence        `protobuf:"varint,4,opt,name=confidence,proto3,enum=sanctions.MatchConfidence" json:"confidence,omitempty"`
	Reason         string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Program        string                 `protobuf:"bytes,6,opt,name=program,proto3" json:"program,omitempty"`                                     // e.g. "IRAN", "DPRK"
	ActionRequired string                 `protobuf:"bytes,7,opt,name=action_required,json=actionRequired,proto3" json:"action_required,omitempty"` // "block" | "escalate" | "flag"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScreeningMatch) Reset() {
	*x = ScreeningMatch{}
	mi := &file_sanctions_sanctions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreeningMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreeningMatch) ProtoMessage() {}

func (x *ScreeningMatch) ProtoReflect() protoreflect.Message {
	mi := &file_sanctions_sanctions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreeningMatch.ProtoReflect.Descriptor instead.
func (*ScreeningMatch) Descriptor() ([]byte, []int) {
	return file_sanctions_sanctions_proto_rawDescGZIP(), []int{0}
}

func (x *ScreeningMatch) GetList() ScreeningList {
	if x != nil {
		return x.List
	}
	return ScreeningList_SCREENING_LIST_UNSPECIFIED
}

func (x *ScreeningMatch) GetListEntryId() string {
	if x != nil {
		return x.ListEntryId
	}
	return ""
}

func (x *ScreeningMatch) GetMatchedName() string {
	if x != nil {
		return x.MatchedName
	}
	return ""
}

func (x *ScreeningMatch) GetConfidence() MatchConfidence {
	if x != nil {
		return x.Confidence
	}
	return MatchConfidence_MATCH_CONFIDENCE_UNSPECIFIED
}

func (x *ScreeningMatch) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ScreeningMatch) GetProgram() string {
	if x != nil {
		return x.Program
	}
	return ""
}

func (x *ScreeningMatch) GetActionRequired() string {
	if x != nil {
		return x.ActionRequired
	}
	return ""
}

type ScreenEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityName    string                 `protobuf:"bytes,1,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`
	EntityType    string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // "person" | "organization" | "vessel" | "aircraft"
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Identifier    string                 `protobuf:"bytes,4,opt,name=identifier,proto3" json:"identifier,omitempty"` // passport, tax ID, IMO number
	DeclarationId int64                  `protobuf:"varint,5,opt,name=declaration_id,json=declarationId,proto3" json:"declaration_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenEntityRequest) Reset() {
	*x = ScreenEntityRequest{}
	mi := &file_sanctions_sanctions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenEntityRequest) ProtoMessage() {}

func (x *ScreenEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sanctions_sanctions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenEntityRequest.ProtoReflect.Descriptor instead.
func (*ScreenEntityRequest) Descriptor() ([]byte, []int) {
	return file_sanctions_sanctions_proto_rawDescGZIP(), []int{1}
}

func (x *ScreenEntityRequest) GetEntityName() string {
	if x != nil {
		return x.EntityName
	}
	return ""
}

func (x *ScreenEntityRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *ScreenEntityRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ScreenEntityRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *ScreenEntityRequest) GetDeclarationId() int64 {
	if x != nil {
		return x.DeclarationId
	}
	return 0
}

type ScreenEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsClear       bool                   `protobuf:"varint,1,opt,name=is_clear,json=isClear,proto3" json:"is_clear,omitempty"`
	Matches       []*ScreeningMatch      `protobuf:"bytes,2,rep,name=matches,proto3" json:"matches,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	CheckedLists  int32                  `protobuf:"varint,4,opt,name=checked_lists,json=checkedLists,proto3" json:"checked_lists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenEntityResponse) Reset() {
	*x = ScreenEntityResponse{}
	mi := &file_sanctions_sanctions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenEntityResponse) ProtoMessage() {}

func (x *ScreenEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sanctions_sanctions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenEntityResponse.ProtoReflect.Descriptor instead.
func (*ScreenEntityResponse) Descriptor() ([]byte, []int) {
	return file_sanctions_sanctions_proto_rawDescGZIP(), []int{2}
}

func (x *ScreenEntityResponse) GetIsClear() bool {
	if x != nil {
		return x.IsClear
	}
	return false
}

func (x *ScreenEntityResponse) GetMatches() []*ScreeningMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *ScreenEntityResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ScreenEntityResponse) GetCheckedLists() int32 {
	if x != nil {
		return x.CheckedLists
	}
	return 0
}

type ScreenHSCodeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	HsCode           string                 `protobuf:"bytes,1,opt,name=hs_code,json=hsCode,proto3" json:"hs_code,omitempty"`
	GoodsDescription string                 `protobuf:"bytes,2,opt,name=goods_description,json=goodsDescription,proto3" json:"goods_description,omitempty"`
	CountryOfOrigin  string                 `protobuf:"bytes,3,opt,name=country_of_origin,json=countryOfOrigin,proto3" json:"country_of_origin,omitempty"`
	CountryOfDest    string                 `protobuf:"bytes,4,opt,name=country_of_dest,json=countryOfDest,proto3" json:"country_of_dest,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ScreenHSCodeRequest) Reset() {
	*x = ScreenHSCodeRequest{}
	mi := &file_sanctions_sanctions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenHSCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenHSCodeRequest) ProtoMessage() {}

func (x *ScreenHSCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sanctions_sanctions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenHSCodeRequest.ProtoReflect.Descriptor instead.
func (*ScreenHSCodeRequest) Descriptor() ([]byte, []int) {
	return file_sanctions_sanctions_proto_rawDescGZIP(), []int{3}
}

func (x *ScreenHSCodeRequest) GetHsCode() string {
	if x != nil {
		return x.HsCode
	}
	return ""
}

func (x *ScreenHSCodeRequest) GetGoodsDescription() string {
	if x != nil {
		return x.GoodsDescription
	}
	return ""
}

func (x *ScreenHSCodeRequest) GetCountryOfOrigin() string {
	if x != nil {
		return x.CountryOfOrigin
	}
	return ""
}

func (x *ScreenHSCodeRequest) GetCountryOfDest() string {
	if x != nil {
		return x.CountryOfDest
	}
	return ""
}

type ScreenHSCodeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IsControlled    bool                   `protobuf:"varint,1,opt,name=is_controlled,json=isControlled,proto3" json:"is_controlled,omitempty"`
	IsDualUse       bool                   `protobuf:"varint,2,opt,name=is_dual_use,json=isDualUse,proto3" json:"is_dual_use,omitempty"`
	RequiresLicense bool                   `protobuf:"varint,3,opt,name=requires_license,json=requiresLicense,proto3" json:"requires_license,omitempty"`
	Classification  string                 `protobuf:"bytes,4,opt,name=classification,proto3" json:"classification,omitempty"` // "EAR99" | "CCL" | "ITAR" | "unrestricted"
	Reason          string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	LicenseType     string                 `protobuf:"bytes,6,opt,name=license_type,json=licenseType,proto3" json:"license_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScreenHSCodeResponse) Reset() {
	*x = ScreenHSCodeResponse{}
	mi := &file_sanctions_sanctions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenHSCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenHSCodeResponse) ProtoMessage() {}

func (x *ScreenHSCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sanctions_sanctions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenHSCodeResponse.ProtoReflect.Descriptor instead.
func (*ScreenHSCodeResponse) Descriptor() ([]byte, []int) {
	return file_sanctions_sanctions_proto_rawDescGZIP(), []int{4}
}

func (x *ScreenHSCodeResponse) GetIsControlled() bool {
	if x != nil {
		return x.IsControlled
	}
	return false
}

func (x *ScreenHSCodeResponse) GetIsDualUse() bool {
	if x != nil {
		return x.IsDualUse
	}
	return false
}

func (x *ScreenHSCodeResponse) GetRequiresLicense() bool {
	if x != nil {
		return x.RequiresLicense
	}
	return false
}

func (x *ScreenHSCodeResponse) GetClassification() string {
	if x != nil {
		return x.Classification
	}
	return ""
}

func (x *ScreenHSCodeResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ScreenHSCodeResponse) GetLicenseType() string {
	if x != nil {
		return x.LicenseType
	}
	return ""
}

type BatchScreenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*ScreenEntityRequest `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchScreenRequest) Reset() {
	*x = BatchScreenRequest{}
	mi := &file_sanctions_sanctions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchScreenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchScreenRequest) ProtoMessage() {}

func (x *BatchScreenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sanctions_sanctions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchScreenRequest.ProtoReflect.Descriptor instead.
func (*BatchScreenRequest) Descriptor() ([]byte, []int) {
	return file_sanctions_sanctions_proto_rawDescGZIP(), []int{5}
}

func (x *BatchScreenRequest) GetEntities() []*ScreenEntityRequest {
	if x != nil {
		return x.Entities
	}
	return nil
}

type BatchScreenResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Results       []*ScreenEntityResponse `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchScreenResponse) Reset() {
	*x = BatchScreenResponse{}
	mi := &file_sanctions_sanctions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchScreenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchScreenResponse) ProtoMessage() {}

func (x *BatchScreenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sanctions_sanctions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchScreenResponse.ProtoReflect.Descriptor instead.
func (*BatchScreenResponse) Descriptor() ([]byte, []int) {
	return file_sanctions_sanctions_proto_rawDescGZIP(), []int{6}
}

func (x *BatchScreenResponse) GetResults() []*ScreenEntityResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_sanctions_sanctions_proto protoreflect.FileDescriptor

const file_sanctions_sanctions_proto_rawDesc = "" +
	"\n" +
	"\x19sanctions/sanctions.proto\x12\tsanctions\x1a\x13common/common.proto\"\x9c\x02\n" +
	"\x0eScreeningMatch\x12,\n" +
	"\x04list\x18\x01 \x01(\x0e2\x18.sanctions.ScreeningListR\x04list\x12\"\n" +
	"\rlist_entry_id\x18\x02 \x01(\tR\vlistEntryId\x12!\n" +
	"\fmatched_name\x18\x03 \x01(\tR\vmatchedName\x12:\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x0e2\x1a.sanctions.MatchConfidenceR\n" +
	"confidence\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x18\n" +
	"\aprogram\x18\x06 \x01(\tR\aprogram\x12'\n" +
	"\x0faction_required\x18\a \x01(\tR\x0eactionRequired\"\xb8\x01\n" +
	"\x13ScreenEntityRequest\x12\x1f\n" +
	"\ventity_name\x18\x01 \x01(\tR\n" +
	"entityName\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x1e\n" +
	"\n" +
	"identifier\x18\x04 \x01(\tR\n" +
	"identifier\x12%\n" +
	"\x0edeclaration_id\x18\x05 \x01(\x03R\rdeclarationId\"\xa5\x01\n" +
	"\x14ScreenEntityResponse\x12\x19\n" +
	"\bis_clear\x18\x01 \x01(\bR\aisClear\x123\n" +
	"\amatches\x18\x02 \x03(\v2\x19.sanctions.ScreeningMatchR\amatches\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12#\n" +
	"\rchecked_lists\x18\x04 \x01(\x05R\fcheckedLists\"\xaf\x01\n" +
	"\x13ScreenHSCodeRequest\x12\x17\n" +
	"\ahs_code\x18\x01 \x01(\tR\x06hsCode\x12+\n" +
	"\x11goods_description\x18\x02 \x01(\tR\x10goodsDescription\x12*\n" +
	"\x11country_of_origin\x18\x03 \x01(\tR\x0fcountryOfOrigin\x12&\n" +
	"\x0fcountry_of_dest\x18\x04 \x01(\tR\rcountryOfDest\"\xe9\x01\n" +
	"\x14ScreenHSCodeResponse\x12#\n" +
	"\ris_controlled\x18\x01 \x01(\bR\fisControlled\x12\x1e\n" +
	"\vis_dual_use\x18\x02 \x01(\bR\tisDualUse\x12)\n" +
	"\x10requires_license\x18\x03 \x01(\bR\x0frequiresLicense\x12&\n" +
	"\x0eclassification\x18\x04 \x01(\tR\x0eclassification\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12!\n" +
	"\flicense_type\x18\x06 \x01(\tR\vlicenseType\"P\n" +
	"\x12BatchScreenRequest\x12:\n" +
	"\bentities\x18\x01 \x03(\v2\x1e.sanctions.ScreenEntityRequestR\bentities\"P\n" +
	"\x13BatchScreenResponse\x129\n" +
	"\aresults\x18\x01 \x03(\v2\x1f.sanctions.ScreenEntityResponseR\aresults*\xbb\x01\n" +
	"\rScreeningList\x12\x1e\n" +
	"\x1aSCREENING_LIST_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bOFAC_SDN\x10\x01\x12\x0f\n" +
	"\vUN_SECURITY\x10\x02\x12\x13\n" +
	"\x0fEU_CONSOLIDATED\x10\x03\x12\v\n" +
	"\aOFSI_UK\x10\x04\x12\f\n" +
	"\bINTERPOL\x10\x05\x12\v\n" +
	"\aWCO_CEN\x10\x06\x12\x12\n" +
	"\x0eDUAL_USE_EAR99\x10\a\x12\x10\n" +
	"\fDUAL_USE_CCL\x10\b\x12\b\n" +
	"\x04ITAR\x10\t*]\n" +
	"\x0fMatchConfidence\x12 \n" +
	"\x1cMATCH_CONFIDENCE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05EXACT\x10\x01\x12\b\n" +
	"\x04HIGH\x10\x02\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x03\x12\a\n" +
	"\x03LOW\x10\x042\xba\x02\n" +
	"\x11SanctionsScreener\x12O\n" +
	"\fScreenEntity\x12\x1e.sanctions.ScreenEntityRequest\x1a\x1f.sanctions.ScreenEntityResponse\x12L\n" +
	"\vBatchScreen\x12\x1d.sanctions.BatchScreenRequest\x1a\x1e.sanctions.BatchScreenResponse\x12O\n" +
	"\fScreenHSCode\x12\x1e.sanctions.ScreenHSCodeRequest\x1a\x1f.sanctions.ScreenHSCodeResponse\x125\n" +
	"\x06Health\x12\x13.common.PageRequest\x1a\x16.common.HealthResponseB\x1eZ\x1ctradegateway/proto/sanctionsb\x06proto3"

var (
	file_sanctions_sanctions_proto_rawDescOnce sync.Once
	file_sanctions_sanctions_proto_rawDescData []byte
)

func file_sanctions_sanctions_proto_rawDescGZIP() []byte {
	file_sanctions_sanctions_proto_rawDescOnce.Do(func() {
		file_sanctions_sanctions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sanctions_sanctions_proto_rawDesc), len(file_sanctions_sanctions_proto_rawDesc)))
	})
	return file_sanctions_sanctions_proto_rawDescData
}

var file_sanctions_sanctions_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sanctions_sanctions_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sanctions_sanctions_proto_goTypes = []any{
	(ScreeningList)(0),            // 0: sanctions.ScreeningList
	(MatchConfidence)(0),          // 1: sanctions.MatchConfidence
	(*ScreeningMatch)(nil),        // 2: sanctions.ScreeningMatch
	(*ScreenEntityRequest)(nil),   // 3: sanctions.ScreenEntityRequest
	(*ScreenEntityResponse)(nil),  // 4: sanctions.ScreenEntityResponse
	(*ScreenHSCodeRequest)(nil),   // 5: sanctions.ScreenHSCodeRequest
	(*ScreenHSCodeResponse)(nil),  // 6: sanctions.ScreenHSCodeResponse
	(*BatchScreenRequest)(nil),    // 7: sanctions.BatchScreenRequest
	(*BatchScreenResponse)(nil),   // 8: sanctions.BatchScreenResponse
	(*common.PageRequest)(nil),    // 9: common.PageRequest
	(*common.HealthResponse)(nil), // 10: common.HealthResponse
}
var file_sanctions_sanctions_proto_depIdxs = []int32{
	0,  // 0: sanctions.ScreeningMatch.list:type_name -> sanctions.ScreeningList
	1,  // 1: sanctions.ScreeningMatch.confidence:type_name -> sanctions.MatchConfidence
	2,  // 2: sanctions.ScreenEntityResponse.matches:type_name -> sanctions.ScreeningMatch
	3,  // 3: sanctions.BatchScreenRequest.entities:type_name -> sanctions.ScreenEntityRequest
	4,  // 4: sanctions.BatchScreenResponse.results:type_name -> sanctions.ScreenEntityResponse
	3,  // 5: sanctions.SanctionsScreener.ScreenEntity:input_type -> sanctions.ScreenEntityRequest
	7,  // 6: sanctions.SanctionsScreener.BatchScreen:input_type -> sanctions.BatchScreenRequest
	5,  // 7: sanctions.SanctionsScreener.ScreenHSCode:input_type -> sanctions.ScreenHSCodeRequest
	9,  // 8: sanctions.SanctionsScreener.Health:input_type -> common.PageRequest
	4,  // 9: sanctions.SanctionsScreener.ScreenEntity:output_type -> sanctions.ScreenEntityResponse
	8,  // 10: sanctions.SanctionsScreener.BatchScreen:output_type -> sanctions.BatchScreenResponse
	6,  // 11: sanctions.SanctionsScreener.ScreenHSCode:output_type -> sanctions.ScreenHSCodeResponse
	10, // 12: sanctions.SanctionsScreener.Health:output_type -> common.HealthResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_sanctions_sanctions_proto_init() }
func file_sanctions_sanctions_proto_init() {
	if File_sanctions_sanctions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sanctions_sanctions_proto_rawDesc), len(file_sanctions_sanctions_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sanctions_sanctions_proto_goTypes,
		DependencyIndexes: file_sanctions_sanctions_proto_depIdxs,
		EnumInfos:         file_sanctions_sanctions_proto_enumTypes,
		MessageInfos:      file_sanctions_sanctions_proto_msgTypes,
	}.Build()
	File_sanctions_sanctions_proto = out.File
	file_sanctions_sanctions_proto_goTypes = nil
	file_sanctions_sanctions_proto_depIdxs = nil
}
