// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: sanctions/sanctions.proto

package sanctions

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "tradegateway/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SanctionsScreener_ScreenEntity_FullMethodName = "/sanctions.SanctionsScreener/ScreenEntity"
	SanctionsScreener_BatchScreen_FullMethodName  = "/sanctions.SanctionsScreener/BatchScreen"
	SanctionsScreener_ScreenHSCode_FullMethodName = "/sanctions.SanctionsScreener/ScreenHSCode"
	SanctionsScreener_Health_FullMethodName       = "/sanctions.SanctionsScreener/Health"
)

// SanctionsScreenerClient is the client API for SanctionsScreener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SanctionsScreenerClient interface {
	ScreenEntity(ctx context.Context, in *ScreenEntityRequest, opts ...grpc.CallOption) (*ScreenEntityResponse, error)
	BatchScreen(ctx context.Context, in *BatchScreenRequest, opts ...grpc.CallOption) (*BatchScreenResponse, error)
	ScreenHSCode(ctx context.Context, in *ScreenHSCodeRequest, opts ...grpc.CallOption) (*ScreenHSCodeResponse, error)
	Health(ctx context.Context, in *common.PageRequest, opts ...grpc.CallOption) (*common.HealthResponse, error)
}

type sanctionsScreenerClient struct {
	cc grpc.ClientConnInterface
}

func NewSanctionsScreenerClient(cc grpc.ClientConnInterface) SanctionsScreenerClient {
	return &sanctionsScreenerClient{cc}
}

func (c *sanctionsScreenerClient) ScreenEntity(ctx context.Context, in *ScreenEntityRequest, opts ...grpc.CallOption) (*ScreenEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScreenEntityResponse)
	err := c.cc.Invoke(ctx, SanctionsScreener_ScreenEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sanctionsScreenerClient) BatchScreen(ctx context.Context, in *BatchScreenRequest, opts ...grpc.CallOption) (*BatchScreenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchScreenResponse)
	err := c.cc.Invoke(ctx, SanctionsScreener_BatchScreen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sanctionsScreenerClient) ScreenHSCode(ctx context.Context, in *ScreenHSCodeRequest, opts ...grpc.CallOption) (*ScreenHSCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScreenHSCodeResponse)
	err := c.cc.Invoke(ctx, SanctionsScreener_ScreenHSCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sanctionsScreenerClient) Health(ctx context.Context, in *common.PageRequest, opts ...grpc.CallOption) (*common.HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.HealthResponse)
	err := c.cc.Invoke(ctx, SanctionsScreener_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SanctionsScreenerServer is the server API for SanctionsScreener service.
// All implementations must embed UnimplementedSanctionsScreenerServer
// for forward compatibility.
type SanctionsScreenerServer interface {
	ScreenEntity(context.Context, *ScreenEntityRequest) (*ScreenEntityResponse, error)
	BatchScreen(context.Context, *BatchScreenRequest) (*BatchScreenResponse, error)
	ScreenHSCode(context.Context, *ScreenHSCodeRequest) (*ScreenHSCodeResponse, error)
	Health(context.Context, *common.PageRequest) (*common.HealthResponse, error)
	mustEmbedUnimplementedSanctionsScreenerServer()
}

// UnimplementedSanctionsScreenerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSanctionsScreenerServer struct{}

func (UnimplementedSanctionsScreenerServer) ScreenEntity(context.Context, *ScreenEntityRequest) (*ScreenEntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScreenEntity not implemented")
}
func (UnimplementedSanctionsScreenerServer) BatchScreen(context.Context, *BatchScreenRequest) (*BatchScreenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchScreen not implemented")
}
func (UnimplementedSanctionsScreenerServer) ScreenHSCode(context.Context, *ScreenHSCodeRequest) (*ScreenHSCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScreenHSCode not implemented")
}
func (UnimplementedSanctionsScreenerServer) Health(context.Context, *common.PageRequest) (*common.HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedSanctionsScreenerServer) mustEmbedUnimplementedSanctionsScreenerServer() {}
func (UnimplementedSanctionsScreenerServer) testEmbeddedByValue()                           {}

// UnsafeSanctionsScreenerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SanctionsScreenerServer will
// result in compilation errors.
type UnsafeSanctionsScreenerServer interface {
	mustEmbedUnimplementedSanctionsScreenerServer()
}

func RegisterSanctionsScreenerServer(s grpc.ServiceRegistrar, srv SanctionsScreenerServer) {
	// If the following call panics, it indicates UnimplementedSanctionsScreenerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SanctionsScreener_ServiceDesc, srv)
}

func _SanctionsScreener_ScreenEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScreenEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SanctionsScreenerServer).ScreenEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SanctionsScreener_ScreenEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SanctionsScreenerServer).ScreenEntity(ctx, req.(*ScreenEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SanctionsScreener_BatchScreen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchScreenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SanctionsScreenerServer).BatchScreen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SanctionsScreener_BatchScreen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SanctionsScreenerServer).BatchScreen(ctx, req.(*BatchScreenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SanctionsScreener_ScreenHSCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScreenHSCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SanctionsScreenerServer).ScreenHSCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SanctionsScreener_ScreenHSCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SanctionsScreenerServer).ScreenHSCode(ctx, req.(*ScreenHSCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SanctionsScreener_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SanctionsScreenerServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SanctionsScreener_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SanctionsScreenerServer).Health(ctx, req.(*common.PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SanctionsScreener_ServiceDesc is the grpc.ServiceDesc for SanctionsScreener service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SanctionsScreener_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sanctions.SanctionsScreener",
	HandlerType: (*SanctionsScreenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScreenEntity",
			Handler:    _SanctionsScreener_ScreenEntity_Handler,
		},
		{
			MethodName: "BatchScreen",
			Handler:    _SanctionsScreener_BatchScreen_Handler,
		},
		{
			MethodName: "ScreenHSCode",
			Handler:    _SanctionsScreener_ScreenHSCode_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _SanctionsScreener_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sanctions/sanctions.proto",
}
