{{- if and (eq .Values.storage.backend "local") .Values.storage.local.enabled (not .Values.storage.local.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rustfs.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.local.accessMode }}
  {{- if .Values.storage.local.storageClass }}
  storageClassName: {{ .Values.storage.local.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.local.size }}
{{- end }}
