{{- if not .Values.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rustfs.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key: {{ .Values.credentials.accessKey | quote }}
  secret-key: {{ .Values.credentials.secretKey | quote }}
{{- end }}
---
{{- if and .Values.storage.openstack.enabled (not .Values.storage.openstack.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rustfs.fullname" . }}-openstack
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
type: Opaque
stringData:
  os-password: {{ .Values.storage.openstack.password | quote }}
{{- end }}
