apiVersion: v1
kind: Service
metadata:
  name: {{ include "rustfs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9000
      protocol: TCP
      name: s3-api
    - port: {{ .Values.service.consolePort }}
      targetPort: 9001
      protocol: TCP
      name: console
  selector:
    {{- include "rustfs.selectorLabels" . | nindent 4 }}
