#!/usr/bin/env bash
# microservices-config.sh — Print all microservice default env vars
# Run: bash scripts/microservices-config.sh
echo "=== TradeGateway Microservices Default Config ==="
echo "TEMPORAL_ADDRESS=localhost:7233"
echo "TEMPORAL_NAMESPACE=tradegateway"
echo "KAFKA_BROKERS=localhost:9092"
echo "TIGERBEETLE_ADDRESS=localhost:3001"
echo "FLUVIO_ADDRESS=localhost:9003"
echo "FLINK_CEP_URL=http://localhost:8081"
echo "KUBECOST_URL=http://kubecost.monitoring.svc.cluster.local:9090"
echo "OPENCTI_URL=http://localhost:8080"
echo "OPENCTI_TOKEN=opencti-default-token-CHANGE-IN-PRODUCTION"
echo "WAZUH_API_URL=https://localhost:55000"
echo "WAZUH_API_USER=wazuh-wui"
echo "KEYCLOAK_URL=http://localhost:8180"
echo "KEYCLOAK_REALM=tradegateway"
echo "KEYCLOAK_CLIENT_ID=tradegateway-api"
echo "ASEAN_SW_URL=https://asean-sw-gateway.asean.org/api/v1"
echo "WCO_CEN_URL=https://cen.wcoomd.org/api/v2"
echo "MOJALOOP_HUB_URL=http://localhost:3000"
echo "MOJALOOP_DFSP_ID=tradegateway-dfsp"
echo "=== Copy above to your environment or Kubernetes secrets ==="
